### ISSUE TITLE
Crash in GfxProcExternal::readbitmap when GfxProcessor is not set

### ISSUE THREAD

**Issue by zenden2k** [meganz/sdk#1019]
I have built MEGA SDK using MS Visual Studio 2013 without FreeImage library.
My app crashes when I try to upload a picture to my Mega account.

"Access violation reading location 0xCDCDCDCD."

```
bool GfxProcExternal::readbitmap(FileAccess* /*fa*/, string* localname, int /*size*/)
{
    if(!processor) return false;
    bool result = processor->readBitmap(localname->c_str());// <--- crashes here
```

It seems  that "processor" is being used without initialization.

**Comment by javiserrano** [comment]
Hi,

It's strange. The value of `processor` should be the one provided by the application in the constructor of the `MegaApi` object. How are you creating that object in your app?

**Comment by zenden2k** [comment]
It is not obvious that I SHOULD pass my own graphics processor if I compile without FreeImage.
I create mega api object this way:  

`megaApi_=new MegaApi(APP_KEY, (const char *)NULL, USER_AGENT);`

This code is executed inside megaapi_impl.cpp:

```
void MegaApiImpl::init(MegaApi *api, const char *appKey, MegaGfxProcessor* processor, const char *basePath, const char *userAgent, int fseventsfd)
{
...
	if(processor)
	{
		GfxProcExternal *externalGfx = new GfxProcExternal();
		externalGfx->setProcessor(processor);
		gfxAccess = externalGfx;
	}
	else
	{
		gfxAccess = new MegaGfxProc(); //<-----
	}
```

where MegaGfxProc is a subclass of GfxProcExternal:

```
#ifdef USE_QT
class MegaGfxProc : public GfxProcQT {};
#elif USE_FREEIMAGE
class MegaGfxProc : public GfxProcFreeImage {};
#elif TARGET_OS_IPHONE
class MegaGfxProc : public GfxProcCG {};
#else
class MegaGfxProc : public GfxProcExternal {};//<----
#endif
```

**Comment by javiserrano** [comment]
You are right. It's clearly a bug.

We haven't noticed it because we always use an internal processor or set an external one, otherwise no thumbnails and previews would be attached for uploaded images and videos.

This pull request should fix the problem https://github.com/meganz/sdk/pull/1022

Thank you very much for your report.
