### ISSUE TITLE
fetchNodes() reads the whole file system tree

### ISSUE THREAD

**Issue by glodos** [meganz/sdk#107]
I'm having problems using the fetchNodes() method, when connecting to accounts having many files. For example, fetching an account with over 1TB of files takes over 3 minutes. 

I would gladly skip calling it, but it's necessary to make other methods work, like getNodeByPath(). Why does it work like that?

The best solution imo would be to allow calling getNodeByPath() and other similar methods without a need to call the fetchNodes() first. Can it be achieved?

**Comment by javiserrano** [comment]
Unfortunately not (yet).
Currently, the only way to skip the request of all nodes from the server is to enable local caching and logging in with the session key.

To enable this feature, it's needed to enable SQLite in the compilation of the SDK, and to provide a folder to store database files in the constructor of MegaApi.

To use it, it's needed to get the session key (`MegaApi::dumpSession`) and to use it to log in the next time:
`void fastLogin(const char* session, MegaRequestListener *listener = NULL);`

If you need help to make it work, just ask here and I will try to help you.

We are working on the load of nodes on-demand, but it requires major changes in the SDK and support from the server side, so it will still take some time.

**Comment by glodos** [comment]
Thanks for your response, I've already set it up as you suggested. I guess next time I call `MegaApi::fetchNodes` it will only fetch differences between the local cache and server, is that right?

**Comment by javiserrano** [comment]
Exactly.

After a `fastLogin` with the session key, the next `fetchNodes` loads the MEGA filesystem from the local cache, and just after that, only the differences are got from servers.

But only the first `fetchNodes` after the login works that way. If you make more `fetchNodes` calls, the second and the following ones will get the whole filesystem from servers.
