### ISSUE TITLE
Uncompilable Java code generated with sdk > 3.2.0

### ISSUE THREAD

**Issue by ElanHD** [meganz/sdk#1188]
Hello, I am having some problems generating java code from sdk > 3.2.0. 

After successfully performing instruction I have next problem :

It's looks like JNI generator misses some values when generating source code. 
The main issue is with constants referenced in MegaJavaApi.java and must be located at 'MegaApi.java`, but apparently they are missing.

After poking around generated c++ code I found header file `sdk/include/megaapi.h` that actually contains those constants and they are in `#ifdef USE_LIBUV` statement. I thought I was missing this library, but even after I installed uv-dev library and `configure` script identified it, but nothing changed.

Some info on my system from console:
```
$cat /etc/*-release 
   PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
   NAME="Debian GNU/Linux"
   VERSION_ID="9"
   VERSION="9 (stretch)"
   ID=debian
$uname -a
   Linux *** 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
```

**Comment by sergiohs84** [comment]
Apologies for the late response. Do you still observe this issue with the current version of the SDK? If so, please, feel free to reopen the ticket.
