### ISSUE TITLE
Error running the MEGA SDK app in android studio   ||  Error al ejecutar la app SDK MEGA en android studio

### ISSUE THREAD

**Issue by johnx32** [meganz/sdk#1222]
Uso android studio en ubuntu 18, Al compilar no me detecta error pero al tratar de correr la app me sale error,  en android studio me sale este error, no soy experto en c++ o android quisiera su ayuda por favor
---------------------------------------------------------
I use android studio in ubuntu 18, When compiling I do not detect error but when trying to run the app I get an error, in android studio I get this error, I am not an expert in c ++ or android I would like your help please
----------------------------------------------------------
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:496: error: cannot find symbol
        return megaApi.multiFactorAuthAvailable();
                      ^
  symbol:   method multiFactorAuthAvailable()
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:514: error: cannot find symbol
        megaApi.multiFactorAuthCheck(email, createDelegateRequestListener(listener));
               ^
  symbol:   method multiFactorAuthCheck(String,MegaRequestListener)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:531: error: cannot find symbol
        megaApi.multiFactorAuthCheck(email);
               ^
  symbol:   method multiFactorAuthCheck(String)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:547: error: cannot find symbol
        megaApi.multiFactorAuthGetCode(createDelegateRequestListener(listener));
               ^
  symbol:   method multiFactorAuthGetCode(MegaRequestListener)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:561: error: cannot find symbol
        megaApi.multiFactorAuthGetCode();
               ^
  symbol:   method multiFactorAuthGetCode()
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:577: error: cannot find symbol
        megaApi.multiFactorAuthEnable(pin, createDelegateRequestListener(listener));
               ^
  symbol:   method multiFactorAuthEnable(String,MegaRequestListener)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:592: error: cannot find symbol
        megaApi.multiFactorAuthEnable(pin);
               ^
  symbol:   method multiFactorAuthEnable(String)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:608: error: cannot find symbol
        megaApi.multiFactorAuthDisable(pin, createDelegateRequestListener(listener));
               ^
  symbol:   method multiFactorAuthDisable(String,MegaRequestListener)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:623: error: cannot find symbol
        megaApi.multiFactorAuthDisable(pin);
               ^
  symbol:   method multiFactorAuthDisable(String)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:644: error: cannot find symbol
        megaApi.multiFactorAuthLogin(email, password, pin, createDelegateRequestListener(listener));
               ^
  symbol:   method multiFactorAuthLogin(String,String,String,MegaRequestListener)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:664: error: cannot find symbol
        megaApi.multiFactorAuthLogin(email, password, pin);
               ^
  symbol:   method multiFactorAuthLogin(String,String,String)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:682: error: cannot find symbol
        megaApi.multiFactorAuthChangePassword(oldPassword, newPassword, pin, createDelegateRequestListener(listener));
               ^
  symbol:   method multiFactorAuthChangePassword(String,String,String,MegaRequestListener)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:699: error: cannot find symbol
        megaApi.multiFactorAuthChangePassword(oldPassword, newPassword, pin);
               ^
  symbol:   method multiFactorAuthChangePassword(String,String,String)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:718: error: cannot find symbol
        megaApi.multiFactorAuthChangeEmail(email, pin, createDelegateRequestListener(listener));
               ^
  symbol:   method multiFactorAuthChangeEmail(String,String,MegaRequestListener)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:736: error: cannot find symbol
        megaApi.multiFactorAuthChangeEmail(email, pin);
               ^
  symbol:   method multiFactorAuthChangeEmail(String,String)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:757: error: cannot find symbol
        megaApi.multiFactorAuthCancelAccount(pin, createDelegateRequestListener(listener));
               ^
  symbol:   method multiFactorAuthCancelAccount(String,MegaRequestListener)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:776: error: cannot find symbol
        megaApi.multiFactorAuthCancelAccount(pin);
               ^
  symbol:   method multiFactorAuthCancelAccount(String)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/sdk/MegaApiJava.java:3572: error: cannot find symbol
        megaApi.isMasterKeyExported(createDelegateRequestListener(listener));
                        ^
  symbol:   method isMasterKeyExported(MegaRequestListener)
  location: variable megaApi of type MegaApi
/root/AndroidStudioProjects/ExampleApp/app/src/main/java/nz/mega/android/bindingsample/MainActivity.java:68: error: cannot find symbol
			String privateKey = megaApi.getBase64PwKey(args[1]);
			                                              ^

**Comment by sergiohs84** [comment]
It looks like you have to update the `libmega.so` and generate bindings again. Please, give it a try with the updated repository (`develop`) and feel free to reopen the ticket if you still observe the issue.
