### ISSUE TITLE
Unable to compile megafuse in example/linux/

### ISSUE THREAD

**Issue by topjohnwu** [meganz/sdk#128]
I followed the instructions, which told me to include --enable-fuse in ./configure.
But it seems that it couldn't recognize it, giving me this error:

configure: WARNING: unrecognized options: --enable-fuse

Any help?

**Comment by wizzard** [comment]
Hello,
there was a mistake in the documentation file, the correct configure argument is ```---with-fuse```.

Thank you for pointing out this issue!

**Comment by topjohnwu** [comment]
Thanks a lot :)
BTW, I cannot get megafuse compile on OS X 10.10, it gave me this while configuring:

checking for FUSE... yes
checking fuse.h usability... no
checking fuse.h presence... no
checking for fuse.h... no
configure: error: fuse.h header not found or not usable

I can get the whole sdk to compile, and I had OSXFuse installed, anyway to fix it?

**Comment by wizzard** [comment]
We never tested our FUSE example on MacOS, theoretically it should work. 
I'd recommend you to find fuse.h header on your system and then specify folder with the header in “path” argument: ```--with-fuse=PATH``` (e.g.: --with-fuse=/usr/local/include )

**Comment by FreeSpirit9009** [comment]
I have the same issue with Ubuntu 16.04. fuse.h is present at /usr/include/linux, but when I run ./configure --with-fuse=/usr/include/linux I get this:

checking for rl_save_prompt in -lreadline... yes
checking for FUSE... /usr/include/linux
checking fuse.h usability... no
checking fuse.h presence... no
checking for fuse.h... no
configure: error: fuse.h header not found or not usable

**Comment by polmr** [comment]
that fuse.h is somewhat unusable for this use case. Install  `libfuse-dev` and try again without explicit `--with-fuse` flag.
