### ISSUE TITLE
MegaNode  set attributes

### ISSUE THREAD

**Issue by dima72** [meganz/sdk#129]
Dear All,

I'm looking for method to save some extra information along with remote file. 
e.g. FileDescription, Memo  

are there such features in MegaApi?

thanks,

**Comment by javiserrano** [comment]
Oops, I forgot to reply to this question :-/
It's supported by MEGA servers and implemented in the "low level" SDK (`MegaClient::setattr`) but not in the intermediate layer (`MegaApi`) yet.

**Comment by dima72** [comment]
Dear Javi,
thanks for mentioning about this,
we are avaiting this feature in Api too.

**Comment by javiserrano** [comment]
I have just created a pull request with this feature:
https://github.com/meganz/sdk/pull/177/files

Since it's quite simple, it will be merged in `master` during this week.

**Comment by dima72** [comment]
thank you Javi

**Comment by javiserrano** [comment]
That feature is already merged on `master`.
If you find any problem, please open the issue again or create a new one.
Thanks to you for using MEGA!
