### ISSUE TITLE
changePassword  API returns  -2 (Invalid args)

### ISSUE THREAD

**Issue by wanglinSZ** [meganz/sdk#1296]
I using Mega SDK(V3.4.4)  downloaded from your office github and complie it myself refer to this introduction (https://github.com/meganz/sdk/tree/v3.4.4/bindings/doc/java ).
     When i using the changePassword function in MegaApiJava, it returns  -2 (Invalid args).I checked the all the old and new password are correct in MegaRequest.Can someone help me?

 public void changePassword(String oldPassword, String newPassword, MegaRequestListenerInterface listener) {
        megaApi.changePassword(oldPassword, newPassword, createDelegateRequestListener(listener));
    }

**Comment by polmr** [comment]
Try to pass NULL as oldPassword

**Comment by wanglinSZ** [comment]
If i put the old password to NULL,the  changePassword interface returns -11 (Access denied) errors.

**Comment by wanglinSZ** [comment]
My test code:`@Before
	public void init() throws Exception {
		megaApi = new MegaApiJava(APP_KEY, USER_AGENT, null, null);
	}

	@Test
	public void testChangePassword() {
		CountDownLatch countDownLatch = new CountDownLatch(1);
		CountDownLatch countDownLatch2 = new CountDownLatch(1);
		List<MegaError> listMegaError = new ArrayList<>(1);

		megaApi.login(EMAIL, OLD_PASSWORD, new MegaRequestListenerInterface() {

			@Override
			public void onRequestUpdate(MegaApiJava api, MegaRequest request) {
				// TODO Auto-generated method stub

			}

			@Override
			public void onRequestTemporaryError(MegaApiJava api, MegaRequest request, MegaError e) {
				listMegaError.add(e);
				countDownLatch.countDown();

			}

			@Override
			public void onRequestStart(MegaApiJava api, MegaRequest request) {
				// TODO Auto-generated method stub

			}

			@Override
			public void onRequestFinish(MegaApiJava api, MegaRequest request, MegaError e) {
				if (e.getErrorCode() != MegaError.API_OK) {
					listMegaError.add(e);
				}
				countDownLatch.countDown();
			}
		});

		try {
			// todo time out
			countDownLatch.await(600, TimeUnit.SECONDS);
		} catch (InterruptedException e) {
			System.out.println("Login exception:" + e.getMessage());
		}

		if (!listMegaError.isEmpty()) {
			System.out.println("Login error." + listMegaError.get(0).getErrorCode());
		}

		if (megaApi.isLoggedIn() == 0) {
			System.out.println("Not Login .");
		} else {
			
			System.out.println("Login success .");
			
			listMegaError.clear();
			
			megaApi.changePassword(OLD_PASSWORD, NEW_PASSWORD, new MegaRequestListenerInterface() {

				@Override
				public void onRequestUpdate(MegaApiJava api, MegaRequest request) {
					// TODO Auto-generated method stub

				}

				@Override
				public void onRequestTemporaryError(MegaApiJava api, MegaRequest request, MegaError e) {
					listMegaError.add(e);
					countDownLatch2.countDown();

				}

				@Override
				public void onRequestStart(MegaApiJava api, MegaRequest request) {
					// TODO Auto-generated method stub

				}

				@Override
				public void onRequestFinish(MegaApiJava api, MegaRequest request, MegaError e) {
					if (e.getErrorCode() != MegaError.API_OK) {
						listMegaError.add(e);
					}
					countDownLatch2.countDown();

				}
			});

			try {
				// todo time out
				countDownLatch2.await(600, TimeUnit.SECONDS);
			} catch (InterruptedException e) {
				System.out.println("Change password exception:" + e.getMessage());
			}
			
			if (!listMegaError.isEmpty()) {
				System.out.println("Change password error." + listMegaError.get(0).getErrorCode());
			}else
			{
				System.out.println("Change");
			}
		}

	}`

**Comment by sergiohs84** [comment]
Closing this ticket, too old. Feel free to re-open if you still observe the issue. Thanks
