### ISSUE TITLE
Cannot compile without ENABLE_SYNC

### ISSUE THREAD

**Issue by RafalSkorka** [meganz/sdk#1305]
Hi!
Is it possible to compile without ENABLE_SYNC on Windows? Right now I am getting errors due to `localrootnode` is used in `void WinDirNotify::process(DWORD dwBytes)` but not defined if ENABLE_SYNC is not defined.
Thank you!

**Comment by polmr** [comment]
🤔 It should be possible: `localrootnode` is defined when !ENABLE_SYNC: https://github.com/meganz/sdk/blob/develop/include/mega/win32/megafs.h#L93 .

**Comment by RafalSkorka** [comment]
Yes, but the LocalNode type is not defined when ENABLE_SYNC is not declared.

**Comment by polmr** [comment]
Alright. You might want to try this branch: https://github.com/meganz/sdk/tree/fixnotenablesyncwindows
