### ISSUE TITLE
iOS stream for MPVideoPlayer

### ISSUE THREAD

**Issue by logikaljay** [meganz/sdk#131]
Is it possible to use the mega api to stream to a format to play in MPMoviePlayer?

Like the actual mega app does on the App Store.

I see from the mega app's syslog output that it creates a local url to http://127.0.0.1:52079/123...456.mp4

Just wondering on the best way to achieve video playback from video stored on mega.

**Comment by jnavarrom** [comment]
Yes, you need implement a http server in the application.

You should use the next method for start a streaming download

```Objective-C
/**
 * @brief Start a streaming download
 *
 * Streaming downloads don't save the downloaded data into a local file. It is provided 
 * in the callback [MEGATransferDelegate onTransferData:transfer:]. Only the MEGATransferDelegate
 * passed to this function will receive [MEGATransferDelegate onTransferData:transfer:] callbacks.
 * MEGATransferDelegate objects registered with [MEGASdk addMEGATransferDelegate:] won't 
 * receive them for performance reasons.
 *
 * @param node MEGANode that identifies the file (public nodes aren't supported yet)
 * @param startPos First byte to download from the file
 * @param size Size of the data to download
 * @param delegate MEGATransferDelegate to track this transfer
 */
- (void)startStreamingNode:(MEGANode *)node startPos:(NSNumber *)startPos size:(NSNumber *)size delegate:(id<MEGATransferDelegate>)delegate;
```

and implement the next one from MEGATransferDelegate

```Objective-C
/**
 * @brief This function is called to provide the last readed bytes of streaming downloads
 *
 * This function won't be called for non streaming downloads.
 *
 * @param api MEGASdk object that started the transfer
 * @param transfer Information about the transfer
 * @param buffer Buffer with the last readed bytes
 * @param size Size of the buffer
 * @return YES to continue the transfer, NO to cancel it
 *
 * @see [MEGASdk startStreamingNode:startPos:size:]
 */
- (BOOL)onTransferData:(MEGASdk *)api transfer:(MEGATransfer *)transfer buffer:(NSData *)buffer;
```

**Comment by logikaljay** [comment]
Thank you for your help - I got most of the way there last night, I was just trying to work the download, storing all of the incomming `onTransferData NSData buffer` in a NSMutableData object and writing it to a file each time, and then starting to play the file `onTransferStart` but did not have any luck. I guess a HTTP server makes sense.

**Comment by logikaljay** [comment]
Hoping you can give me a bit more guidence as I have tried everything I can think of and it still is not working:

* I have a webserver setup on 127.0.0.1:8080 (using CocoaHTTPServer - GCDWebServer wouldn't work for some reason - many complaints about `#import <memory> file not found` etc) serving a document root of /Users/me/tmp (running fine on simulator, will have to change for devices)
* I have modified your iOS example's `- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath;` method to include:
```objc
        case MEGANodeTypeFile: {
            NSString *name = [node name];
            if (isImage(name.lowercaseString.pathExtension)) {
                ... original code ...
            } else if (isVideo(name.lowercaseString.pathExtension)) {
                [[MEGASdkManager sharedMEGASdk] startStreamingNode:node startPos:0 size:[node size] delegate:self];
            }
            break;
        }
```

* I have added the delegate `MEGATransferDelegate` to `CloudDriveTableViewController`
* I have implemented the following methods:
```objc
- (void)onTransferStart:(MEGASdk *)api transfer:(MEGATransfer *)transfer
{
    stream = [[[NSData alloc] init] mutableCopy];
}
```

```objc
- (BOOL)onTransferData:(MEGASdk *)api transfer:(MEGATransfer *)transfer buffer:(NSData *)buffer
{
    
    NSString *filePath = @"/Users/me/tmp/tmp.mp4";
    
    [stream appendData:buffer];
    [stream writeToFile:filePath atomically:NO];
    
    return YES;
}
```
* I have added the following method to play the video:
```objc
-(void)playVideo:(NSString *)url
{
    self.videoController = [[MPMoviePlayerViewController alloc] initWithContentURL:[NSURL URLWithString:url]];
    [self.videoController.moviePlayer prepareToPlay];
    [self.videoController.moviePlayer setShouldAutoplay:YES];
    [self presentMoviePlayerViewControllerAnimated:self.videoController];
    [self.videoController.moviePlayer play];
}
```

* I have tried calling `[self playVideo:@"http://localhost:8080/tmp.mp4"]` from numerous places, including:
  1. below the `[MEGASdkManager startStreamingNode]` call: black screen appears, file does not play.
  2. in `- (void)onTransferStart:(MEGASdk *)api transfer:(MEGATransfer *)transfer`: black screen appears, file does not play - side note: this method is called twice for some reason.
  3. in `- (BOOL)onTransferData:(MEGASdk *)api transfer:(MEGATransfer *)transfer buffer:(NSData *)buffer` with a `BOOL playing` instance variable to make sure it is only called once: black screen, unresponsive player.

* I have tested to see if the file is being created in /Users/me/tmp/ - it is getting created and written to just fine.
* I have tested to see if the webserver is functioning - I am able to use chrome/safari to download the file http://127.0.0.1:8080/tmp.mp4
* I have tested to see if the partially downloaded file is corrupt in any way, ffprobe says that it is fine, even before it has finished downloading completely.
* I have tested the file once it has fully downloaded and it does work fine, but not when called from `onTransferFinish`

I am completely out of ideas now as to how to make this work. every way i try to play the video i get a black screen.

If it makes it easier, I can push my changes to a fork, however there really isnt that many

**Comment by jnavarrom** [comment]
I guess you can use `CocoaHTTPServer`, but we use our custom classes using standard sockets.

In `- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath;` when the user taps on video file we create a link with our internal Http server and use this link for init a `MPMoviePlayerViewController`

```Objective-C
if (isVideo(name.pathExtension)) {
                NSURL *link = [NSURL URLWithString:[NSString stringWithFormat:@"http://127.0.0.1:%llu/%lld.%@", [[MEGAProxyServer sharedInstance] port], node.handle, node.name.pathExtension.lowercaseString]];
                if (link) {
                    MPMoviePlayerViewController *moviePlayerViewController = [[MPMoviePlayerViewController alloc] initWithContentURL:link];
                    
                    [self presentMoviePlayerViewControllerAnimated:moviePlayerViewController];
                    
                    [moviePlayerViewController.moviePlayer prepareToPlay];
                    [moviePlayerViewController.moviePlayer play];
                    
                    return;
                }   
            }
```

`MEGAProxyServer` creates, binds and listens a native socket. This socket accepts connections, for each connection you should create a request, create and open a read and a write streams. Then you receive a response for each request, and you need  parse the header. This header gives you a range with location and length, you should use those values as a parameters of `startStreamingNode`, location is the startPos and length is the size.


Doesn't make sense call `startStreamingNode` with the start position 0 and size the node size and create a file with the content of the node, this is the same as download a node.

**Comment by logikaljay** [comment]
Ugh, that makes A LOT more sense than the way I was doing it - Thank you. I will try this out throughout the day today and let you know how I get on.

**Comment by jnavarrom** [comment]
Hi @logikaljay 

We have added a HTTP Proxy server in the intermediate layer and in the iOS binding, maybe you are interesting in this new feature. Take a look at this pull request https://github.com/meganz/sdk/pull/218.

**Comment by logikaljay** [comment]
Hey @jnavarrom, 

Thanks for remembering me! I will take a look - thanks very much

**Comment by mduplifting** [comment]
Can you add streaming feature to Demo project?

**Comment by jnavarrom** [comment]
You can take a look in the iOS repository: https://github.com/meganz/iOS3

https://github.com/meganz/iOS3/blob/master/iMEGA/Cloud%20drive/CloudDriveTableViewController.m#L353

https://github.com/meganz/iOS3/blob/master/iMEGA/Categories/MEGANode%2BMNZCategory.m#L83

https://github.com/meganz/iOS3/blob/master/iMEGA/Utils/MEGAAVViewController.m

**Comment by mduplifting** [comment]
Thank you!
