### ISSUE TITLE
[Xcode, IOS-Swift] symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by TruongKhanhHung** [meganz/sdk#1329]
I dragged the folder "sdk-3.4.5" into my ios-swift project. I have inherited "MEGARequestDelegate" in class "AppDelegate" and build app xcode "build succeeded" message.

But when I the declaration "let megaapi: MEGASdk = MEGASdk (appKey:" *** ", userAgent:" *** ")" then the error: 

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MEGASdk", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

How can I fix it? Thank you!

**Comment by jnavarrom** [comment]
Looks like you are not compiling the MEGA SDK.

You can check out how it's done at https://github.com/meganz/iOS

We have a workspace with three project: MEGA (the application code, your swift code), MEGASDK (build the sdk static library) and Karere (build the karere static library). Also, you would need the third party libraries and headers: libc-ares, libcryptopp, libcurl, libmediainfo, libsodium, libuv and libzen

The steps are (without Karere support):
1. Create a workspace.
2. Create a Swift project and add this project to the workspace
3. Download or clone the SDK add the MEGASDK.xcodeproj (bindings/ios) to the workspace
4. Download the prebuilt third party dependencies from this link: https://mega.nz/#!kAsQia7A!6-E0wO2N8BwSGfucwQRQ0mEWU1Yz-s-OjbaG3Vixb0M
5. Uncompress that file and move the folders webrtc , include and lib into bindings/ios/3rdparty
6. In the Swift project -> tarjets -> Link Binary With Library libMEGASDK.a
7. In the Swift project -> Build settings -> update the User Headers Search Paths
8. Add the Objective-C Bridging Header and add `#import "MEGASDk.h"`

![screenshot 2019-01-14 at 14 42 25](https://user-images.githubusercontent.com/3861964/51116221-d099f100-180a-11e9-819f-7f5b6a9e8d3d.png)
![screenshot 2019-01-14 at 14 42 51](https://user-images.githubusercontent.com/3861964/51116250-e0b1d080-180a-11e9-9da1-96b9b1d6c2c8.png)
![screenshot 2019-01-14 at 14 43 18](https://user-images.githubusercontent.com/3861964/51116251-e1e2fd80-180a-11e9-9e91-dfcd4b058872.png)

**Comment by TruongKhanhHung** [comment]
@jnavarrom Thank you so much! I will try it and give you feedback
