### ISSUE TITLE
./configure --with-libraw got an error

### ISSUE THREAD

**Issue by niheaven** [meganz/sdk#1330]
I'm using this sdk in compile megacmd in OSX, and `./configure --with-libraw` got the following error:

```
checking for libraw... checking libraw/libraw.h usability... yes
checking libraw/libraw.h presence... yes
checking for libraw/libraw.h... yes
checking for libraw_init in -lraw... no
configure: error: Could not find libraw
configure: error: ./configure failed for sdk
```

I use `brew install libraw` to install libraw, and the same error occurs whether with-bottle or install-from-source. What's wrong with me?

OS: macOS 10.14.2
MEGAcmd: 1.0.0
SDK: @ https://github.com/meganz/sdk/commit/f3a3b810619fb1e671b8a68ad58c2cded51ee63a as MEGAcmd / current master (@ https://github.com/meganz/sdk/commit/975d2996ded16ef695b460f652ad9f106b7e5d0e)
libraw: 0.19.0 as bottle / 0.19.2 build from source

**Comment by polmr** [comment]
It seems that configure checks are failing to link with libraw for some reason.
`config.log` should show what the errors are at some point. 
You could enforce libraw by changing
```
AC_CHECK_LIB(raw, [libraw_init], [LIBRAW_LIBS="$LIBRAW_LIBS -lraw -fopenmp"],[
            AC_MSG_ERROR([Could not find libraw])
    ])
```
by
```
AC_CHECK_LIB(raw, [libraw_init], [LIBRAW_LIBS="$LIBRAW_LIBS -lraw -fopenmp"],[LIBRAW_LIBS="$LIBRAW_LIBS -lraw -fopenmp"])
```
in configure.ac [here](https://github.com/meganz/sdk/blob/f3a3b81/configure.ac#L615)
and do execute `autogen.sh` again. 
But if the configure check fails, it's likely that it'll fail again when compiling/linking the sdk.
As a reference: we have been able to compile it with 0.19.0 from source.

**Comment by niheaven** [comment]
Thanks. I've checked `config.log` and found

```
configure:20353: checking for libraw_init in -lraw
configure:20378: g++ -o conftest -g -O2 -DNDEBUG=1 -fPIC   conftest.cpp -lraw  -ldl  -fopenmp >&5
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
configure:20378: $? = 1
```

So obviously this is a Xcode's gcc fault that this clang doesn't support openmp...

I'll check for some solution about it, an thanks again.

**Comment by niheaven** [comment]
@polmr 
I'm looking for some advises... You said that you have been able to compile MEGAcmd with LibRaw 0.19.0, is it on macOS? And what is the configure arguments? I could build LibRaw with OpenMP enabled, but when configure MEGAcmd, the error happened again.

**Comment by polmr** [comment]
Hi @niheaven , yes, with MacOS, IIRC it was compiled with `--with-libraw=/path/to/libraw/install/dir`. Being `/path/to/libraw/install/dir` the path passed to libraw 0.19.0 configuration in --prefix *. Why don't you remove the `-fopenmp` from configure.ac [here](https://github.com/meganz/sdk/blob/f3a3b81/configure.ac#L615) and [here](https://github.com/meganz/sdk/blob/f3a3b81/configure.ac#L636) and then run 
```
./autogen.sh
./configure --with-libraw
```
What's your g++ version (`g++ --version`)?
* Actually our compilation with libraw in mac was not done via autotools, but with Qt, and in the end we link it with just `-lraw`. If the proposed solution of removing `-fopenmp` in configure tests, we can modify it not to add it in case `clang` is used. Please, let us know

**Comment by niheaven** [comment]
Thanks @polmr, I've tested remove all `-fopenmp` flags in `comfigure.ac` and the configure pass, `make` works as well.

I use Apple Xcode gcc, e.g.

```zsh
$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
