### ISSUE TITLE
Android: fail to build mega sdk with ndk r16

### ISSUE THREAD

**Issue by wangzhenyan12** [meganz/sdk#1360]
Hi,
Mega sdk developers.

I tried to build mega sdk with ndk r16, but failed with the error message such as:
_**error: no member named 'fgetpos' in the global namespace using ::fgetpos
Referring to 
https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md
https://android.googlesource.com/platform/bionic/+/master/docs/32-bit-abi.md
I have tried 2 methods to fix the issue:
1. raised APP_PLATFORM to 24 in Application.mk and it worked well to build.
2. Disable _FILE_OFFSET_BITS=64 in the mega sdk source code (/examples/android/ExampleApp/app/src/main/jni/mediainfo/Android.mk, /src/megaapi_impl.cpp, /include/mega/config-android.h). 
There was a link error in zenlib as following: undefined reference to 'wctomb'.

mega sdk version: develop branch @a883c23

Cheers,
Jason

**Comment by sergiohs84** [comment]
We are using NDK 27 already. Closing this ticket as obsolete
