### ISSUE TITLE
MegaApiJava.getBase64PwKey()

### ISSUE THREAD

**Issue by IcerAndroid** [meganz/sdk#1382]
Hi,I am an android developer .when i use the Mega sdk,I can't find this method “getBase64PwKey” in jni. so i can't use the fastLogin method. Help me! Help me! Help me!

**Comment by sergiohs84** [comment]
Hi there
The usage of that function should not be required in your new development. Note the `MegaApi::fastConfirmAccount()` is deprecated. Please use `MegaApi::confirmAccount()` instead.
