### ISSUE TITLE
Import from a proprietary library in Java bindings for Android

### ISSUE THREAD

**Issue by gilbsgilbs** [meganz/sdk#1471]
Hi,

I'm trying to use the java bindings in an Android App. To make it work, I have to patch `AndroidGfxProcessor.java` manually because [it imports a utility function from the MEGA Android app](https://github.com/meganz/sdk/blob/80f4fcdcb742e7f9cd9a0028af85ef23e325760e/bindings/java/nz/mega/sdk/AndroidGfxProcessor.java#L25). This Android app is [proprietary software](https://github.com/meganz/android/blob/master/LICENCE.md) that I am not allowed to include in my bundles.

I can see many solutions:
- Include this utility function into the SDK itself
- Use `Log.d` function from Android framework directly
- Make the Android App free software (which is a bad solution IMO, but would be a good thing to do in any case because I'm working on stuff that I could definitely contribute directly to the Android App)

Some other issues I came across while building JNIs:
- [Still have to use an outdated version of the NDK](https://github.com/meganz/sdk/issues/1360)
- Unlike [what is stated in README](https://github.com/meganz/sdk/tree/develop/examples/android/ExampleApp#to-build-the-library-by-yourself), `NDK_ROOT` environment variable is ignored and the NDK is assumed to be located in `${HOME}/android-ndk` in `build.sh` script.
- Pretty much every dependency in the JNI are outdated and got a lot of security patches since then.

Let me know if you want me to open new issues for this.

**Comment by sergiohs84** [comment]
Old ticket. Closing...
