### ISSUE TITLE
Provide binary releases

### ISSUE THREAD

**Issue by gregkotsaftis** [meganz/sdk#150]
I am a Java dev and need a DLL in order to use JNA to call it's methods (SWIG is just an overkill for simple tasks).
I am not up to the task to build the source code and all it's dependencies with c++, so I kindly request binary releases as well.

**Comment by sergiohs84** [comment]
Hi Greg

We're aware of the complexity of building your own DLL for JNI usage, so we do provide a pre-built binary for quick tests and examples purposes, like in `/sdk/examples/java/`. You can follow the instructions here to setup your project: https://github.com/meganz/sdk/tree/master/examples/java

Also, you can download the DLL file from this link: https://mega.nz/#!B4cx1KoA!GWYOcP0mp5_n6ouUEv27BKSkRcPGj9x17Eos6S72NB8

Regards
