### ISSUE TITLE
how to binding python with mega sdk

### ISSUE THREAD

**Issue by angga30** [meganz/sdk#1524]
i can't import megaAPI.

**Comment by Ammadkhalid** [comment]
I'm having same issue. I follow steps described at OSX.txt and successfully able to install sdk. However when i run:

```
➜  dist git:(master) ls
➜  dist git:(master) pip install megasdk-3.6.1-py2.py3-none-any.whl --force-reinstall
Processing ./megasdk-3.6.1-py2.py3-none-any.whl
Installing collected packages: megasdk
Successfully installed megasdk-3.6.1
➜  dist git:(master) ipython
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import mega
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-e937ebf229d0> in <module>
----> 1 import mega

/usr/local/anaconda3/lib/python3.7/site-packages/megasdk-3.6.1-py3.7.egg/mega/__init__.py in <module>
      1 # Get rid of the funny nested name space.
----> 2 from .mega import *

ModuleNotFoundError: No module named 'mega.mega'

In [2]:
```

python version:
`Python 3.7.3`

thanks! i also tried to install for python2.7 but nope still same issue.

**Comment by lzzy12** [comment]
@Ammadkhalid this error is because of a faulty documentation for the installation process of the python binding. 
The documentation says in order to configure the build, you have to run the following command:
Configure the project for Python:
`./autogen.sh ./configure --disable-silent-rules --enable-python --disable-examples `

However, the corrent way to do it for enabling python support in the sdk is 
```
./autogen.sh 
./configure --disable-silent-rules --enable-python --disable-examples
```
Those are 2 different commands, probably they missed a line break while writing it.

**Comment by Ammadkhalid** [comment]
i was trying this out but it shows me. Maybe because of python version?

```
python3.7/site-packages/mega
▶ ipython
fPython 3.7.4 (default, Sep  7 2019, 18:27:02)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from mega import Mega
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-77855baa84ed>", line 1, in <module>
    from mega import Mega

  File "/usr/local/lib/python3.7/site-packages/mega/mega.py", line 88
    0L, self.rsa_private_key[2], self.rsa_private_key[0],
     ^
SyntaxError: invalid syntax


In [2]:```

**Comment by Ammadkhalid** [comment]
Now in python 2. it import successfully but when i tried to important. I Get this error:
>>> mega = Mega()
>>> mega.login_user('<User>', '<Password>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/mega/mega.py", line 50, in login_user
    self._login_common(res, password_aes)
  File "/usr/local/lib/python2.7/site-packages/mega/mega.py", line 66, in _login_common
    enc_master_key = base64_to_a32(res['k'])
TypeError: 'int' object has no attribute '__getitem__'
>>>
```
i replaced my actual login with`<User>` and `<Password>'
