### ISSUE TITLE
Python MegaRequestListener Implement?

### ISSUE THREAD

**Issue by RiceeeChang** [meganz/sdk#156]
I try to get the file public key with below code revised from crud_example2.py 

    def upload(local_path, remote_path='/'):
        path_node = api.getNodeByPath(remote_path, cwd)
        if path_node:
            executor.do(api.startUpload, (local_path, path_node))
            filename = local_path.split('/')[-1]

            export_node = api.getNodeByPath(filename, path_node)
            export_listener = ExportListener()
            
            executor.do(api.exportNode, (export_node, export_listener))
            return export_listener.link
        else:
            return None

    class ExportListener(MegaRequestListener):
        def onRequestFinish(self, api, request,error):
            self.link = request.getLink()
            if not self.link:
                print error

and i run with the error message

      File "/home/rice/mods/pymega.py", line 44, in upload
        return export_listener.link
      File "/usr/local/lib/python2.7/dist-packages/mega/mega.py", line 605, in <lambda>
        __getattr__ = lambda self, name: _swig_getattr(self, MegaRequestListener, name)
      File "/usr/local/lib/python2.7/dist-packages/mega/mega.py", line 57, in _swig_getattr
        raise AttributeError(name)
      AttributeError: link

**Comment by javiserrano** [comment]
Sorry for our late reply.

Your code seems to be OK. I have used it and it works for me with the current version of the SDK in the `master` branch. The problem could be related with your version of SWIG. Which version are you using?

If you can provide a minimal but complete example that we could directly run, we would check it better with your version of SWIG and I think that we would find the problem.
