### ISSUE TITLE
How to build this library

### ISSUE THREAD

**Issue by hbtalha** [meganz/sdk#1582]
Dear all, I am a c++ beginner and  I would like to build this library but I don't know to do it. I am windows user.
I have looked everywhere with no luck so far.
I tried to run the visual studio project in the examples folder but it gave me 680 error.

These errors are some of ones I found going through the build log:

include\chrono(786): error C2440: '<function-style-cast>': cannot convert from '__int64' to 'std::chrono::system_clock::duration'

include\ratio(73): error C2065: 'INTMAX_MAX': undeclared identifier

include\chrono(767): error C2938: 'std::ratio_multiply<std::ratio<100,1>,std::nano>' : Failed to specialize alias template

\include\chrono(767): error C2938: 'std::ratio_multiply<std::ratio<100,1>,std::nano>' : Failed to specialize alias template

**Comment by sergiohs84** [comment]
Hi there. Can you tell us the commit of the SDK you are using and the version of Visual Studio? Thanks

**Comment by hbtalha** [comment]
Hello, I am using Visual Studio 2017. From: Sergio HernándezSent: Wednesday, December 18, 2019 15:39To: meganz/sdkCc: hbtalha; AuthorSubject: Re: [meganz/sdk] How to build this library (#1582) Hi there. Can you tell us the commit of the SDK you are using and the version of Visual Studio? Thanks—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by sergiohs84** [comment]
I suggest you 2 different ways:
1. Install VS 2015 and try to build the example: https://github.com/meganz/sdk/tree/develop/examples/win32
2. Use VS 2017 by importing the project from CMake configuration files: https://github.com/meganz/sdk/tree/develop/contrib/cmake

**Comment by hbtalha** [comment]
I’ve installed VS 2015  and tried to build the example but it is giving me these errors From: Sergio HernándezSent: Thursday, December 19, 2019 12:58To: meganz/sdkCc: hbtalha; AuthorSubject: Re: [meganz/sdk] How to build this library (#1582) I suggest you 2 different ways:Install VS 2015 and try to build the example: https://github.com/meganz/sdk/tree/develop/examples/win32Use VS 2017 by importing the project from CMake configuration files: https://github.com/meganz/sdk/tree/develop/contrib/cmake—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hbtalha** [comment]
I've installed VS 15 but when trying to buid the example it gives a bunch of errors in the library 'chrono;

**Comment by sergiohs84** [comment]
Have you tried by adding the definition of `__STDC_LINMIT_MACROS` to the pre-compiler processing?? If it does not solve your issue, would you mind to post here the detailed steps you are following, so we can test and investigate the issue? Thanks

**Comment by hbtalha** [comment]
How/where eaxctly would I add the definition of __STDC_LIMIT_MACROS?

**Comment by hbtalha** [comment]
dghsedrfhgysfetdrhyset

**Comment by sergiohs84** [comment]
In VS2015, you can try to add the following to the `CMakeSetCompilerOptions.cmake` file:
add_definitions(-D__STDC_LIMIT_MACROS).

**Comment by sergiohs84** [comment]
Closing this ticket. If the issue needs further investigation, please, feel free to re-open it. Thanks

**Comment by hbtalha** [comment]
@sergiohs84, sorry for the late reply, school had me busy. 
I actually quit trying to get the example to compile in VS15, instead I am trying to learn how this SDK works to better my knowledge of c++ a little, and I am trying to use it in Codeblocks but don't know how to do it correctly.

I have opened another issue where I explain the details https://github.com/meganz/sdk/issues/1946
