### ISSUE TITLE
Bug: webdav server does not handle range requests HTTP/1.1 (RFC7233) compliant

### ISSUE THREAD

**Issue by khand100** [meganz/sdk#1600]
Hi,
I noticed that the webdav server is too strict while handling range requests with an end byte range exceeding the actual file size. According to [RFC 7233 - 2.1.  Byte Ranges
](https://tools.ietf.org/html/rfc7233#section-2.1) it should just reply with the rest of the file:

> If the last-byte-pos value is
   absent, or if the value is greater than or equal to the current
   length of the representation data, the byte range is interpreted as
   the remainder of the representation (i.e., the server replaces the
   value of last-byte-pos with a value that is one less than the current
   length of the selected representation).

But your implementation just responds with a 416 Range Not Satisfiable http code, which causes downloads to fail. I noticed this because the cdn I am using in front of the webdav server makes fixed byte range requests to improve the cache hit rate, but right now the last request often fails because the range exceeds the actual file size.

I also found the corresponding lines in the code in [megaapi_impl.cpp - MegaHTTPServer::streamNode](https://github.com/meganz/sdk/blob/develop/src/megaapi_impl.cpp#L27105). I have never worked with C++ before thus I do not think I can create a useful pull request but I think something like this should fix the issue:
```diff
diff --git a/src/megaapi_impl.cpp b/src/megaapi_impl.cpp
index 36907b4e..eac564ff 100644
--- a/src/megaapi_impl.cpp
+++ b/src/megaapi_impl.cpp
@@ -27134,17 +27134,16 @@ int MegaHTTPServer::streamNode(MegaHTTPContext *httpctx)
     {
         start = httpctx->rangeStart;
     }
-    httpctx->rangeStart = start;
 
-    if (httpctx->rangeEnd >= 0)
+    if (httpctx->rangeEnd >= 0 && httpctx->rangeEnd < totalSize)
     {
         end = httpctx->rangeEnd;
     }
-    httpctx->rangeEnd = end + 1;
-
-    bool rangeRequested = (httpctx->rangeEnd - httpctx->rangeStart) != totalSize;
 
     m_off_t len = end - start + 1;
+
+    bool rangeRequested = len != totalSize;
+
     if (totalSize && (start < 0 || start >= totalSize || end < 0 || end >= totalSize || len <= 0 || len > totalSize) )
     {
         response << "HTTP/1.1 416 Requested Range Not Satisfiable\r\n"
```

**Comment by polmr** [comment]
Sounds good to me. Thanks for taking your time to prepare this!
Some comments: the removal of the lines overriding rangeStart & rangeEnd is wrong I'm afraid. They will be used elsewhere and should contain the effective requested range.
With your changes, the `end >= totalSize` and `len > totalSize` checks should always be false. 

I believe simply changing `end = httpctx->rangeEnd;` to `end = std::min(totalSize - 1, httpctx->rangeEnd);` will produce the same result.

What's your client exactly (so that we can try it out)? 
In any case, before applying these changes, we should ensure that most common clients don't run into problems when receiving an smaller range than requested.

**Comment by khand100** [comment]
You are probably right about the overriding of rangeStart & rangeEnd. I thought these contain the original/unmodified values from the request header and they where only used to determine the value of `rangeRequested`. Therefor I wanted to simplify and especially remove this line `httpctx->rangeEnd = end + 1;` which seamed unnecessary confusing.

Yes `end >= totalSize` and `len > totalSize` would always be false, which is exactly the change we want :smile:  But I would not remove the checks in case future refactoring messed something up and we do not return garbage to clients.

Yes just your minimum variant change or my extended if clause `&& httpctx->rangeEnd < totalSize` achieve the intended behavior.

I am not using a webdav client. My setup is as following:
any webrowser -> BunnyCDN -> caddy (webserver/proxy) -> megacmd/webdav  
The origin of the problem is an option of BunnyCDN, which is intended to improve cache hit rates by rewriting all range requests to fixed ranges. Which apparently relies on a correct implementation of rfc7233. I used Postman to send handcrafted range requests to track down from where the 416 responses came. I also tested normal webservers which all just send the rest of the file.

So I am quite sure this change will not cause problems for other clients, because just sending the rest of the file is the defined behavior from the rfc and especially because we still send correct `Content-Length` and `Content-Range` headers. If the client is not respecting these it is a bad implementation and we should not care for it :man_shrugging:

**Comment by polmr** [comment]
Your client is `webrowser -> BunnyCDN -> caddy (webserver/proxy)` then :-) . 
I agree keeping the checks in place for the future and I'm pretty confident no client will fail with these changes, but should be checked just in case (we don't want to break widely used client). 
Herer's the PR that should fix it: https://github.com/meganz/sdk/pull/1611 . @khand100, I can have an installer for you to test if you are willing to. If so, please contact support@mega.nz, referencing this issue and indicate your OS.

**Comment by khand100** [comment]
Great, thanks for the quick fix. I would love to test it, I just send the mail.

**Comment by khand100** [comment]
@polmr I still got no response from the support, can you check whats going on there? The ticket number is #TQR-445-23668.
Or can you send me a debian installer via another way (upload it to mega for example :smile: )

**Comment by polmr** [comment]
Sure... which Debian?

**Comment by khand100** [comment]
Debian 10, thanks.

**Comment by polmr** [comment]
Here it is: https://mega.nz/#!YE5V0AiS!WaGhLbQOU-1KfYdvQ9GNH5_d3A5IqECoS1BLnpoI8Zo

SHA256 checksum:
```c998b8ddcf1f8eecf8aed38d1ed10ead6062f9d0c9be2f5c075f83b941a3d498```

**Comment by khand100** [comment]
Nice it fixed my 416 issues, thank you very much.
Can you estimate how long it will take until https://github.com/meganz/sdk/pull/1611 is merged?
