### ISSUE TITLE
How do I get a reference to MegaNode object by a public link of a folder?

### ISSUE THREAD

**Issue by lzzy12** [meganz/sdk#1631]
I'm trying to download files as well as folders provided it's public link using the API (the python binding to be more precise). I'm able to get the `MegaNode` object for files with the help of `MegaApi->getPublicNode(char * megaFileLink)` and then I call `MegaApi->startDownload()` method to start the download however, **I can't find any documentation for getting nodes for folders given it's public link**. Can you, please guide me in the right direction?

**Comment by lzzy12** [comment]
If possible please help @polmr

**Comment by mattw-mega** [comment]
I think you want to use this one to "login" into the public folder, then get its root node: `void loginToFolder(const char* megaFolderLink, MegaRequestListener *listener = NULL);`  cheers

**Comment by lzzy12** [comment]
I'll try. Thanks
