### ISSUE TITLE
megasymplesync in docker

### ISSUE THREAD

**Issue by MaxKh** [meganz/sdk#1660]
Hi

I'm trying to create a docker container with `megasimplesync`.
The base layer is `alpine:edge`, `mega sdk` version is v3.6.3
The Dockerfile: https://gist.github.com/MaxKh/ae9ce059899f34ed2bd09e6995a91a08

I use a host directory mounted to the container as a local folder for synchronization.
Remote file addition and deletion are handled properly. Local file addition too. But local file deletion is ignored. The following appears in logs:
`[debug] Self filesystem notification skipped`

**Comment by clunietp** [comment]
@MaxKh - Did you ever figure this one out?

**Comment by MaxKh** [comment]
@clunietp No. Also I noticed same errors during "normal" usage (without docker). I had to replace sync logic from **megasimplesync** to self-writted python client on top of official MEGA Python SDK

**Comment by clunietp** [comment]
That sounds interesting, do you have that published anywhere?  I suppose my alternative is to run the official client, bugs and all, in a heavier container

**Comment by MaxKh** [comment]
I have no plans to publish - the sync login is a part of my "private" telegram bot.
SDK examples are quite clear and provide good starting point.
https://github.com/meganz/sdk/tree/develop/examples/python

**Comment by clunietp** [comment]
I was not able to recreate this bug using Alpine and the 3.6.5 client; sync seems to be working fine with both local and remote additions/deletions.  I published my build in case this can be useful to anyone looking for a Alpine+megasync container

https://github.com/clunietp/docker-trickle-megasync

**Comment by sergiohs84** [comment]
The example `megasimplesync` become obsolete and it was removed in v5.1.1.
Closing this ticket because the above. Thanks
