### ISSUE TITLE
after set --enable-tests, the building will fail!

### ISSUE THREAD

**Issue by clockzhong** [meganz/sdk#1700]
I got the following errors with the latest source tree, after I enabled the --enable-tests as:
./configure --enable-python --enable-tests --with-gtest=/usr/local/lib/gtest

.....................
examples/megacli.cpp:2546:19: note: variable tracking size limit exceeded with -fvar-tracking-
assignments, retrying without
 autocomplete::ACN autocompleteSyntax()
                   ^
  CXXLD    examples/megacli
  CXX      examples/examples_megasimplesync-megasimplesync.o
  CXXLD    examples/megasimplesync
  CXX      examples/linux/examples_linux_megafuse-megafuse.o
  CXXLD    examples/linux/megafuse
  CXX      tests/unit/tests_test_unit-Commands_test.o
tests/unit/Commands_test.cpp: In member function ‘virtual void Commands_CommandGetRegisteredContacts_processResult_happyPath_Test::TestBody()’:
tests/unit/Commands_test.cpp:79:5: error: converting to ‘std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {const char (&)[15], const char (&)[3], const char (&)[15]}; <template-parameter-2-2> = void; _Elements = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]’
     };
     ^
tests/unit/Commands_test.cpp:79:5: error: converting to ‘std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {const char (&)[13], const char (&)[3], const char (&)[16]}; <template-parameter-2-2> = void; _Elements = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]’
tests/unit/Commands_test.cpp: In member function ‘virtual void Commands_CommandGetRegisteredContacts_processResult_onlyOneContact_Test::TestBody()’:
tests/unit/Commands_test.cpp:101:5: error: converting to ‘std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {const char (&)[15], const char (&)[3], const char (&)[15]}; <template-parameter-2-2> = void; _Elements = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]’
     };
     ^
tests/unit/Commands_test.cpp: In member function ‘virtual void Commands_CommandGetRegisteredContacts_processResult_extraFieldShouldBeIgnored_Test::TestBody()’:
tests/unit/Commands_test.cpp:123:5: error: converting to ‘std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {const char (&)[15], const char (&)[3], const char (&)[15]}; <template-parameter-2-2> = void; _Elements = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]’
     };
     ^
Makefile:2599: recipe for target 'tests/unit/tests_test_unit-Commands_test.o' failed
make[2]: *** [tests/unit/tests_test_unit-Commands_test.o] Error 1
make[2]: Leaving directory '~/sdk'
Makefile:2881: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '~/sdk'
Makefile:1371: recipe for target 'all' failed
make: *** [all] Error 2

It seems the Gtest is wrong with latest google test library after so long time.

**Comment by clockzhong** [comment]
Without the enable-tests, the building is OK after fixing the pull request: ["Fixed some bulding bugs in ubuntu #1699"](https://github.com/meganz/sdk/pull/1699)

**Comment by cb-mega** [comment]
Can you update to latest develop and try again? It should be fixed now. Thanks

**Comment by clockzhong** [comment]
@cb-mega I need test the source codes in master branch or develop branch? I found some differences between. 
Thanks!
Cock

**Comment by cb-mega** [comment]
develop contains the most recent changes.

**Comment by clockzhong** [comment]
Ok, I'll try develop branch latest version tonight at home, and will update the status here.

**Comment by sergiohs84** [comment]
Closing this ticket, since it's getting old. Please, feel free to re-open in case the issue requires further investigation. Thanks
