### ISSUE TITLE
set the modification date on a file

### ISSUE THREAD

**Issue by richardARPANET** [meganz/sdk#1708]
Does the sdk provide any way to set the "date added" on a file? Either as it's being uploaded or afterwards?

I need this to control the sorting of the files in the Mega.nz web interface to match the sorting on local disk.

![dateadded](https://user-images.githubusercontent.com/38049750/67904136-708bf580-fb65-11e9-9edf-6a5304cd7d17.png)

**Comment by sergiohs84** [comment]
Thank you for the question, @richardARPANET . The _Date added_ is a property of every uploaded file and it is set to the date the file was uploaded to MEGA. That behavior is required for several features in our cloud service, ie. MEGAsync, which relies on that date to decide whether the file is newer and has to be downloaded, or a local copy is newer and it has to be uploaded. In consequence, we do not plan to provide any way to set the "date added" by the user.

As a possible workaround, you can try sorting your files by the _Last modified_ date (modification timestamp), which probably fit your needs :) Please, see the screenshot below:
![image](https://user-images.githubusercontent.com/11694066/71086100-4506ae00-2199-11ea-9d14-b605d92af29a.png)

**Comment by richardARPANET** [comment]
:ok: thanks
