### ISSUE TITLE
Allow creation of anonymous account

### ISSUE THREAD

**Issue by eegh9Od2ahNg9aej** [meganz/sdk#1715]
Allow anonymous account (not tied to any email). Basically, allow for the creation of a public key from the client side generated private key and use that as an ID for Mega. Tying an account forcefully to an email is allowing a security risk factor if the email is compromised. This would be a an advanced registration feature for people who know what they are doing (being fully responsible for their credentials).
Ideally, for any of those already with an email tied account, to be able to disconnect it from their email and use the above method.

**Comment by sergiohs84** [comment]
Hi @eegh9Od2ahNg9aej. MEGA is proud of providing a service with privacy by default, but we do not plan to allow anonymous accounts in any way. Thanks
