### ISSUE TITLE
no module named _mega

### ISSUE THREAD

**Issue by artsiom-tsaryonau** [meganz/sdk#1778]
Hi!
I am trying to build `mega sdk` inside docker. My Dockerfile looks like this

	FROM alpine:3.7

	WORKDIR /home/tmp

	RUN apk add autoconf automake make g++ git \
				libtool curl-dev c-ares-dev zlib-dev sqlite-dev libsodium-dev swig \
				py2-pip python2-dev &&\
		apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
				crypto++-dev \
				libressl libressl-dev &&\
		apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
				freeimage-dev &&\
		pip install --upgrade pip && pip install wheel
		
	RUN git clone https://github.com/meganz/sdk.git &&\
		cd sdk && sh autogen.sh &&\
		./configure --disable-silent-rules --enable-python --disable-examples &&\
		make && make install

	RUN cd sdk/bindings/python && python setup.py bdist_wheel &&\
		pip install dist/megasdk-3.6.3-py2.py3-none-any.whl
		
I have created a sample `py` file that contains some kinda of demo application

    import mega 
    api = mega.MegaApi('test')
    print(dir(api))

However when I try to run it using `python demo.py` I get this error
```
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import mega
  File "/usr/lib/python2.7/site-packages/mega/__init__.py", line 2, in <module>
    from .mega import *
  File "/usr/lib/python2.7/site-packages/mega/mega.py", line 17, in <module>
    _mega = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/mega/mega.py", line 16, in swig_import_helper
    return importlib.import_module('_mega')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _mega
```
What is the problem? 

My additional question - is there a way to use Python3 instead of Python2.7 for scripts? Or it will work with any version?

**Comment by cb-mega** [comment]
Currently, in order to use the python bindings you'll either have to adjust the python path through `sys.path` (check out `test_libmega.py`) or through `PYTHONPATH` (pointing to bindings/python/.libs).

Python3 is currently not officially supported.
