### ISSUE TITLE
failed to compile win32 example on windows 10 using visual studio 2015

### ISSUE THREAD

**Issue by alonescarecrow** [meganz/sdk#1786]
hi
I'm using windows 10 and visual studio 2015. to begin working with meganz SDK I tried to compile it's win32 example named "testmega". I Followed instruction mentioned in README.md file and also used prebuilt 3rd-party libraries suggested by README file. but I got these errors on "chrono", "Ratio" and etc which I attached them as a text file.
see attachment for error logs.

[error_log.txt](https://github.com/meganz/sdk/files/3988565/error_log.txt)

**Comment by cb-mega** [comment]
The `testmega` project was updated today. If you pull the latest changes on the `develop` branch you should be able to build it. Please let us know if there are any further issues.
