### ISSUE TITLE
'curl/curl.h' file not found

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [meganz/sdk#180]
I'm trying to run the Swift example app. But I get the error **'curl/curl.h' file not found** in the `megasys.h` file (line no. 107).

How do I resolve this?

**Comment by jnavarrom** [comment]
Have you downloaded the prebuilt third party dependencies?

If you haven't downloaded the prebuilt third party dependencies, you can download a zip from https://mega.nz/#!QF02zQTL!rdyWnXtY3utfyuMdWCmpoR9CXHPGKQpf1afXQenk5vI
Then, you should uncompress the content and move include and lib to the directory sdk/bindings/ios/3rdparty
 
<img width="984" alt="screen shot 2015-11-16 at 13 40 08" src="https://cloud.githubusercontent.com/assets/3861964/11181935/028aad04-8c67-11e5-8eff-f4179b9ad041.png">

Please, update to the commit (f974498140e6bd163fa720f6a9781905df28b6f4) that correct some compilation errors related with Swift 2.0

**Comment by Isuru-Nanayakkara** [comment]
Ah no, I didn't do that. All good now. Thanks!
