### ISSUE TITLE
Fetching file attributes (API, megacli)

### ISSUE THREAD

**Issue by Sfinx** [meganz/sdk#185]
Is it possible to fetch the file attributes other than name (modification time, MAC's, etc.) using API or megacli ? Does the megacli getfa command is working ? So it will be good to have the setattr <type> <attr string> <file> command in megacli along with working getfa one. Thanks !

**Comment by sergiohs84** [comment]
You can use the `MegaApi` to retrieve file attributes and information about nodes, such as modification and creation time, display name or the preview in case of images/videos. Please, check the public interfaces of the class `MegaNode` in the documentation for further details.
At the same time, if you prefer to use the SDK directly, you can get/set attributes by using the commands `getfa` and `putfa` respectively from `megacli`.

**Comment by Sfinx** [comment]
Last time I've checked the getfa/putfa - they just do not work. Can you please confirm they are working simply checking the attributes of the just aploaded fule using megacli. Thanks !
