### ISSUE TITLE
Android X86_64

### ISSUE THREAD

**Issue by HereComesANewChallenger** [meganz/sdk#1867]
I tried to build Mega SDK  for Android X86_64.
I had a link error: "libcrypto.so: undefined reference to 'rc4_md5_enc' "
Did you already tried to generate an Android X86_64 library version ?
If, no, do you think this `rc4_md5_enc' function is really used by mega sdk ?

**Comment by sergiohs84** [comment]
Hi there
We actually do compile and use the library on Android x64 devices in our official app. Currently, we build the SDK and MEGAchat libraries by using the NDK r16 for x64 (r14 for x32). You might want to have a look to the Android repo: https://github.com/meganz/android The Readme.md contains information about the building system and the scripts used to semi-automatize the procedure.

As for the usage of the `rc4_md5_enc` function, I think it's not in use currently.
