### ISSUE TITLE
Missing libs for ios sdk 

### ISSUE THREAD

**Issue by zelin** [meganz/sdk#190]
I am having trouble using latest Demo and Mega workspace. I am getting errors for missing libs 

libcares.a
libcrypto.a
libcryptopp.a
libcurl.a
libssl.a

Where can i get these files or how can i compile them for Mega sdk. Infact is it possible to get Mega.framework?

**Comment by jnavarrom** [comment]
Have you downloaded the prebuilt third party dependencies?

If you haven't downloaded the prebuilt third party dependencies, you can download a zip from https://mega.nz/#!QF02zQTL!rdyWnXtY3utfyuMdWCmpoR9CXHPGKQpf1afXQenk5vI
Then, you should uncompress the content and move include and lib to the directory sdk/bindings/ios/3rdparty

If you want to build the third party dependencies by yourself: open a terminal in the directory sdk/bindings/ios/3rdparty. Run sh build-all.sh (Wait until the process ends, it will take some minutes ~20)

<img width="984" alt="screen shot 2015-11-16 at 13 40 08" src="https://cloud.githubusercontent.com/assets/3861964/11181935/028aad04-8c67-11e5-8eff-f4179b9ad041.png">
