### ISSUE TITLE
Failed to upload large number of files with sdk 3.4.4

### ISSUE THREAD

**Issue by chenxiao9** [meganz/sdk#1936]
OS: ubuntu server 16.04 
SDK version: 3.4.4
Application Language: Java 1.8
Recently, I wanted upload large numbers of files ; the total size of files maybe 4T. So I run an application to keep uploading files one by one which was builded by Java and Java binding sdk. But after uploaded hundreds of  GBtye, the upload function will always return error code -5.  But about 10 days ago, I  uploaded many files which size above 5T with the same application successfully.   I once changed the mega account, but the problems still  exists.

**Comment by kenkit** [comment]
What error do you get while uploading ?

**Comment by chenxiao9** [comment]
There is no extra error message. Just return error code -5. Now I restart application on time
