### ISSUE TITLE
Compiling With MinGW64

### ISSUE THREAD

**Issue by hbtalha** [meganz/sdk#1947]
I am building the sdk using mingw64, I have added all the packages required for windows.
 ./configure it stops with this error:

checking for WinHTTP... configure: error: WinHTTP.h header not found or not usable

I have tried downloading the header and copied to the 'include' folder but it is not working.

Any idea how to get this to work?

**Comment by mattw-mega** [comment]
For windows it's much easier to build with cmake and Visual Studio, I would recommend that, though we don't have instructions in the readme.md for that yet.  Please see the contrib/cmake folder for the CMakeLists.txt.

**Comment by hbtalha** [comment]
Could you give me the instructions to build with cmake and VS please so I can try that?

**Comment by mattw-mega** [comment]
We will be providing step by step instructions once we switch to building the official windows products that way.  In the meantime the scripts to build dependencies are in that folder, which you can examine, and generating visual studio projects with cmake is done in the normal way, you can easily look that up.  thanks

**Comment by hbtalha** [comment]
OK, I am a beginner in these as this is my first time build such libraries but I will be sure to check it out.

It would be cool if you guys made a video tutorial on how to build on windows and unix-like systems.

**Comment by sergiohs84** [comment]
Hi @hbtalha . The building system has been rewritten. This issue should be solved. Please, follow [steps here](https://github.com/meganz/sdk?tab=readme-ov-file#windows).
