### ISSUE TITLE
Cyrillic symbols

### ISSUE THREAD

**Issue by rsarov** [meganz/sdk#1966]
It  work with cyrillic? 
I use Windows Winapi functions WideCharToMultiByte(), but it not work. 
Example: 
`wchar_t* wc = L"Кирилица"; 
char* str = UTF8Encode(wc); 
api->createFolder(str, parent);
//Response listener == -11
`

**Comment by mattw-mega** [comment]
Do you have write permissions in the parent?   API_EACCESS = -11,              ///< Access denied.
Cyrillic should be no problem - the name is encrypted anyway along with all other attributes before being sent to the servers.

**Comment by rsarov** [comment]
If not cyrillic then all ok
