### ISSUE TITLE
Prebuilt third party dependencies for Win64 / Visual C++ ?

### ISSUE THREAD

**Issue by superflexible** [meganz/sdk#1969]
Hello,
there are prebuilt libraries for Win32 mentioned in the README.md in the examples folder (see below), but where can I get them for Win64? I am having a really hard time finding the correct libraries.

> ## How to run the projects
> 
> 1. Download the SDK or clone the SDK repository
> 2. Download the prebuilt third party dependencies from this link:
> https://mega.co.nz/#!VsNmABiQ!RKobitbqZbUt1sEdiyJ_jOG3IJlC1zJG-YP2TRxYFd8

**Comment by mattw-mega** [comment]
We have only released 32 bit apps to date on windows.  We will be releasing 64 bit MEGAsync shortly though.   To build the dependencies as 64 bit, see the scripts in /contrib/cmake which make it very easy.  thanks

**Comment by superflexible** [comment]
Hello,
thanks, I've got it working now.
