### ISSUE TITLE
EAGAIN: Request failed, retrying

### ISSUE THREAD

**Issue by superflexible** [meganz/sdk#1973]
Hello,
I am observing that legitimate HTTP requests by the SDK are frequently replied to by the servers with:
-3

This error code seems to mean EAGAIN: Request failed, retrying.

Can I do anything to avoid this error? Could it be due to application-specific limits regarding the number of HTTP requests? Does my application have to be approved to reach production status?

**Comment by superflexible** [comment]
Hello,
I found the cause - my app was using multiple MegaApi instances for separate threads, thus needing several logins. The servers apparently don't like that, and it's not very efficient really. I am now using only one MegaApi instance and it is working fine now.

**Comment by superflexible** [comment]
Hello,
I need to reopen this ticket. After one successful login attempt, if the user stops the job and disconnects, the next login attempt a few minutes later is blocked by the servers. Why? Should I log in only once per day?

**Comment by mattw-mega** [comment]
You should only log in once, until the user deliberately chooses to log out.    Each time you log in, a new session is created, and the number of open/recent sessions is limited.   Subsequent app starts should resume that session - that's much more efficient on your end also, because you can use previously downloaded and cached account state instead of getting it from the servers every time.

**Comment by superflexible** [comment]
OK, so what is necessary to save and resume the SDK state when the application terminates / is restarted?

Just save the session key?

And then use the following function the next time the app is started?
void fastLogin(const char* session, MegaRequestListener *listener = NULL);

**Comment by superflexible** [comment]
To answer my own question, yes this works beautifully.

**Comment by mattw-mega** [comment]
Yes that is correct - be sure to store that session key securely as it can be used to access the account without re-supplying the password (provided the session has not been cancelled)
