### ISSUE TITLE
Can't download prebuilt libraries, also missing x86-64 lib

### ISSUE THREAD

**Issue by acarlsen** [meganz/sdk#1976]
Prebuilt libraries link for Android here is dead:
https://github.com/meganz/sdk/blob/develop/examples/android/ExampleApp/README.md

Also please include x86-64 version of libmega.so - I have tried building libraries myself using guide but script fails at random places without meaningful error, usually unpacking/configuring some dependency and I don't really know enough about the build process used to debug it in any meaningful way. 

I have removed MEGA support in latest version of my app because I am unable to satisfy Google Play 64 bit library requirement if trying to include MEGA support.

**Comment by mrladeia** [comment]
I'm also having trouble building libmega.so

I'm having a problem when it comes to line 15 (``` CC=`${NDK_ROOT}/ndk-which gcc` ```) of build.sh nothing happens and the script closes because of `set -e` (line 2 in build.sh)

Line 15 does not execute the command and I was unable to identify the error.

(https://github.com/meganz/sdk/blob/develop/examples/android/ExampleApp/app/src/main/jni/build.sh#L15)

**Comment by Nelnitorian** [comment]
Same problem here.

**Comment by han9over** [comment]
Why isn't anyone responding to issues? Is this in active development?

**Comment by sergiohs84** [comment]
Apologies for the delay. We will sort it out in the coming weeks. Thanks for your patient.

PS: I hope it's not too late for you to restore the support to MEGA in your app, @acarlsen. Keep an eye on the issue ;)

**Comment by acarlsen** [comment]
I did manage to build the libraries in the end after lots of trial and error, but it would be very nice to just be able to import Mega SDK like a Maven library prepackaged with interop files and prebuilt binaries. That would it would be a one-liner in your build.gradle to import it and you wouldn't need to include a lot of files in your own project or build your own wrapper library...
