### ISSUE TITLE
mega file decryption with libsodium

### ISSUE THREAD

**Issue by IRGC** [meganz/sdk#1989]
this is not a issue but a question
what functions of libsodium mega sdk uses to decrypt the mega file?
in php i use  
`$cipher="AES-128-CTR";`
`openssl_decrypt($raw,$cipher, $key,OPENSSL_RAW_DATA|OPENSSL_ZERO_PADDING, $iv);`
i want to port to libsodium 

thanks.

**Comment by sergiohs84** [comment]
None of them. The `libsodium` primitives are used for elliptic keys, concretely for Ed25519 (for signing) and Cu25519 (for chat).
Files are encrypted using primitives from `libcrypto++`, concretely AES in ECB mode. For file attributes, such as previews/thumbnails, we use AES in CBC mode, same than for node attributes such as filename.
Hope it helps you.
