### ISSUE TITLE
detect package (arch, machine, hostinfo, etc)

### ISSUE THREAD

**Issue by latot** [meganz/sdk#202]
Hi again, well checking the config.log from https://github.com/meganz/sdk/issues/201 i found this:

```
hostname = 6e
uname -m = x86_64
uname -r = 4.3.3-hardened-r1
uname -s = Linux
uname -v = #1 SMP Tue Dec 22 14:15:15 CLT 2015

/usr/bin/uname -p = Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown
```

but some utilities are in my system, like arch, so checking the code in configure script file i found this:

```
/usr/bin/uname -p = `(/usr/bin/uname -p) 2>/dev/null || echo unknown`
/bin/uname -X     = `(/bin/uname -X) 2>/dev/null     || echo unknown`

/bin/arch              = `(/bin/arch) 2>/dev/null              || echo unknown`
/usr/bin/arch -k       = `(/usr/bin/arch -k) 2>/dev/null       || echo unknown`
/usr/convex/getsysinfo = `(/usr/convex/getsysinfo) 2>/dev/null || echo unknown`
/usr/bin/hostinfo      = `(/usr/bin/hostinfo) 2>/dev/null      || echo unknown`
/bin/machine           = `(/bin/machine) 2>/dev/null           || echo unknown`
/usr/bin/oslevel       = `(/usr/bin/oslevel) 2>/dev/null       || echo unknown`
/bin/universe          = `(/bin/universe) 2>/dev/null          || echo unknown`
```

i think call like this its a bad idea, because linux distros change the installation directory, so its posible change all rutes call to something like this? (maybe are more calls like this, up)

```
/usr/bin/arch -k       = `($(which arch) -k) 2>/dev/null       || echo unknown`
```

Cya.

**Comment by polmr** [comment]
Hi lalot,sorry for answering this issue so late.
These absolute paths in your configure scripts are generated by GNU build system Autotools. We do not write them manually. If you are interested in escalating your suggestion, here is the exact file which causes it to be written there: http://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=blob_plain;f=build-aux/config.guess;hb=refs/heads/master (link to master branch at autoconf project <http://git.savannah.gnu.org/gitweb/?p=autoconf.git>).
