### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by menjilx** [meganz/sdk#2044]
Do you offer or have a REST API?

Thank you

**Comment by sergiohs84** [comment]
I'm glad to announce, @menjilx , that we are already working on a REST API. However, it's not ready yet, and you will need to wait for a few months in order to test it in production.
Are you considering to integrate MEGA into any existing service?
Cheers

**Comment by menjilx** [comment]
> I'm glad to announce, @menjilx , that we are already working on a REST API. However, it's not ready yet, and you will need to wait for a few months in order to test it in production.
> Are you considering to integrate MEGA into any existing service?
> Cheers

Yes, I'm planning to add it on my service which is "Mirroring Links/Files".
