### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by erotavlas85** [meganz/sdk#206]
Hi,
I would like to know if you are planning to create a package for the famous and very useful packages manager for windows https://chocolatey.org/. It is used by many system administrators.
Thank you very much

**Comment by javiserrano** [comment]
Hi,
It is not in our immediate plans due to other priorities. However, it looks interesting. We will try to do it when other things with a higher priority are finished but I can't give you a deadline, it could take months.

If you have experience with Chocolatey and want to collaborate, we would be glad to review and accept a pull request adding support to this package manager.

**Comment by erotavlas85** [comment]
Hi,
ok thank you for your fast reply. At the moment I do not have free time to do it, maybe in the future. There are two guides in order to make a package: Automatic package https://github.com/chocolatey/choco/wiki/AutomaticPackages and standard package https://github.com/chocolatey/choco/wiki/CreatePackages.

**Comment by erotavlas85** [comment]
Hi,
does sync client for windows support silent installation?

**Comment by javiserrano** [comment]
The installer of the sync client (MEGAsync) is built using NSIS so this documentation should apply:
http://nsis.sourceforge.net/Docs/Chapter4.html#silent

Runnning the installer with `/S` it should silently install MEGAsync.
Despite it's not an officially supported feature, I have just tested it and it seems to work well.

**Comment by erotavlas85** [comment]
Yes, it worked at least on Windows 10. Now I would like to make a package, it seems not difficult according to this video https://www.youtube.com/watch?v=Wt_unjS_SUo. The problem is that I have only little free time and many projects to do.
Thank you

**Comment by trajano** [comment]
let me try it again.  I had issues when running it with `/S` in that nothing really happened.  It could be the way I was using, i'll put it on https://github.com/trajano/choco-packages and if it works out well maybe someone from `meganz` can take the code I wrote.

**Comment by trajano** [comment]
I actually opened one a while back in https://github.com/meganz/MEGAsync/issues/59

**Comment by trajano** [comment]
@javiserrano what is the command line you use?

**Comment by erotavlas85** [comment]
@trajano if you are interested about installing mega.nz sync client together with command line utility ([megatools](http://megatools.megous.com/)) that does not require username and password in order to download files from mega.nz cloud (as official mega.nz command line client), you can use this script https://gist.github.com/erotavlas85/f872919413c28360b66f
In detail, the following lines are enough:
`
$ScriptHome="$env:ProgramData"
# install chocolatey package manager
$ChocolateyPath="$ScriptHome\chocolatey"
if (-Not (Test-Path $ChocolateyPath))
{
	echo "Installing chocolatey packages manager"
	# default installation folder C:\ProgramData\Chocolatey note C:\Users\All Users\ and C:\ProgramData\ are the same
	iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
	refreshenv
	
	# necessary starting since chocolatey v0.10.0
	choco feature enable -n allowEmptyChecksums

	choco install -y 7zip	
}
# only for versions before windows 10
elseif ($OSMajorVersion -eq 6)
{
	echo "Updating powershell to latest version"
	choco install -y dotnet4.5.1
	choco install -y powershell
}
# install mega.nz services
cd $ScriptHome
# Note: megacmd requires user authentication while megatools does not
$MegaToolsVersion="1.9.98"
$MegaTools="$ScriptHome\megatools-$MegaToolsVersion-$WindowsVersion"
if(-Not (Test-Path $MegaTools))
{
	Import-Module Bitstransfer
	Start-BitsTransfer -source "https://megatools.megous.com/builds/megatools-$MegaToolsVersion-$WindowsVersion.zip"
	& "$ProgramsPath\7-Zip\7z.exe" x -y ".\megatools-$MegaToolsVersion-$WindowsVersion.zip"
	Remove-Item ".\megatools-$MegaToolsVersion-$WindowsVersion.zip"
	
	$MegaSync="https://mega.nz/MEGAsyncSetup.exe"
	Start-BitsTransfer -source $MegaSync
	Start-Process -FilePath ".\MEGAsyncSetup.exe" -ArgumentList "/S" -Wait	
	Remove-Item ".\MEGAsyncSetup.exe"
}
`

**Comment by trajano** [comment]
This part `Start-Process -FilePath ".\MEGAsyncSetup.exe" -ArgumentList "/S" -Wait	` does not seem to work for me from the command line itself.  What I did was ".\MegaSyncSetup.exe /S` but running that does not install MEGAsync.

**Comment by erotavlas85** [comment]
What is your windows and powershell version? I tested the script with windows 7, 10 and powershell 5.

**Comment by trajano** [comment]
Windows 10 14393.593
````
PS C:\Windows\system32> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  693
````

**Comment by trajano** [comment]
But I think you and I are trying to install different things, I was mainly after the MEGAsync client.  Where would you get the compiled MEGAcmd CLI commands from?

**Comment by trajano** [comment]
I think I figured out what went on... the `/S` seems to install to the current user's folder (which is the default).  I wonder if I can make it *All Users*

Also I would approach megacmd differently (because it's a CLI I would want the shims created)  I'll do that in a few minutes.

**Comment by trajano** [comment]
There seems to be a problem with 7zip that comes with Chocolatey vs the official 7zip.  Preventing a proper extraction of the files for megacmd.exe specifically megaclient.exe and uninst.exe.  Though I don't care much about unist.exe I think megaclient.exe is needed no?

**Comment by erotavlas85** [comment]
I confirm that megaclient sync work via S`tart-Process -FilePath ".\MEGAsyncSetup.exe" -ArgumentList "/S" -Wait	` moreover I use megatools cmd client since it does not require username and password to download files from my user account.
7zip with chocolatey works well the syntax is this `& "$ProgramsPath\7-Zip\7z.exe" x -y "\input file path"`
Please, read this [script](https://gist.githubusercontent.com/erotavlas85/391dc816d39701587e2a4aebc8e3f264/raw/c1ef5aa4df188a88163b37a7e658f8be746ed37c/Mega.nz%2520client%2520and%2520megatools%2520cmd%2520installer%2520via%2520chocolatey) it does all.

**Comment by trajano** [comment]
You're using a different 7zip, chocolatey itself comes with 7zip which will not extract the files correctly.

**Comment by erotavlas85** [comment]
The [package](https://chocolatey.org/packages/megasync) is working on chocolatey.
