### ISSUE TITLE
No example for downloading folders from public link for python binding

### ISSUE THREAD

**Issue by lzzy12** [meganz/sdk#2089]
Please add examples on how to download folders from public link, in your examples for using python binding

**Comment by sergiohs84** [comment]
After reviewing the situation of bindings and example for Python, it's been decided that we stop maintaining them.
In consequence, this ticket becomes obsolete and it will be closed.

As an alternative, @lzzy12 , it's suggested to use MEGAcmd. You can call any command from Python directly. I hope it works for you.

Kind regards,
Sergio
