### ISSUE TITLE
mega.dll for Windows 64 Bit (And Windows 10 issues)

### ISSUE THREAD

**Issue by burricios** [meganz/sdk#210]
Hi,
I'm trying to use the SDK to compile the java example program (I had to add the parameter -Djava.library.path="libs" so it could find the mega.dll library). However, the mega.dll is for 32bit, so I't wont work with 64Bit JVM. I tried using 32Bit JVM but I still get errors while trying to run the program, which you can see here:

Native code library failed to load.
java.lang.UnsatisfiedLinkError: C:\Users\Javi\Documents\Java Mega\sdk-master\sdk-master\examples\java\libs\mega.dll: Can't find dependent libraries
java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Javi\Documents\Java Mega\sdk-master\sdk-master\examples\java/libmega.so
java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Javi\Documents\Java Mega\sdk-master\sdk-master\examples\java/libs/libmegajava.so
java.lang.UnsatisfiedLinkError: C:\Users\Javi\Documents\Java Mega\sdk-master\sdk-master\examples\java\libs\mega.dll: Can't find dependent libraries

I really don't know what's happening here.

***WINDOWS 10 ISSUES
Also, any app with the mega sdk (I tried compiling the example C++ app with visual studio, and downloading megatools (an app created with the mega sdk)) wont work in windows 10. When executed from cmd, it will just get stuck without showing or doing anything.

Any help would be appreciated :)

**Comment by arauzl** [comment]
este problema ya lo solucione en windows 10. hay que copiar las dlls faltantes en syswow64. las dll faltan tes son : msvcp100d.dll y msvcr100d.dll. con eso ya corrio en windows 10
![mega](https://cloud.githubusercontent.com/assets/17056565/12802268/a604319e-cab0-11e5-9cd7-f7b476604897.png)

**Comment by burricios** [comment]
Gracias por la respuesta!

De todas formas, entiendo que esto no soluciona el problema de la compilacion en java, verdad? ¿Podrias explicarme cómo haces exactamente para compilar una aplicacion que utilice el SDK?
Gracias

**Comment by arauzl** [comment]
Con esto se resuelve el problema de las dependencias "Can't find dependent libraries". Una ves que solucione ese problema ya pude compilar y ejecutar la aplicacion de ejemplo en un proyecto de netbeans. Como mostre en la imagen del comentario anterior. Y por la misma razon no puedes compilar

**Comment by burricios** [comment]
Gracias, he ido a probarlo pero me he dado cuenta de que esos dll ya estaban en la carpeta syswow64, por lo que no parece que ese sea el problema.
Alguna otra idea?
Gracias

**Comment by javiserrano** [comment]
Hemos generado una nuevo paquete con nuestra biblioteca precompilada (junto con todas sus dependencias) para 32 y 64 bits.

Las podéis descargar aquí:
https://mega.nz/#!UtkgFZbS!v9aL5DpDyw5jmQljAx3Ns-wvjbYPOsQn-eQKZMx3qqE

Hemos actualizado también las instrucciones para que podáis construir vuestra propio `mega.dll` y los ejemplos, incluyendo versiones precompiladas de `mega.dll` y todas sus dependencias (para 32 y 64 bits) para que sea más sencillo:
https://github.com/meganz/sdk/blob/master/bindings/java/contrib/vs2010
https://github.com/meganz/sdk/tree/master/examples/java

La versión anterior de `mega.dll` era de depuración y dependía de los archivos `msvcp100d.dll` y `msvcr100d.dll`. La nueva versión es de release, por lo que no es completamente necesario tener instalado Visual Studio 2010. Sólo los _Redistributable Packages_:
http://download.microsoft.com/download/C/6/D/C6D0FD4E-9E53-4897-9B91-836EBA2AACD3/vcredist_x86.exe (32 bits)
http://download.microsoft.com/download/A/8/0/A80747C3-41BD-45DF-B505-E9710D2744E0/vcredist_x64.exe (64 bits)

Tened en cuenta que esta versión de `mega.dll` también depende de otras DLLs, que están también incluídas en el mismo paquete (cURL, c-ares, OpenSSL, FreeImage,...). En la versión anterior estaban enlazadas estáticamente o no eran necesarias (hemos empezado recientemente a usar cURL en vez de WinHTTP por defecto para resolver algunos problemas de conectividad). Es posible que necesitéis añadir la carpeta que contiene esas DLLs a vuestra variable de entorno `PATH` para que la máquina virtual de Java pueda encontrarlas (está comentado en los archivos README).

Espero que esta actualización resuelva los problemas que estábais teniendo.
