### ISSUE TITLE
Error: invalid option: --with-openssl

### ISSUE THREAD

**Issue by fairsayan** [meganz/sdk#2182]
When I try to run the command
`brew install --with-openssl curl` required in https://github.com/meganz/sdk/blob/develop/doc/OSX.txt at line 10, I get this error:
`Error: invalid option: --with-openssl`

Running on OSX version 10.15.6 (Catalina)

**Comment by fairsayan** [comment]
I tried using `sudo port install libcryptopp` with proper configuration path (by default with MacPorts files are in /opt/local/include/cryptopp).
it finds the headers, but it fails anyway:
`
checking for libcryptopp... checking cryptopp/cryptlib.h usability... yes
checking cryptopp/cryptlib.h presence... yes
checking for cryptopp/cryptlib.h... yes
checking for main in -lcryptopp... no
`

**Comment by sergiohs84** [comment]
The building system is now based on CMake and VCPKG. It should solve this issue. Otherwise, feel free to reopen it.
Thanks for reporting.
