### ISSUE TITLE
login error with sdk 3.4.4

### ISSUE THREAD

**Issue by chenxiao9** [meganz/sdk#2241]
OS: ubuntu server 16.04
SDK version: 3.4.4
Application Language: Java 1.8

Application would get errorCode：-3 when create new api and login after running a period of time .  When error occurs,  the subsquent api will login with error：-3. Restart application will work , but why?
The error log like：
ERROR MegaApiWrapper -Login error:Request failed, retrying
ERROR MegaApiWrapper -Login error:Access denied

**Comment by mattw-mega** [comment]
Probably you are leaving too many sessions open, or logging in too frequently - ideally every login should have a matching logout.   And once logged in, you can resume your app with fastLogin() which resumes your last session, instead of making a new login (which makes a new session)
