### ISSUE TITLE
Error compiling on mingw

### ISSUE THREAD

**Issue by shinchiro** [meganz/sdk#2316]
Hello, starting from release 3.7.5, I'm no longer can compile successfully on mingw.
http://0x0.st/ikbN.log

The errors come from these two functions:

https://github.com/meganz/sdk/blob/4d23b33ffdff3ec108d8471369df1932415eea29/src/win32/fs.cpp#L1668

https://github.com/meganz/sdk/blob/4d23b33ffdff3ec108d8471369df1932415eea29/src/win32/fs.cpp#L1680

**Comment by sergiohs84** [comment]
It seems the problem is not reproducible on our side. Also, the building system has evolved since the issue was reported.
If you still experience issues building on Windows, please, let us know. Thanks
