### ISSUE TITLE
Building the megasdk dll on Windows

### ISSUE THREAD

**Issue by demdante** [meganz/sdk#2325]
I have been having a difficult time building the mega sdk as a dll on windows.  Using the method detailed on the main page under the Windows section (involves using vcpkg to download and install all dependency libraries), I have been able to generate the static library (Mega.lib), but I am trying to build the MegaSDK into a dll file as described in the comments of the Makefile.win32.  Is there a way for me to create the Mega.dll using the vcpkg method, as I have tried for many days to use Cygwin to configure and compile the mega sdk using the Makefile.win32, but I have not been able to get it to work....  Any help would be awesome.  Or, better yet, does anyone just have an already compiled mega sdk dll file that they can share?  That would be awesome.

**Comment by sergiohs84** [comment]
Please, try again with an updated version of the SDK. We revisited the whole building system for all platforms.
If you still find issues, feel free to open a new ticket. Thanks

PS: note you might be interested on [this other thread](https://github.com/meganz/sdk/issues/2689).
