### ISSUE TITLE
question, megacli sync corrupted files

### ISSUE THREAD

**Issue by latot** [meganz/sdk#233]
Hi, well i don't know if its right ask here...

the example "megacli" when we sync some folder with a remote folder, the files are checked?

like, i have the b file locally, then i upload it but then then internet connection is lost, when i sync, its checked the remote b is corrupted?

Thx.

**Comment by javiserrano** [comment]
Yes, a fingerprint of files is created before they are uploaded. At the end of the upload, the fingerprint is checked again before attaching the file to the account. That way, we ensure that the file wasn't modified during the transfer. That fingerprint is also checked at the end of downloads.

Additionally, there is another integrity check related to the encryption/decryption. For each chunk of data, a HMAC is created during uploads and verified during downloads. Also, there is a 64 bit meta-MAC of all chunk HMACs that ensures the integrity of the whole file.

It's recommended to use our official apps, or applications based on our SDK to ensure that these checks are properly implemented and prevent the upload / download of corrupted files.

**Comment by latot** [comment]
Hi, thx for answering, little question, the examples in the sdk are considerer officials?

Thx.

**Comment by javiserrano** [comment]
Yes, of course :-)
