### ISSUE TITLE
Access violation (e.g., trying to write to a read-only share)

### ISSUE THREAD

**Issue by bim-g** [meganz/sdk#2336]
I am trying to upload a file in an existing folder but it return this error "Access violation (e.g., trying to write to a read-only share)",
i'm stuck and i dont know how to resolv. 
i tried all procedure but nothing work.

**Comment by sergiohs84** [comment]
Hi @bim-g 
How do you try to upload the file? can you share some extra information? That error is not returned by the SDK in any way :confused: 
Thanks

**Comment by bim-g** [comment]
it has been solved, the problem was when tried to upload multiple file at once.
