### ISSUE TITLE
megafuse isn't working on Linux

### ISSUE THREAD

**Issue by xdb64** [meganz/sdk#2348]
I have followed the instructions and got to the point where I have the megafuse executable. I ran it, entered the credentials, however nothing happens - when I go to the mountpoint, it's empty.

**Comment by tdparsenal** [comment]
Hi,
I encountered the same situation on Linux. The result of megafuse
~/workingspace/megaio/sdk/examples/linux ⌚ 15:26:26
$ ./megafuse 
MEGA email: tdparsenal@gmail.com
MEGA password (won't be shown): 
Local mountpoint: /home/phtran/phong
MEGA mountpoint (default /): /abc
megafuse: src/megaclient.cpp:5394: bool mega::MegaClient::CacheableStatusMap::addOrUpdate(int64_t, int64_t): Assertion `mClient->statusTable && "Updating status without status table"' failed.
[1]    63984 abort (core dumped)  ./megafuse

Anyone can suggest a solution to fix that ?

**Comment by kenkit** [comment]
I'm on windows C++ btw might related https://github.com/meganz/sdk/issues/2584

**Comment by sergiohs84** [comment]
The example `megafuse` is not anymore part of the repository.
