### ISSUE TITLE
Megasync can't find MegaApi::resumeSync function

### ISSUE THREAD

**Issue by Vascom** [meganz/sdk#2386]
Why removed function MegaApi::resumeSync from SDK?
Megasync still use it and can't be compiled with new SDK.

Should I use sdk 3.7.4 and not should use sdk 3.7.5 and higher?

**Comment by sergiohs84** [comment]
Hi @Vascom.

We have improved the codebase and all the sync management is not anymore something that the app copes with.
Instead, from v3.7.3, the SDK manages syncs internally, including persistence, and takes care of resuming them at the right moment.

May I ask you whether you have a modified version of MEGAsync? or you have your own client which calls `MegaApi::resumeSync()`???

Thanks

**Comment by Vascom** [comment]
I build megasync for rpmfusion repository.

**Comment by sergiohs84** [comment]
Oh, so you build MEGAsync for Linux. Awesome!
Then, I suggest to keep an eye to the upcoming v4.5.0 [here](https://github.com/meganz/MEGAsync/releases). Once it's ready and live, we will publish the new version, and then your package for rpmfusion repository will work again ;)
Thanks for your patience.

**Comment by Vascom** [comment]
It work now. But with specific version of SDK, not with latest as i thought before.
