### ISSUE TITLE
Build failure on Raspberry Pi 4 without including libatomic

### ISSUE THREAD

**Issue by thurask** [meganz/sdk#2472]
Since https://github.com/meganz/MEGAcmd/issues/451 also applies to MEGA SDK, rebroadcasting the issue for visibility. To summarize, building MEGAcmd git master on Raspberry Pi 4 running Raspbian 10 fails (``undefined reference to `__atomic_load_8'``) without including libatomic in both MEGAcmd and MEGA SDK, which can be accomplished by adding an autoconf step to both projects to check if libatomic is needed.

**Comment by developerbedoya** [comment]
I set the environment variable `LDFLAGS` when running `./configure`. That solved the problem in my Raspberry Pi 3, using Raspbian Buster:

`LDFLAGS="-latomic" ./configure`
