### ISSUE TITLE
Google Play warning: You are using a vulnerable version of OpenSSL

### ISSUE THREAD

**Issue by cgollner** [meganz/sdk#252]
Hi all,

today I got a warning email from Google saying:

> Please migrate your app(s) to OpenSSL 1.02f/1.01r or higher as soon as possible and increment the version number of the upgraded APK. Beginning July 11, 2016, Google Play will block publishing of any new apps or updates that use older versions of OpenSSL. If you’re using a 3rd party library that bundles OpenSSL, you’ll need to upgrade it to a version that bundles OpenSSL 1.02f/1.01r or higher.
> 
> The vulnerabilities were addressed in OpenSSL 1.02f/1.01r. 

Seems like the MEGA SDK is still using OpenSSL 1.0.1j.

Cheers

**Comment by sergiohs84** [comment]
We've updated the Android examples to use OpenSSL 1.0.1s instead.
Thank you for reporting, @cgollner
