### ISSUE TITLE
Java SwingExample failed to compile

### ISSUE THREAD

**Issue by gcclinux** [meganz/sdk#254]
Followed instructions and failed to compile in javac, I imported the file in Eclipse and also failed to find the required libraries, can you please advise?

Many Thanks

ricardo@latitude-e6530:~/apps/mega-sdk/sdk$ javac -d bin -sourcepath src/ src/nz/mega/bindingsample/SwingExample.java
src/nz/mega/bindingsample/SwingExample.java:42: error: package nz.mega.sdk does not exist
import nz.mega.sdk.MegaApiJava;
                  ^
src/nz/mega/bindingsample/SwingExample.java:43: error: package nz.mega.sdk does not exist
import nz.mega.sdk.MegaApiSwing;
                  ^
src/nz/mega/bindingsample/SwingExample.java:44: error: package nz.mega.sdk does not exist
import nz.mega.sdk.MegaError;
                  ^
src/nz/mega/bindingsample/SwingExample.java:45: error: package nz.mega.sdk does not exist
import nz.mega.sdk.MegaLoggerInterface;
                  ^
src/nz/mega/bindingsample/SwingExample.java:46: error: package nz.mega.sdk does not exist
import nz.mega.sdk.MegaNode;
                  ^
src/nz/mega/bindingsample/SwingExample.java:47: error: package nz.mega.sdk does not exist
import nz.mega.sdk.MegaRequest;
                  ^
src/nz/mega/bindingsample/SwingExample.java:48: error: package nz.mega.sdk does not exist
import nz.mega.sdk.MegaRequestListenerInterface;
                  ^

**Comment by javiserrano** [comment]
Hi!

Those missing files are generated in `bindings/java/` when the SDK is build with `--enable-java`.
Please, copy or link those files in your `src` folder (keeping the `nz/mega/sdk`) path and `javac` should be able to find them.

Those steps are commented in the instructions of the example:
https://github.com/meganz/sdk/blob/master/examples/java/README.md

We will review them to check if they are confusing or are wrong.
