### ISSUE TITLE
3rdParty building: Failed to download automake1.15-1.15.1-1-any.pkg.tar.xz  

### ISSUE THREAD

**Issue by vlad-mal** [meganz/sdk#2574]
When building 3rdParty Libraries (..\..\sdk\contrib\cmake\build3rdparty.cmd -o x86-windows-mega) , the error is:

-- Extracting source D:/Cpp/Lib/mega/3rdParty/vcpkg/downloads/icu4c-61_1-src.tgz
-- Applying patch D:/Cpp/Lib/mega/3rdParty/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch D:/Cpp/Lib/mega/3rdParty/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch D:/Cpp/Lib/mega/3rdParty/vcpkg/ports/icu/fix_parallel_build_on_windows.patch
-- Using source at D:/Cpp/Lib/mega/3rdParty/vcpkg/buildtrees/icu/src/c-61_1-src-b2757af884.clean
-- Downloading https://repo.msys2.org/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 6;"Couldn't resolve host name"
-- Downloading https://mirror.selfnet.de/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirror.selfnet.de/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:90 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:128 (msys_package_download)
  scripts/cmake/vcpkg_acquire_msys.cmake:288 (msys_package)
  ports/icu/portfile.cmake:85 (vcpkg_acquire_msys)
  scripts/ports.cmake:142 (include)

**Comment by sergiohs84** [comment]
This issue should have been solved already. We re-written the whole building system based on cmake for all platforms.
