### ISSUE TITLE
OAuth authorization support

### ISSUE THREAD

**Issue by vintikzzz** [meganz/sdk#2575]
Hi!

I am developing some project and I want to allow users to upload their content to Mega.nz. In this case I don't want users to share their mega.nz credentials with me (login/pass), it's not secure. Google drive have this feature already and it looks really convenient ([see example](https://developers.google.com/drive/api/v3/quickstart/nodejs)).

**Comment by Yrlish** [comment]
I'm also interested in this, I want to use tools and authenticate them with OAuth2. It will be better and more convenient than username/password. I also have 2FA, which makes current solutions unusable more or less.

**Comment by tuokri** [comment]
This would be incredibly helpful. Asking users to input their mega credentials to my third party service is not ideal.

**Comment by Yrlish** [comment]
I still can't believe this isn't available yet. It's ridiculous.

**Comment by lucasschirm** [comment]
Just to add to the list. That would be helpful for me aswell

**Comment by sergiohs84** [comment]
Thanks for the suggestions.

The End to End Encryption provided by MEGA relies on your password to authenticate, but the password is also used to decrypt the master key of your account. In consequence, even with an Open Authentication system in place, you would still the password to decrypt the data.

Nevertheless, we could implement a different mechanism. We will study this proposal.

**Comment by owenkellogg** [comment]
Thank you for your attention, this will be extremely useful in whichever form you take @sergiohs84 .
