### ISSUE TITLE
Build without libsodium fails

### ISSUE THREAD

**Issue by lemourin** [meganz/sdk#2578]
The README says libsodium is an optional dependency. The sodium headers are unconditionally included by the mega sdk though [1].

[1]: https://github.com/meganz/sdk/blob/master/include/mega/types.h#L74

**Comment by Gery82** [comment]
> The README says libsodium is an optional dependency. The sodium headers are unconditionally included by the mega sdk though [1].
> 
> [1]: https://github.com/meganz/sdk/blob/master/include/mega/types.h#L74

**Comment by sergiohs84** [comment]
Libsodium is indeed a mandatory dependency, required for the cryptography using elliptic keys.
