### ISSUE TITLE
Support of importing shared folder link

### ISSUE THREAD

**Issue by daniel0076** [meganz/sdk#2579]
Hi MEGA developers,

After reading through the code and the examples, I found MEGA SDK currently only supports importing a shared file but not a folder.
Is there (or will be) an API to import a shared folder link ?

Or is there any way to accomplish this with existing SDK APIs.

Thank you very much.

**Comment by sergiohs84** [comment]
Hi @daniel0076. First of all, apologies for the late reply. If you are still interested on importing a folder link to your account, you'll need to use 2 instances of `MegaApi`. One of the as usual, logged-in into your account, plus another one to fetch all the data from the folder link (see `loginToFolder()`). Once the additional instance retrieved all data (note the successful login should be follow with a call to `fetchnodes()`), you can call `authorizeNode()` to get a `MegaNode` than you can import into your account by calling `copyNode()`.
