### ISSUE TITLE
ffmpeg support might be outdated

### ISSUE THREAD

**Issue by DarkFighterLuke** [meganz/sdk#2580]
When trying to compile I get this:
`src/gfx/freeimage.cpp:258:18: error: ‘AVStream’ {aka ‘struct AVStream’} has no member named ‘skip_to_keyframe’`

I think it could be a version mismatch.

I am using Arch Linux and building the SDK with autotools.
On Ubuntu 20.10 this issue doesn't appear.

**Comment by DarkFighterLuke** [comment]
Found a duplicate #2576 .

**Comment by sergiohs84** [comment]
This ticket is outdated. Please, see [this comment](https://github.com/meganz/sdk/issues/2635#issuecomment-2508332251).
