### ISSUE TITLE
MegaCli crash

### ISSUE THREAD

**Issue by tdparsenal** [meganz/sdk#2584]
Hi Authors,
I am testing Mega SDK with python bindings. However it crashed with following error

$ python megacli.py 
Mega sample app. Type help or ? to list commands.

(Cmd) ?

Documented commands (type help <topic>):
========================================
cd    export  help    login   ls     mount  passwd  pwd   rm    
exit  get     import  logout  mkdir  mv     put     quit  whoami

(Cmd) login
Usage: login email password
(Cmd) login tdparsenal@gmail.com xxxxxxxxxxxx
(Cmd) INFO	2021-08-01 15:46:01,821 Request start (LOGIN)
INFO	2021-08-01 15:46:03,448 Request finished (LOGIN); Result: No error
INFO	2021-08-01 15:46:03,448 Request start (FETCH_NODES)
python: src/megaclient.cpp:5394: bool mega::MegaClient::CacheableStatusMap::addOrUpdate(int64_t, int64_t): Assertion `mClient->statusTable && "Updating status without status table"' failed.
[1]    73854 abort (core dumped)  python megacli.py

It also happened with C++ native : megafuse, I have no idea on how statusTable should be initialized. Can you please check ?

**Comment by kenkit** [comment]
Happened to me on C++ sdk when login in too

**Comment by kenkit** [comment]
> > @sergiohs84 are they created when you initialize megaapi object or when you initiate login request ?
> 
> They are created when you start a new session -> login + fetchnodes :)

Will investigate with a debugger and find what is going on when I'm free, maybe I missed some compile flags when building ?

**Comment by sergiohs84** [comment]
Closing this ticket as stale. Please, re-open if you still experience the issue. Thanks

**Comment by zenden2k** [comment]
The problem still exists in debug builds if you pass nullptr as `basePath` in MegaApi constructor.

**Comment by sergiohs84** [comment]
Hi @zenden2k. The SDK doesn't allow to pass nullptr as `basePath` any longer. It does require to have a local cache, since nodes of your cloud are kept in cache and only loaded from DB into RAM when needed.
We need to update the documentation: delete the following line
```
         * If you pass NULL to this parameter, the SDK won't use any local cache.
````
