### ISSUE TITLE
Freeing MegaApi class instance takes a long time and 100% CPU

### ISSUE THREAD

**Issue by superflexible** [meganz/sdk#2586]
Hello,
it seems that a simple
delete myMegaAPI;
takes a long time to free the nodes, is there any way to speed this up? Can I clear the nodes list prior to deleting the class instance?

**Comment by superflexible** [comment]
Apparently it's due to the C++ library's iterator debugging features, because I am using the DEBUG build. Will try switching to RELEASE.

**Comment by mattw-mega** [comment]
Yes it is (in the VS c++ lib) - release will run fast, or you can turn that off with the x64-windows-mega-staticdev triplet (you have to rebuild 3rd party libraries too)

**Comment by superflexible** [comment]
Hi, yes release is much faster, thanks.
