### ISSUE TITLE
### Current behavior

### ISSUE THREAD

**Issue by Scarlethrose1** [meganz/sdk#2590]
### Current behavior

We intercept every request call that goes out of cypress to add an AUTH header to every request. When the header is not attached we get network requests that fail. Before when using Cypress 6.8, all requests were intercepted even between tests (`it`). Now that is not the case anymore. This causes our tests to flake very frequently.

### Desired behavior

Intercept all requests! 

### Test code to reproduce

You can reproduce the errors pretty consistently with the repo: https://github.com/giacaglia/cypress-test-tiny

You need to run both the frontend and the backend to test it out. 

### Cypress Version

8.3.1

__Originally posted by @giacaglia in https://github.com/cypress-io/cypress/issues/18063__

**Comment by sergiohs84** [comment]
Not relevant for MEGA SDK repository, but Cypress. Closing this ticket.
