### ISSUE TITLE
MegaApiClient

### ISSUE THREAD

**Issue by Bluekey21** [meganz/sdk#2595]
We have an aplication in VB.NET where we use the API “MegaApiCliente”  for uploading files, but since the last september 30, the app hasn’t work as usual, it means, isn’t uploading files to our account of Mega.

The code line is as follows:

Dim Cliente As New MegaApiClient()
Cliente.Login("micorreo.com", "mypassword")

            Dim Nodos = Cliente.GetNodes()
            Dim Root As INode
            Dim Carpeta As INode

            If CarpetaNube <> "" Then
                Dim ExisteCarpeta As Boolean = Cliente.GetNodes().Any(Function(n) n.Name = CarpetaNube)

                If ExisteCarpeta = True Then
                    Carpeta = Nodos.[Single](Function(n) n.Name = CarpetaNube)
                Else
                    Root = Nodos.[Single](Function(n) n.Type = NodeType.Root)

                    Carpeta = Cliente.CreateFolder(CarpetaNube, Root)
                End If
            Else
                Carpeta = Nodos.[Single](Function(n) n.Type = NodeType.Root)
            End If

            Dim Archivo As INode = Cliente.UploadFile(RutaArchivo, Carpeta)

            Dim DownloadUrl As Uri = Cliente.GetDownloadLink(Archivo)

            UrlDescarga = DownloadUrl.ToString

            Cliente.Logout()

The app it seems uploading files but there isn’t any messange error, our project was updated with the 1.9.0.0 API’s versión. So, one question, do we have to send any extra to our API?.

Please we will wait for your support, could you please send us any documentation?

And it still hangs, Where as same credentials works well to login in browser

Thank you in advance and best regards.

**Comment by sergiohs84** [comment]
Is the `MegaApi::login()` returning any error? maybe you have enabled the 2FA and the authentication code is required, or there's another error. Please, can you provide logs from SDK? for further inspection by our devs. Thanks

**Comment by sergiohs84** [comment]
Closing this ticket, since there's no response and we cannot reproduce it.
In case you still observe the issue, please, feel free to re-open it and provide logs from the SDK to analyze the root of the issue.
Thanks
