### ISSUE TITLE
MegaApi::httpServer* methods not available in Python?

### ISSUE THREAD

**Issue by Eboreg** [meganz/sdk#2608]
Hi,

Is there any way to make the httpServer* methods (httpServerStart(), httpServerAddListener(), etc) available in the Python bindings? I tried `./configure --enable-python --with-libuv` and `--with` all kinds of stuff, but to no avail.

To be exact, this is my latest attempt:

```
./autogen.sh
./configure --enable-python --disable-silent-rules --disable-curl-checks --with-openssl --with-cryptopp --with-sodium --with-zlib --with-sqlite --with-cares --with-curl --with-freeimage --with-libuv --disable-examples --with-libzen --with-libmediainfo
make
cd bindings/python
python setup.py bdist_wheel --plat-name linux_x86_64
```

It all builds and seems to work OK, except the httpServer* methods just aren't there:

```
In [8]: api
Out[8]: <resources.lib.mega.mega.MegaApi; proxy of <Swig Object of type 'mega::MegaApi *' at 0x7ffad6f11c60> >

In [9]: api.httpServerStart()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [9], in <module>
----> 1 api.httpServerStart()

AttributeError: 'MegaApi' object has no attribute 'httpServerStart'

In [10]: [m for m in api.__dir__() if "http" in m.lower()]
Out[10]: ['useHttpsOnly', 'usingHttpsOnly']
```

OS: Ubuntu 20.04.03
Python: 3.8.10

**Comment by sergiohs84** [comment]
Hi Robert. We are not using `autotools` anymore, but CMake. Would you mind to give it a try again in order to confirm that the issue is still there?

Thanks in advance.

**Comment by sergiohs84** [comment]
After reviewing the situation of bindings and example for Python, it's been decided that we stop maintaining them.
In consequence, this ticket becomes obsolete and it will be closed.

As an alternative, @Eboreg , it's suggested to use MEGAcmd. You can call any command from Python directly. I hope it works for you.

Kind regards,
Sergio
