### ISSUE TITLE
Python Bindings distutils depricated

### ISSUE THREAD

**Issue by AnotherSamWithADream** [meganz/sdk#2619]
When building the python bindings after running:
`./configure --disable-silent-rules --enable-python --disable-examples`
I get this error:
`configure: error: cannot import Python module "distutils".
Please check your Python installation. The error was:
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives`
According to the error you should be using setuptools not distutils.
I do not do any C based languages (C, C++, C#) so I wont be able to make the changes.

**Comment by jorgeajimenezl** [comment]
If you have setuptools installed, use this variable `export PYTHONWARNINGS="ignore"`

**Comment by missemily2022** [comment]
@jorgeajimenezl Can you explain a little more?

**Comment by jorgeajimenezl** [comment]
@missemily2022  Even if you have setuptools installed, the `configure.sh`, what it does is to check that running `python -c "import distutils"` does not generate output. In recent versions of `distutils`, this generates a warning, so it does not pass the test, however, using `PYTHONWARNINGS="ignore"`, the interpreter will not generate warnings and should pass the configuration tests.

**Comment by EmilyMirror** [comment]
@jorgeajimenezl Thanks for the Answer.I now need to somehow implement it in GitHub Actions

**Comment by jorgeajimenezl** [comment]
> @jorgeajimenezl Thanks for the Answer.I now need to somehow implement it in GitHub Actions 

Well, u can just create a shell script (that export the en variable) that u execute on GitHub Actions

**Comment by missemily2022** [comment]
@jorgeajimenezl Thanks I figured ou the solution

**Comment by sergiohs84** [comment]
Thanks for reporting.

The building system has been rewritten and now Python bindings are generated via CMake. `distutils` is not used anymore, so this issue becomes obsolete.

Nevertheless, when generating the python packages using the bindings this warning is shown:
`.local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************!! `
We have created a ticket to update the `setup.py`.

**Comment by sergiohs84** [comment]
After reviewing the situation of bindings and example for Python, it's been decided that we stop maintaining them.
In consequence, this ticket becomes obsolete and it will be closed.

As an alternative, @jorgeajimenezl, if you are still interested on accessing to MEGA from Python, we suggest to use MEGAcmd. You can call any command from Python directly. I hope it works for you.

Kind regards,
Sergio

**Comment by rjriajul** [comment]
@sergiohs84 I know it's been a while since you mentioned that Python bindings are no longer supported and recommended MEGAcmd instead.

Since some time has passed, I just wanted to check in—is there any chance you might bring Python bindings back, or would you consider letting the community take over the code? Direct Python support is still really helpful for many of us.

Thanks for your hard work on the project.

**Comment by sergiohs84** [comment]
Hi @rjriajul 

I don't work for MEGA anymore. You'd better ask @ortmann

Cheers
