### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AmirulAndalib** [meganz/sdk#2622]
https://github.com/AmirulAndalib/MLTB-ALPINE-DEV/runs/7413333016?check_suite_focus=true#step:6:1123

---
#8 184.6 In file included from /usr/include/openssl/bio.h:20,
#8 184.6                  from /usr/include/openssl/ssl.h:18,
#8 184.6                  from ./include/mega/posix/meganet.h:28,
#8 184.6                  from ./include/mega.h:74,
#8 184.6                  from src/posix/net.cpp:22:
#8 184.6 src/posix/net.cpp: In constructor 'mega::CurlHttpIO::CurlHttpIO()':
#8 184.6 src/posix/net.cpp:272:10: error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization [-fpermissive]
#8 184.6   272 |     if (!CRYPTO_get_locking_callback()
#8 184.6       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
#8 184.6 src/posix/net.cpp:274:13: error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization [-fpermissive]
#8 184.6   274 |         && !CRYPTO_THREADID_get_callback())
#8 184.6       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
#8 185.1 make[2]: *** [Makefile:2767: src/posix/libmega_la-net.lo] Error 1
#8 185.1 make[2]: *** Waiting for unfinished jobs....
#8 187.0 mv -f src/posix/.deps/libmega_la-waiter.Tpo src/posix/.deps/libmega_la-waiter.Plo
#8 187.0 make[2]: Leaving directory '/root/home/sdk'
#8 187.0 make[1]: *** [Makefile:3347: all-recursive] Error 1
#8 187.0 make[1]: Leaving directory '/root/home/sdk'
#8 187.0 make: *** [Makefile:1517: all] Error 2

---

**Comment by AmirulAndalib** [comment]
please check the error here


https://github.com/AmirulAndalib/MLTB-ALPINE-DOCKER/runs/7357905207?check_suite_focus=true#step:6:982

**Comment by sergiohs84** [comment]
I looks like the link is broken. Probably the issue is related to the usage of a newer compiler, while the crypto library is not updated to support such a new compiler.

https://stackoverflow.com/questions/46815821/assigned-nullptr-to-bool-type-which-compiler-is-correct
