### ISSUE TITLE
Support M1 chip simulator

### ISSUE THREAD

**Issue by cuongtv51** [meganz/sdk#2624]
When i try to run demo on iOS, it print this error:
`
Building for iOS Simulator, but the linked library 'libssl.a' was built for iOS.
`

**Comment by jnavarrom** [comment]
Applications -> Right click on Xcode -> Tick Open with Rosetta

<img width="379" alt="Screenshot 2022-09-28 at 11 46 56" src="https://user-images.githubusercontent.com/3861964/192747637-7864e1d3-3d77-4d68-b1ac-e6104c671bf8.png">
