### ISSUE TITLE
How to cancel login process?

### ISSUE THREAD

**Issue by oviradoi** [meganz/sdk#2625]
I have noticed that if the login process hangs (due to a misconfigured proxy server), the Mega API client will retry the login using an exponential back-off.

Is there any way to configure the maximum number of retries of the login process? Or the values of the exponential back-off used for the login request?

Is there any way to cancel the login process after it has started? I have access to the MegaRequest object from the onRequestTemporaryError method, but I don't see any api->cancelLogin or request->cancel method.

**Comment by mattw-mega** [comment]
That is how it works for all request batches, not just one containing Login.  You do have the option to delete the MegaApi of course, and start from scratch.

**Comment by oviradoi** [comment]
Thanks for the reply. It seems that deleting the MegaApi object is the only way to cancel all the requests, and this is the method I used in the end.
