### ISSUE TITLE
About using via WinHttp or cURL

### ISSUE THREAD

**Issue by jhernancanom** [meganz/sdk#2629]
Hi, friends.
I would like to use MegaNz via WinHttp or cURL. I want you to show me where can I find the info for this.
Thanks for sharing.

**Comment by sergiohs84** [comment]
Hi @jhernancanom. Since MEGA provides a E2EE service, you cannot download files directly by cURL, since the data stored in our servers is encrypted by the client before upload, with the keys controlled by the user. In consequence, the file you download needs to be decrypted upon download.
