### ISSUE TITLE
[Question] two questions about security

### ISSUE THREAD

**Issue by lihe052g** [meganz/sdk#2632]
Hello, I have two questions about security.
1. Why mega uses AES-ECB? It is widely known that this model is not recommended.
2. Does mega have key rotation for file key? And why?

Thanks in advance!

**Comment by sergiohs84** [comment]
Hi there. Let me try to reply to your questions:

1. I encourage you to read the [Security Whitepaper](https://mega.nz/SecurityWhitepaper.pdf), which may solve your doubts.
2. Every new file uploaded to MEGA will use a new encryption key for the new node. However, that unique node's key is not rotated afterwards. The node's keys are encrypted to your master key. Rotating the node's key would require to re-encrypt the data and upload it to our servers again, which would be sub-optimal for users. Thanks
