### ISSUE TITLE
How to get APP key.

### ISSUE THREAD

**Issue by Tman7511** [meganz/sdk#2634]
Hi there, i don't know how now I can get app key. can anyone help me?

**Comment by Salas1313** [comment]
I need help too get key

**Comment by tuokri** [comment]
I don't think you need this anymore. It's working fine for me with just an empty string in place of the app key.

**Comment by sergiohs84** [comment]
Hello, 
MEGA doesn't require a valid `appKey` anymore to communicate with its API. Thanks
