### ISSUE TITLE
OpenSSL warning in Google Play

### ISSUE THREAD

**Issue by acarlsen** [meganz/sdk#2645]
Hi, I use the newest prebuilt SDK binaries for Android in an app. When deploying to Google Play I get the warning below:

> Your app uses a defective version of the OpenSSL library, which can cause your app to crash. Update to a fixed version of OpenSSL.
> 
> Defective versions:
> 
> OpenSSL 1.1.1d in lib/armeabi-v7a/libmega.so

Would it be possible to provide a version with updated OpenSSL version? thanks.

**Comment by sergiohs84** [comment]
Already updated to v3.x. Thanks for the notice :)

**Comment by dknchris** [comment]
@acarlsen Where exactly are the newest prebuilt SDK binaries? Can you link the updated binaries please?
