### ISSUE TITLE
unable to compile megafuse

### ISSUE THREAD

**Issue by ak4153** [meganz/sdk#2667]
Hey, 
I'm having some trouble in compiling sdk/examples/linux/megafuse
I've seen this issue https://github.com/meganz/sdk/issues/128 but my problem is different, I don't get any errors when I run ./configure.

what I did: I followed the steps in the README.md e.g: cloned, `cmake -DVCPKG_ROOT=vcpkg -DCMAKE_BUILD_TYPE=Debug -S sdk -B build_dir` etc..

then I `cd sdk` -> ./configure --with-fuse -> make.
the `compiling sdk/examples/linux/` remains the same and doesn't contain the binary `megafuse`.

followed this 
## How to build and run the project:

To build and run the project, follow theses steps:

1. Build the SDK including the option `--with-fuse` in the `./configure` step
2. Run the `megafuse` binary that you will find in this folder

- If you run it without parameters, it will interactively request the required data 
- You can automate it providing additional parameters: 

  `megafuse [megauser megapassword localmountpoint [megamountpoint]]`

also followed this after running make clean in sdk/ folder
sh autogen.sh
./configure --with-fuse
make
sudo make install

Could you help please?

**Comment by sergiohs84** [comment]
Hi @ak4153 

Thanks for reporting. The `megafuse` example was obsolete and removed.

However, we have added support to add FUSE mount points in Linux, which you can give a try.
Please, check documentation for [addMount()](https://github.com/meganz/sdk/blob/master/include/megaapi.h#L22646) and other public related interfaces in `MegaApi`. They are in order, and the last one is `setMountFlags()` ;) 

If you have questions about this new feature, please, open a new ticket. Thanks
