### ISSUE TITLE
Account-level deduplication 

### ISSUE THREAD

**Issue by sumade123** [meganz/sdk#2671]
I am creating an app that will upload files to Mega, but I wonder if I need to handle the case where the user renames the file.

I read that Mega does account-level deduplication, is this still the case? 

i.e. the user uploads a file, but then the file is renamed and is uploaded again (will this take double the space, or will it recognise the original file, and not take up additional disk space, whilst (in the user's view) the files of both names are still visible).

**Comment by sergiohs84** [comment]
Hi @sumade123 

MEGA does apply de-duplication, yes. For instance, if you upload a file, rename it and upload it again, you'll see how the 2nd upload is not actually transferring data, but doing a remote copy of the original file.

It helps you to save bandwidth. However, both files will occupy space from your storage quota.
