### ISSUE TITLE
Build final command is failing on any windows system with VS2017 or VS2022 as VS2019 is hardcoded in build_from_scratch.cmake

### ISSUE THREAD

**Issue by Kapil-Vermani** [meganz/sdk#2677]

**Comment by antonioborondo** [comment]
Hi @Kapil-Vermani! Starting from version [8.0.0](https://github.com/meganz/sdk/releases/tag/v8.0.0), all editions of Visual Studio 2019 and 2022 are now supported. Try building with any of those versions and let us know how it goes.
