### ISSUE TITLE
Does not build with Visual studio 2022 Community version.  Looks for  only  Microsoft Visual Studio 2019 or 2017 which is no more available.

### ISSUE THREAD

**Issue by parthasarathi204** [meganz/sdk#2682]
cmake -DVCPKG_ROOT=vcpkg -DCMAKE_BUILD_TYPE=Debug -S sdk -B build_dir
-- [SDKlib] is a top-level project. Install target, examples and tests will be enabled by default.
-- Using VCPKG dependencies. VCPKG base path: C:/Users/user/mega/vcpkg and tripplet x64-windows-mega
-- Overlay for VCPKG ports: C:/Users/user/mega/sdk/contrib/cmake/vcpkg_overlay_ports
-- Overlay for VCPKG triplets: C:/Users/user/mega/sdk/contrib/cmake/vcpkg_overlay_triplets
-- Running vcpkg install
command:
"C:\Program Files\CMake\bin\cmake.exe" -DVCPKG_ROOT_DIR=C:/Users/user/mega/vcpkg -DPACKAGES_DIR=C:/Users/user/mega/vcpkg/packages -DBUILDTREES_DIR=C:/Users/user/mega/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Users/user/mega/build_dir/vcpkg_installed -DDOWNLOADS=C:/Users/user/mega/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Users\user\mega\vcpkg\buildtrees\0.vcpkg_dep_info.cmake"
failed with the following output:
d8187afd-ea4a-4fc3-9aa4-a6782e1ed9af, CMake Error at buildtrees/0.vcpkg_dep_info.cmake:23 (message):,   Microsoft Visual Studio 2019 or 2017 could not be found, Call Stack (most recent call first):,   buildtrees/0.vcpkg_dep_info.cmake:48 (vcpkg_triplet_file),   buildtrees/0.vcpkg_dep_info.cmake:66 (vcpkg_get_dep_info), ,
-- Running vcpkg install - failed

**Comment by antonioborondo** [comment]
Hi @parthasarathi204! Starting from version [8.0.0](https://github.com/meganz/sdk/releases/tag/v8.0.0), all editions of Visual Studio 2022 are now supported.
