### ISSUE TITLE
error in making

### ISSUE THREAD

**Issue by ehsan75** [meganz/sdk#274]
I followed following steps on ubuntu
-go to jni folder
-add path to swig in PATH variable
-run make

it compiles all files but finally it fails ...seems to me that swig interface file sdk/bindings/megaapi.i not present in.

-------------------
me/ehsan/ExampleApp_AS/app/src/main/jni/../java/*.class
make[2]: Leaving directory `/home/ehsan/ExampleApp_AS/app/src/main/jni/mega'
make[1]: Leaving directory `/home/ehsan/ExampleApp_AS/app/src/main/jni'
mkdir mega/sdk
mkdir: cannot create directory ‘mega/sdk’: File exists
make: [mega/sdk/bindings/megaapi.i] Error 1 (ignored)
rm mega/sdk/src
ln -s ../../../../../../../../../src mega/sdk/src
rm mega/sdk/include
ln -s ../../../../../../../../../include mega/sdk/include
rm mega/sdk/bindings
ln -s ../../../../../../../../../bindings mega/sdk/bindings
rm mega/sdk/third_party
ln -s ../../../../../../../../../third_party mega/sdk/third_party
make -C mega -f MakefileBindings java_wrap.cxx JAVA_BASE_OUTPUT_PATH=/home/ehsan/ExampleApp_AS/app/src/main/jni/../java
make[1]: Entering directory `/home/ehsan/ExampleApp_AS/app/src/main/jni/mega'
make[1]: *** No rule to make target `sdk/bindings/megaapi.i', needed by `java_wrap.cxx'.  Stop.
make[1]: Leaving directory `/home/ehsan/ExampleApp_AS/app/src/main/jni/mega'
make: *** [mega/java_wrap.cxx] Error 2

**Comment by sergiohs84** [comment]
It seems you copied the example to a different folder out of the SDK (`/home/ehsan/ExampleApp_AS/`), but our building scripts are trying to find the required files in a parent folder (like the command `ln -s ../../../../../../../../../src mega/sdk/src`).

Our suggestion is to keep the original tree structure of the SDK. However, in the event you want to copy the example somewhere else, then you'll need to place a copy of the SDK in the folder `<example>/app/src/main/jni/mega`.

FYI, we've updated the instruction on the `Readme.md` to make it clear.

**Comment by ehsan75** [comment]
You are correct and I am very much thankfull for your fast help...really appreciated

Best regds,
Ehsan
