### ISSUE TITLE
Update to the latest OpenSSL

### ISSUE THREAD

**Issue by glodos** [meganz/sdk#311]
Hi there,

I am using the latest prebuilt shared libraries in my Android app and recently got a warning in the developer console about OpenSSL vulnerabilities. Here you can find more information about that: https://support.google.com/faqs/answer/6376725

I'd like to ask you guys for updating the library linked with the latest Open SSL version to keep things secure.

Thank you in advance.

**Comment by sergiohs84** [comment]
Thank you for reporting. We are updating the prebuilt shared libraries for Android/Java bindings (and the corresponding examples.

The expected changes will be:
 - Update 3rd party libraries to the latest versions (already in use for public applications).
 - Remove obsolete interfaces such as `addContact()`.
 - Minor adjustments in the instructions (`Readme.md`).

We'll notify you once the change is available in our `develop` branch.

Kindly regards

**Comment by sergiohs84** [comment]
Hi @glodos 

The changes I mentioned in the previous comment are now available in the `develop` branch.

Should you want to have a try, you'll see the OpenSSL library has been updated to a secure version without known vulnerabilities.

Regards
