### ISSUE TITLE
How to get total size of remote folder node

### ISSUE THREAD

**Issue by cocia** [meganz/sdk#325]
From browser version mega client(https://mega.nz), we can see the info of folder showing "Total size" and "Contains" children numbers. That's helpful to check the children of folder changed or not.

How can I get similar information by android/java sdk? I was seeking for a while but couldn't find them.

**Comment by javiserrano** [comment]
I think that you are looking for `MegaApi::getSize(MegaNode node)`

**Comment by cocia** [comment]
When I use MegaApi::getSize(MegaNode node) to get size of a folder, it looks like return the total available size of my account. And all the folders seem having same "size".

**Comment by cocia** [comment]
@javiserrano Sorry for my careless. MegaApi::getSize(MegaNode node) is working. I couldn't get right value before because I was using MegaNode.getSize() method. 
I suppose these two api should return same size value but there are not. Why?
