### ISSUE TITLE
memory leaks in MegaApiImpl

### ISSUE THREAD

**Issue by igorge** [meganz/sdk#408]
Multiple memory leak detected by valgrind (sdk git d4b462efc702a9c645e90c202b57e14da3de3501)

1:
0x6BE9D74: mega::MegaApiImpl::init(mega::MegaApi*, char const*, mega::MegaGfxProcessor*, char const*, char const*, int) (megaapi_impl.cpp:3455)

  	else
  	{
  		gfxAccess = new MegaGfxProc();
  	}

2:
0x6BE9B67: mega::MegaApiImpl::init(mega::MegaApi*, char const*, mega::MegaGfxProcessor*, char const*, char const*, int) (megaapi_impl.cpp:3427)

  #ifndef __APPLE__
      (void)fseventsfd;
      fsAccess = new MegaFileSystemAccess();
  #else
      fsAccess = new MegaFileSystemAccess(fseventsfd);

3:
0x6BEAB3D: mega::MegaApiImpl::~MegaApiImpl() (megaapi_impl.cpp:3476)

  MegaApiImpl::~MegaApiImpl()
  {
      MegaRequestPrivate *request = new MegaRequestPrivate(MegaRequest::TYPE_DELETE);
      requestQueue.push(request);
      waiter->notify();

  
4:
0x6BE9AF3: mega::MegaApiImpl::init(mega::MegaApi*, char const*, mega::MegaGfxProcessor*, char const*, char const*, int) (megaapi_impl.cpp:3422)

      httpio = new MegaHttpIO();

**Comment by polmr** [comment]
Thanks @igorge. This is something well known. An ordered memory freeing for those parts isn't straight forward. Anyway it isn't expected for an application to initilize several MegaApi objects. So this will only happen when shutting down the application and hence liberating all the memory.

**Comment by sergiohs84** [comment]
@igorge thank you for reporting. We've confirmed those memory leaks and prepared the fix. Changes will be available shortly.
