### ISSUE TITLE
Android example not building

### ISSUE THREAD

**Issue by Ligandfas** [meganz/sdk#420]
Hello, can't get the app running and in both ways(prebuilt classes and with the makefile) it's either missing methods in the JavaApi.class(with the prebuilt classes way )or getting a build error
![cap1](https://cloud.githubusercontent.com/assets/18163788/18549876/73d05098-7b51-11e6-9726-18feff55d6fc.JPG)

here the path settings
![cap2](https://cloud.githubusercontent.com/assets/18163788/18549968/f2a9b99a-7b51-11e6-9d49-5b3392a2ac08.JPG)

need help :'( thanks

**Comment by CodeNextTechnologies** [comment]
I am also having same issue.

**Comment by sergiohs84** [comment]
We have recently updated the prebuilt libraries and the auto-generated classes for the Android examples (both AndroidStudio and Eclipse).

Please, pull the latest changes and try again with the new files linked in the Readme.md (https://github.com/meganz/sdk/tree/master/examples/android/ExampleApp_AS).

Thanks
