### ISSUE TITLE
Request  for tagging/release archives

### ISSUE THREAD

**Issue by shameempk** [meganz/sdk#436]
Curious about the 'no tagging' policy of sdk for almost 2 years (from 2.5.0 on wards). Release tarballs are pretty much required for packaging megasync client for new linux distros.
Please do tagging/release for the sdk.

**Comment by Codalunga** [comment]
+1 for this, it actually limits MEGA employment on different distros, like Solus.

**Comment by sergiohs84** [comment]
We've made some changes to update SDK version numbers accordingly. You can expect tags for the upcoming releases. 
Thanks for your understanding and reporting.

**Comment by shameempk** [comment]
Thanks. Quite fast response.
