### ISSUE TITLE
10175 segmentation fault  megasync

### ISSUE THREAD

**Issue by jemadux** [meganz/sdk#444]
I used debian sid and i wanted to make a fresh install with debian testing . in debian sid i used the username angelos and I moved the /home/angelos to /home/jemadux .  I desired to use the username jemadux and that is . i tried the deb files that is on mega.zn and says that not working .. so i deleted I guess the data of mega 

```
$ rm -rf .local/share/data/Mega\ Limited 
```

and when from command line start the mega is

```
$ megasync 
[1]    10175 segmentation fault  megasync
```

and i cant connect to server .. do i have to do something elase

**Comment by javiserrano** [comment]
Could you open the issue in the repo of MEGAsync please?
https://github.com/meganz/MEGAsync

Thank you!
