### ISSUE TITLE
Flow control with MegaApi::startStreaming

### ISSUE THREAD

**Issue by connesc** [meganz/sdk#510]
Hi,

I plan to use `MegaApi::startStreaming` from the intermediate layer.
However, I wonder how I can control the download speed.

My use case involves multiple download streams that are consumed at different rates, including rather low rates.
Since the downloaded files are large, it is not an option to buffer them at full speed for a later use.
Ideally, I would like each transfer to independently adjust its speed to its consumption rate.

Is this possible?

My first idea was to block the `MegaTransferListener::onTransferUpdate` callback until the consumer is ready to handle more input. Is this correct?

Thanks!

**Comment by sergiohs84** [comment]
Hi Cédrin

At first glance, you can use `MegaApi::startStreaming`. However, you won't be able to limit the speed for each transfer independently, but globally for every on-going download. It means that, for your use case, you will need one instance of `MegaApi` per transfer, which is probably not doable in terms of performance.

Our recommendation is to use the HTTP server feature integrated in the SDK. You can implement the flow control for the HTTP connection. In example, you may have a thread per connection and block them according to your needs.

https://github.com/meganz/sdk/blob/master/include/megaapi.h#L7881

Hope it helps you and fulfills your needs to develop your apps.

Best regards

**Comment by connesc** [comment]
Hi Sergio,

Thanks a lot for this comprehensive answer.

I did not noticed this feature, probably because the [Doxygen docs](https://mega.co.nz/#!c5FzhBJL!HUVjsOJTylwkmXPZ0AxT66Wuu4YvZInyHbWGYgvTHt4) are outdated.
This looks really promising, and will certainly fulfill my requirements.

Thanks!

**Comment by sergiohs84** [comment]
Well noted, @connesc 

You're very right, the doxygen docs were quite outdated. Just pushed a new link with an updated version ([download it here](https://mega.nz/#!7glwEQBT!Fy9cwPpCmuaVdEkW19qwBLaiMeyufB1kseqisOAxfi8)) Thanks for telling us.

Best regards

**Comment by connesc** [comment]
Hi,

Thanks for the updated doc! Maybe the master branch could be updated as well.

FYI, the HTTP proxy works very well. I have written a small wrapper to expose the feature: [megaproxy](https://github.com/connesc/megaproxy).

A few notes for future references:
- To enable the HTTP proxy, libmega must be built with libuv. The `configure` script does not have a `--with-libuv` flag, but this is roughly equivalent:
```
./configure CXXFLAGS=-DHAVE_LIBUV=1 LDFLAGS=-luv
```
The `HAVE_LIBUV` flag is also needed at include time:
```c++
#define HAVE_LIBUV 1
#include <megaapi.h>
```

- The folder listing does not properly define a charset. This might cause issues with non-ASCII filenames. A possible workaround is to override the `Content-Type` header with `text/html; charset=utf-8`. This can be done easily with Nginx:
```nginx
location / {
    proxy_pass http://localhost:4443;
    charset utf-8;
}
```
