### ISSUE TITLE
Enable compiling options in jenkins (for checks)

### ISSUE THREAD

**Issue by latot** [meganz/sdk#523]
Hi all, i want request this, well testing ar al least in my experience some time there is pr cause fails in the compilation time, so to try avoid this, is possible use travis here?

Thx. Cya.

**Comment by polmr** [comment]
excuse me, I can't understand your wording. Could you please rephrase it?

**Comment by latot** [comment]
Hi, sorry my bad english...

Lets try again, here some times when up some code it causes compilation errors, like, https://github.com/meganz/sdk/issues/524, but this don't is the first time i found it, and when i search some past commits there is a lot of this....
So to avoid this in the future i think can be good implement travis to check if the code you want to include to the project can be compiled without problem (or at least in ubuntu for example).

**Comment by polmr** [comment]
I think I get it now. We do have some system to check PRs automatically (we use Jenkins instead of Travis). But in this particular case #524, the test system isn't compiling fuse example. We'll had it. thanks for reporting.

**Comment by latot** [comment]
mm, maybe to complement it, is possible enable all the test/options in jenkins?, like a full check.
