### ISSUE TITLE
How to log MegaSDK C++

### ISSUE THREAD

**Issue by dima72** [meganz/sdk#533]
Please provide brief instructions how to 
get log of MegaSDK  please consider that I'm on VisualStudio.

**Comment by javiserrano** [comment]
Hi,

Please take a look at `MegaApi::setLogLevel` and `MegaApi::setLoggerObject`. Using those functions, you can get logs in your own subclass of `MegaLogger` and manage them as you want (writting them to  `stdout`, to a file, etc.).

Using  `MegaApi::setLogLevel` only, a default logger will be used that prints logs to `stdout`.
