### ISSUE TITLE
Filenames and Dirnames with spaces are not listed with fetchNodes()

### ISSUE THREAD

**Issue by dima72** [meganz/sdk#548]
Dear MEGA Developers,  
please explain, whether this is known bug or perhaps some settings are missed.
If filename or dirname with space e.g 'New Text File.txt'  - is never listed in my application
after fetchNodes()

thanks in advance,

**Comment by dima72** [comment]
UP

**Comment by polmr** [comment]
Dear @dima72 , the SDK is totally compliant with filenames with spaces. All the applications that use it support those. 

You might want to take a look at those. For instance, MEGAcmd (https://github.com/meganz/sdk/tree/master/examples/megacmd).

If you need further assistance, please, paste the minimum piece of code we can use to try to reproduce your issue.

**Comment by dima72** [comment]
ops, sorry for razing this topic, it was out internal bug.
I have tested files and folders with spaces are listed and uploaded without problem.
thanks for the attention.
