### ISSUE TITLE
listener->OnRequestTemporaryError

### ISSUE THREAD

**Issue by dima72** [meganz/sdk#549]
Please advice must or must not be OnRequestTemporaryError implemented in decendant class?
In my application i have MegaRequestListener and MegaListener descendants.

As soon as  I implement in them empty OnRequestTemporaryError method, my application starts crashing if network errors happen. Exceptions appear in megaapi_impl.cpp
void MegaApiImpl::fireOnRequestFinish(MegaRequestPrivate *request, MegaError e)
about here
**requestMap.erase(request->getTag());**

in fact requestMap is trying to erase not existing listener or call its event. 
this happens in many places. Listeners are not released from MegaApi lists, etc..

**Comment by polmr** [comment]
Respuesta a https://github.com/meganz/sdk/issues/549
Yes, you can implement OnRequestTemporaryError in your decendant class. 
map::erase method doesn't crash if the key couldn't be found. My guess is that `request` has been deleted before and it is `getTag` what is throwing the exception. Remember that in your implementation of MegaRequestListener::onRequestFinish, and  MegaRequestListener::OnRequestTemporaryError "The SDK retains the ownership of the request and error parameters", hence, you should not delete it and would need to copy (MegaRequest::copy) it if you want to use it ouside there.

**Comment by dima72** [comment]
```
MyListener lr;
mega_api->addListener(&lr);
lr.wait();
```
problem is, i do nothing about `request` in code of listener. I just quit of `wait()` method if OnRequestTemporaryError happens. After that the listener is destroyed because  
my method is quit out of scope, BUT OnRequestTemporaryError happens again and again on non-existing listener.

> map::erase method doesn't crash if the key couldn't be found.
i'm guessing that is not the best programming technique.

**Comment by polmr** [comment]
If I'm understanding you correctly, you are passing a pointer to your MyListener, that gets deleted after whatever function you're in ends. That's extremely hazardous, since your "mega_api" object has a reference to an invalid position (and will eventually use). You should either pass a pointer to an instance dynamically allocated (new MyListener) and take care of freeing that memory somewhere; or remove the listener before the function ends: `mega_api->removeLitener(&lr)`.

**Comment by dima72** [comment]
Great, that makes it clear. Maybe best way to `removeListener`  in `wait()` method at the end, so mega_api never knows about the listener again. 

Can you say if there might be any problems if there are single mega_api instance but many listeners
belonging to different threads?

**Comment by polmr** [comment]
The sdk runs in a separate thread. It will call your listeners IN ITS THREAD. Remember you need to ensure those listeners exist when that happens. MegApi will just call their callbacks one by one.

**Comment by dima72** [comment]
To my disappointment, since i move 
mega_api->removeListener(this)  to the very end of wait() method

immediately i'm getting access violation.
```
megaapi_impl.cpp line 9834
void MegaApiImpl::removeListener(MegaListener* listener)
{
if(!listener) return;
sdkMutex.lock();
^^^^^^^ **crashes here**
listeners.erase(listener);
sdkMutex.unlock();
}
```
BUT this does not happen if I use listener this way:
```
MyListener lr;
mega_api->addListener(&lr);
lr.wait();
mega_api->removeListener(&lr);


```

**Comment by javiserrano** [comment]
Hi!

Looking at the crash I would say that there should be a problem managing different threads and either the `MegaApi` object or the `listener` object is deleted before the call to `removeListener`.

If you can give us enough code to reproduce the crash, I think that we could help you better. The implementation of `MyListener` would be specially interesting to solve the issue.

Regards, Javi.
