### ISSUE TITLE
megacmd failed to compile on mingw

### ISSUE THREAD

**Issue by shinchiro** [meganz/sdk#550]
Hello, I'm trying to compile megacmd from `release/3.0` branch on mingw but it failed with a lot of undefine error. Am I missing something?
[k.txt](https://github.com/meganz/sdk/files/747847/k.txt)

**Comment by polmr** [comment]
Hi @shinchiro 
What's your configure order?
Did you configure with `--disable-megaapi` ?
Anyway, I believe there are other issues compiling with MINGW in that branch (working on it...). However, in the  meantime, if you want to try MEGAcmd in windows you can download it from here: https://mega.nz/cmd. We've just released a version with what's in `release/v3.0.0` branch.

**Comment by polmr** [comment]
the other issues have been fixed now

**Comment by shinchiro** [comment]
Try pulling the latest commits but still out of luck..It still giving undefined error :/ 
This is my configure:
```
./configure --disable-shared --enable-static --disable-silent-rules --without-openssl --disable-megaapi --with-cryptopp=$INSTALL_PATH --without-sodium --with-zlib=$INSTALL_PATH --with-sqlite=$INSTALL_PATH --without-cares --without-curl --with-winhttp=/d/MSYS/mega-sdk/sdk --without-freeimage --with-readline=$INSTALL_PATH --with-termcap=$INSTALL_PATH --prefix=$INSTALL_PATH 
```

Also is it possible to perform task like uploading without blocking running other command?
In megacli, I can uploading files and calling other command during uploading

**Comment by polmr** [comment]
You should remove the `--disable-megaapi`. That's what's causing the undefined errors.

With MEGAcmd you can use it in "non-interactive" mode (see some information here: https://github.com/meganz/sdk/tree/release/v3.0.0/examples/megacmd or using "help --non-interactive" within MEGAcmd shell). In this mode you can run anything in background.

**Comment by shinchiro** [comment]
Thanks for tip. I'm able to compile it now. 

But in `build_sdk.sh`, sdk is compiled with `--disable-megaapi` by default if you dont set the `-a` switch, which is wrong I think, when megacmd is enabled by default
