### ISSUE TITLE
Getting error after executing "sh autogen.sh" command on Linux

### ISSUE THREAD

**Issue by talhakabakus** [meganz/sdk#554]
I am just following the instructions [here](https://github.com/meganz/sdk/tree/master/examples/java) in order to build Mega SDK Java libraries on Linux (Ubuntu). When I try to execute the first command which is `sh autogen.sh`, I get the following error: `autogen.sh: 2: autogen.sh: autoreconf: not found`.

And, I'd like to learn if there will be an import-and-use Java library soon.

**Comment by polmr** [comment]
This is because you don't have autoreconf installed. In ubuntu you do it with:
`sudo apt-get install autoconf`
Concerning Java. As of now we are not offering a packed jar you can use. We will consider however your petition.

**Comment by talhakabakus** [comment]
Thanks for your quick response @polmr , here is the error output despite I have installed `autoconf`:

```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:96: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by polmr** [comment]
I believe installing libtool fixes that one. We need to state these dependencies. Thanks for reporting.

**Comment by talhakabakus** [comment]
Thanks for your care, looking forward to see improvements. Would like to use evaluate the performance of MEGA alongside other cloud file sharing platforms for my academic research.

**Comment by polmr** [comment]
readme explains the dependency of autoconf and libtool now (branch `develop` by the moment)
