### ISSUE TITLE
On iOS, MEGAAcountDetails is not available

### ISSUE THREAD

**Issue by sylverb** [meganz/sdk#56]
It is not possible to get account details with current iOS binding
In MEGARequest.mm :
    - (MEGAAcountDetails *) megaAccountDetails  {
        return nil;
    }
Is there a fix for this planned ?

**Comment by javiserrano** [comment]
Hi!

You are right. It isn't implemented yet.
It only requires few changes so we will do it in few days.

Thank you for pointing it out.

**Comment by javiserrano** [comment]
The last commit should fix the problem.
Please open a new issue if you have any problem using this feature (or any other).

Thanks!

**Comment by sylverb** [comment]
Working perfectly ! Thanks a lot !
