### ISSUE TITLE
[Linux] Getting the error "configure: error: cryptopp/cryptlib.h header not found or not usable"

### ISSUE THREAD

**Issue by talhakabakus** [meganz/sdk#565]
Following the issue #554, despite I have installed `autoconf` and `libtool` packages, still getting the error `configure: error: cryptopp/cryptlib.h header not found or not usable` when I execute `./configure` command on `Ubuntu 14.04`.

**Comment by polmr** [comment]
You need to install all the required dependencies. Those are described here (https://github.com/meganz/sdk). See the `posix` part.
