### ISSUE TITLE
[Linux] Building Java examples with required dependencies

### ISSUE THREAD

**Issue by tymoteuszborkowski** [meganz/sdk#580]
Hi,
is there any way to build java examples on Linux with all required dependencies? I generated library successfully, but if I want to compile CRUD example on my other computer with linux i have to install all these packages again. Otherwise I have error: "cannot open shared object file: No such file or directory".

Thanks in advance.

**Comment by sergiohs84** [comment]
The Java example has been updated to avoid your observed issue. Please, give it a try with a recent version of the repo.
