### ISSUE TITLE
OpenSSL Issues

### ISSUE THREAD

**Issue by crazyhorse961** [meganz/sdk#584]
Hello,
i'm having an issue from 3 hours now..
Basically i'm using the java api, but for making it run it needs 5 files/libraries and i were able just to find mega.dll (and his dependencies).
I get the following when i run the code (https://hastebin.com/ufanoviziq.sql).
The problem is that i'm not able to find the .so files even after cloning the project... trying on a linux machine... repeating the tutorial steps in the java tutorial...
I'm out of ideas, where i can find the .so/.dylib required files ?
Thank you & have a good day

**Comment by crazyhorse961** [comment]
Update, i did many progress, now while doing ./configure i get the following:
`configure: error: Make sure cURL is built/linked with OpenSSL!`
Any fix?

**Comment by sergiohs84** [comment]
Hi there
You need cURL library with OpenSSL support, which is not the standard cURL library. For Debian-based distributions, the package is called `libcurl4-openssl-dev`. For Fedora-like, `libcurl-devel` (compiled with `--enable-ssl`).
Thanks

**Comment by javiserrano** [comment]
If you are sure that you are building with a `libcurl` library that was built with `OpenSSL`, maybe the check in the configure script is failing. To test it, you can add the option `--disable-curl-checks` to your `./configure` command. That should let you build the SDK, but if `libcurl` is not really built with `OpenSSL`, you will get a runtime error and your application will close at startup.

**Comment by crazyhorse961** [comment]
I did it and curl works as intended but the error still occurs.
I also tried the flag --without-ssl on setup of mega but i still get the error (i cannot disable OpenSSL from an application that uses it)

**Comment by sergiohs84** [comment]
Closing this ticket, since it become too old. Feel free to reopen if you still observe the issue with a recent version of the SDK. Thanks

**Comment by gvalchca** [comment]
Hi,
I keep running into an error when installing megacmd. Im trying to get it to work on the cluster where I don't have admin permissions.

```
checking whether cURL is built with OpenSSL support... no
configure: error: Make sure cURL is built/linked with OpenSSL!
configure: error: ./configure failed for sdk
```

I've compiled curl myself and it says it has the OpenSSL support:

```
$ curl -V
curl 7.83.0-DEV (x86_64-unknown-linux-gnu) libcurl/7.83.0-DEV OpenSSL/1.0.2k-fips zlib/1.2.7 OpenLDAP/2.4.44
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```

any ideas?

**Comment by aabellagm** [comment]
Hi @gvalchca,
Would you mind to share with us the configure line you are executing and attach the complete output? The exact OS where you are building MEGAcmd would help a lot too, so we can suggest which system packages you need.
My first idea is that the curl library detected by configure is not built with openssl despite the binary you built have it enabled. You can try adding "--disable-curl-checks --with-curl=<full_path>" pointing to the path where the openssl lib you built is located.
Almost at the end of "sdk/config.log" should be the testing lines which could explain a bit more of what is happening. You can try to review it by yourself or sharing it with us.

Thanks for using MEGAcmd!

**Comment by gvalchca** [comment]
Hi,

In the end I've  managed to configure using the following:

`./configure --with-cryptopp='$HOME/programs/cryptopp' --prefix='$HOME/programs/megacmd_install' --with-cares='$HOME/programs/c-ares' --disable-curl-checks --with-freeimage='$HOME/programs/FreeImageInstall/usr' --with-sodium='$HOME/programs/sodium'
`

but still, it doesn't compile:

`libtool: link: warning: library `/programs/c-ares/lib/libcares.la' was moved.
libtool: link: warning: library `/programs/c-ares/lib/libcares.la' was moved.
src/mega_cmd_server-megacmdutils.o: In function `megacmd::isRegExp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/programs/MEGAcmd/src/megacmdutils.cpp:987: undefined reference to `pcrecpp::RE::QuoteMeta[abi:cxx11](pcrecpp::StringPiece const&)'
src/mega_cmd_server-megacmdutils.o: In function `megacmd::unquote(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/programs/MEGAcmd/src/megacmdutils.cpp:1025: undefined reference to `pcrecpp::RE::QuoteMeta[abi:cxx11](pcrecpp::StringPiece const&)'
src/mega_cmd_server-megacmdutils.o: In function `pcrecpp::RE::RE(char const*)':
/usr/include/pcrecpp.h:493: undefined reference to `pcrecpp::RE::Init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, pcrecpp::RE_Options const*)'
src/mega_cmd_server-megacmdutils.o: In function `pcrecpp::RE::RE(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/include/pcrecpp.h:491: undefined reference to `pcrecpp::RE::Init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, pcrecpp::RE_Options const*)'
src/mega_cmd_server-megacmdutils.o: In function `pcrecpp::RE::operator=(pcrecpp::RE const&)':
/usr/include/pcrecpp.h:513: undefined reference to `pcrecpp::RE::Init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, pcrecpp::RE_Options const*)'
collect2: error: ld returned 1 exit status`

any ideas?
