### ISSUE TITLE
Compiling fails on Ubuntu 12.04.5 with gcc version 4.6.3

### ISSUE THREAD

**Issue by nephilim1973** [meganz/sdk#59]
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)

# sh autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --install --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./config.guess'
libtoolize: copying file `./config.sub'
libtoolize: copying file `./install-sh'
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'

-----------------------------------------------------------------------------

# ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert i686-pc-linux-gnu file names to i686-pc-linux-gnu format... func_convert_file_noop
checking how to convert i686-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether make supports nested variables... (cached) yes
checking for size_t... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for pid_t... yes
checking for off_t... yes
checking for ssize_t... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether build environment is sane... yes
checking for cppcheck... no
checking for ANSI C header files... (cached) yes
checking for ANSI C header files... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... 64
checking for _LARGEFILE_SOURCE value needed for large files... no
checking for off_t... (cached) yes
checking size of uint64_t... 8
checking whether struct tm is in sys/time.h or time.h... time.h
checking for off_t... (cached) yes
checking for size_t... (cached) yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/timeb.h usability... yes
checking sys/timeb.h presence... yes
checking for sys/timeb.h... yes
checking htonl usability... no
checking htonl presence... no
checking for htonl... no
checking whether C++ compiler accepts -fPIC... yes
checking whether the linker accepts -fPIC... yes
checking sys/inotify.h usability... yes
checking sys/inotify.h presence... yes
checking for sys/inotify.h... yes
checking mcheck.h usability... yes
checking mcheck.h presence... yes
checking for mcheck.h... yes
checking for inotify_init1... yes
checking for fdopendir... yes
checking for select... yes
checking for sendfile in -lsendfile... no
checking for socket in -lsocket... no
checking for clock_gettime in -lrt... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking if building for Win32 platform... no
checking for pthread_create in -lpthread... yes
checking for libcryptopp... --with-cryptopp not specified
checking cryptopp/cryptlib.h usability... yes
checking cryptopp/cryptlib.h presence... yes
checking for cryptopp/cryptlib.h... yes
checking for main in -lcryptopp... yes
checking for libsodium... --with-sodium not specified
checking sodium/core.h usability... no
checking sodium/core.h presence... no
checking for sodium/core.h... no
configure: sodium/core.h header not found or not usable
checking for sodium_init in -lsodium... no
configure: Could not find libsodium
checking for zlib... --with-zlib not specified
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for main in -lz... yes
checking for SQLite... --with-sqlite not specified
checking for Berkeley DB... --with-db not specified
configure: Using SQLite3 as the default DB access layer.
checking sqlite3.h usability... yes
checking sqlite3.h presence... yes
checking for sqlite3.h... yes
checking for sqlite3_open in -lsqlite3... yes
checking for OpenSSL... --with-openssl not specified
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for SSL_new in -lssl... yes
checking for c-ares... --with-cares not specified
checking ares.h usability... yes
checking ares.h presence... yes
checking for ares.h... yes
checking for ares_library_init in -lcares... yes
checking curl/curl.h usability... yes
checking curl/curl.h presence... yes
checking for curl/curl.h... yes
checking for main in -lcurl... yes
checking whether cURL is built with OpenSSL support... yes
checking if building example applications... yes
checking for FreeImage... --with-freeimage not specified
checking FreeImage.h usability... yes
checking FreeImage.h presence... yes
checking for FreeImage.h... yes
checking for main in -lfreeimage... yes
checking for termcap... --with-termcap not specified
checking for tputs in -ltermcap... yes
checking for Readline... --with-readline not specified
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
checking for rl_save_prompt in -lreadline... yes
checking if building tests... no
checking for doxygen... no
configure: WARNING: doxygen not found - will not generate any doxygen documentation
checking for perl... /usr/bin/perl
configure: creating ./config.status
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating libmega.pc
config.status: creating include/mega/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure: Configured to build Mega SDK:

  SDK version:      2.5.0
  Host setup:       i686-pc-linux-gnu
  Install prefix:   /usr/local
  Compiler:         g++
  CXXFLAGS:         -g -O2 -fPIC
  gcc hardening:    no
  debug:            no
  static:           no
  sync subsystem    yes
  MEGA API          yes
  example apps:     yes

  inotify:          yes
  posix threads:    yes

  OpenSSL:            -lssl
  Crypto++:           -lcryptopp
  Sodium:             
  Zlib:               -lz
  SQLite3:            -lsqlite3
  c-ares:             -lcares
  cURL:              -lcurl
  FreeeImage:         -lfreeimage
  Readline:           -lreadline
  Termcap:            -ltermcap

-----------------------------------------------------------------------------

# make -j
make  all-recursive
make[1]: Entering directory `/root/GIT/mega-sdk'
Making all in include
make[2]: Entering directory `/root/GIT/mega-sdk/include'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/GIT/mega-sdk/include'
make[2]: Entering directory `/root/GIT/mega-sdk'
  CXX    src/src_libmega_la-megaapi_impl.lo
  CXX    src/src_libmega_la-megaapi.lo
  CXX    src/gfx/src_libmega_la-freeimage.lo
  CXX    src/src_libmega_la-megaclient.lo
  CXX    src/src_libmega_la-attrmap.lo
  CXX    src/src_libmega_la-backofftimer.lo
  CXX    src/src_libmega_la-base64.lo
  CXX    src/src_libmega_la-command.lo
  CXX    src/src_libmega_la-commands.lo
  CXX    src/src_libmega_la-db.lo
  CXX    src/src_libmega_la-fileattributefetch.lo
  CXX    src/src_libmega_la-file.lo
  CXX    src/src_libmega_la-filefingerprint.lo
  CXX    src/src_libmega_la-filesystem.lo
  CXX    src/src_libmega_la-gfx.lo
  CXX    src/src_libmega_la-http.lo
  CXX    src/src_libmega_la-json.lo
  CXX    src/src_libmega_la-node.lo
  CXX    src/src_libmega_la-pubkeyaction.lo
  CXX    src/src_libmega_la-request.lo
  CXX    src/src_libmega_la-serialize64.lo
  CXX    src/src_libmega_la-share.lo
  CXX    src/src_libmega_la-sharenodekeys.lo
  CXX    src/src_libmega_la-sync.lo
  CXX    src/src_libmega_la-transfer.lo
  CXX    src/src_libmega_la-transferslot.lo
  CXX    src/src_libmega_la-treeproc.lo
  CXX    src/src_libmega_la-user.lo
  CXX    src/src_libmega_la-utils.lo
  CXX    src/src_libmega_la-logging.lo
  CXX    src/src_libmega_la-waiterbase.lo
  CXX    src/src_libmega_la-proxy.lo
  CXX    src/crypto/src_libmega_la-cryptopp.lo
  CXX    src/db/src_libmega_la-sqlite.lo
  CXX    third_party/utf8proc/src_libmega_la-utf8proc.lo
  CXX    src/gfx/src_libmega_la-external.lo
  CXX    src/posix/src_libmega_la-fs.lo
  CXX    src/posix/src_libmega_la-console.lo
  CXX    src/posix/src_libmega_la-net.lo
  CXX    src/posix/src_libmega_la-waiter.lo
  CXX    src/posix/src_libmega_la-consolewaiter.lo
  CXX    src/thread/src_libmega_la-posixthread.lo
  CXX    examples/examples_megacli-megacli.o
  CXX    examples/examples_megasimplesync-megasimplesync.o
src/megaapi_impl.cpp:39:0: warning: "_LARGEFILE64_SOURCE" redefined [enabled by default]
/usr/include/features.h:170:0: note: this is the location of the previous definition
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[2]: *** [src/src_libmega_la-megaapi_impl.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[2]: *** [src/src_libmega_la-megaapi.lo] Error 1
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[2]: *** [src/gfx/src_libmega_la-freeimage.lo] Error 1
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[2]: *** [src/src_libmega_la-megaclient.lo] Error 1
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[2]: *** [src/src_libmega_la-command.lo] Error 1
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[2]: *** [src/src_libmega_la-commands.lo] Error 1
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[2]: *** [src/src_libmega_la-fileattributefetch.lo] Error 1
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[2]: *** [src/src_libmega_la-file.lo] Error 1
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[2]: *** [src/src_libmega_la-gfx.lo] Error 1
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[2]: *** [src/src_libmega_la-node.lo] Error 1
src/posix/waiter.cpp: In member function ‘void mega::PosixWaiter::notify()’:
src/posix/waiter.cpp:141:29: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
make[2]: Leaving directory `/root/GIT/mega-sdk'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/GIT/mega-sdk'
make: *** [all] Error 2

**Comment by wizzard** [comment]
Hello,
this issue most likely related to your environment: ```g++: internal compiler error: Killed```

I could confirm that SDK compiles fine for me on Ubuntu 12.04.5 with gcc version 4.6.3. 

What architecture do you use? is it 32bit or 64bit Ubuntu? 

Have you tried to compile any other C++ applications?

**Comment by nephilim1973** [comment]
Hi wizzard...
I use an 2.6.32 SMP kernel on an i686 athlon i386 GNU/Linux architecture (32 Bit)
Until now, all compilations were running fine.

Could I provide you with more detailed informations ?

**Comment by wizzard** [comment]
yeah, this could be the problem, MEGA SDK requires quite a lot of RAM to compile.

**Comment by nephilim1973** [comment]
For physical machines, here is a workaround:

dd if=/dev/zero of=/var/swap.img bs=1024k count=4000
mkswap /var/swap.img
swapon /var/swap.img

Generates a 4 GB swap file and activates it, so you could use more RAM while compiling (but it's very slow, of course !)

Unfortunatelly, I use a virtual machine on OpenVZ and this workaround is nit supported  :-(
Is is possible to reduce the amount of RAM while compiling ? (command line option for "configure" etc. ?)

**Comment by wizzard** [comment]
Unfortunately I'm not aware of any way to reduce RAM usage for C++ compilation (you might try to use clang compiler: http://clang.llvm.org/)

**Comment by pohutukawa** [comment]
Have you tried compiling using `make` without the `-j` flag. `-j` forks into many concurrent compiler invocations to speed up the compile to interleave better with I/O and on multi-core machines, however heavily at the expense of memory usage. So a normal/vanilla `make` instead may actually work for your case.

**Comment by nephilim1973** [comment]
A man should not always keep stubbornly to the instructions... :-)
@ pohutukawa: You make my day.  Success ! Thanks a lot. Often the simple solutions are also the best.
