### ISSUE TITLE
./configure on OSX Yosemite with MacPorts and cryptopp

### ISSUE THREAD

**Issue by lpetrov** [meganz/sdk#62]
I'd managed to install the libcryptopp and cryptopp with ports install..
However, cryptopp is in /opt/local/include/cryptopp, which i'd set via --with-cryptopp, but the ./configure command stills fail with:
```configure: error: Could not find libcryptopp```
Tried " --with-libcryptopp=/opt/local/lib/", but no success :)

**Comment by wizzard** [comment]
Hello,
could you please attach ```config.log``` file, which is located in SDK root directory?
Thank you

**Comment by lpetrov** [comment]
Here is the config.log:
https://gist.github.com/lpetrov/59a1e2b5cc463867fb73

**Comment by wizzard** [comment]
Could you please try to point the "base" of the installation: 
```./configure --with-cryptopp=/opt/local/```

Please let me know if it work for you!

**Comment by lpetrov** [comment]
It worked :)

Thanks!
L

**Comment by lpetrov** [comment]
In case that some is wondering how to make this work with MacPorts, instead of homebrew...
1. do a sudo port install on the packages listed in doc/OSX.txt
2. follow the same steps as listed in the OSX.txt file
3. when doing ./configure, just use the following command:
```
./configure --with-cryptopp=/opt/local/ --with-cares=/opt/local/ --with-curl=/opt/local/ --with-freeimage=/opt/local/ --with-readline=/opt/local/
```
And it worked as charm :)
