### ISSUE TITLE
sh autogen.sh fails on Kubuntu 14.04 64bit

### ISSUE THREAD

**Issue by jalomann** [meganz/sdk#64]
I am compiling on Kubuntu 14.04 64bit. Running autogen.sh gives the following:

$ sh autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:108: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by wizzard** [comment]
Hello, please install ```libtool``` package:
```sudo apt-get install libtool```

**Comment by jalomann** [comment]
Solved the problem. Thank you!
