### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by hazrasudip9** [meganz/sdk#648]
OBJCXXLD src/libmega.la
libtool: link: unable to infer tagged configuration
libtool:   error: specify a tag with '--tag'
Makefile:1660: recipe for target 'src/libmega.la' failed
make[2]: *** [src/libmega.la] Error 1
make[2]: Leaving directory '/home/sudip/Desktop/sdk-2.8.0'
Makefile:2586: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/sudip/Desktop/sdk-2.8.0'
Makefile:1274: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by polmr** [comment]
We've had to add `AM_LIBTOOLFLAGS="--tag=CXX"` to predetermine the tag to Makefile.am for some cross compilations. Maybe that could help you.

**Comment by hazrasudip9** [comment]
Thanks .
