### ISSUE TITLE
Building with MSVC-2015

### ISSUE THREAD

**Issue by gvanem** [meganz/sdk#656]
I had little problem building Mega.dll using MinGW. But using MSVC-2015 or clang-cl is an endless struggle. One error is from `src/attrmap.cpp`:
```
error C2504: 'Cachable': base class undefined"
```
So I tried cooking up a Python-script to generate a dependency output with the help of `-showIncludes`. Low an behold, it shows that `include/mega/types.h` gets included **after** other headers using it (or depending on `struct Cachable`) . Here is the dependency output of `src/attrmap.cpp`:
```
 F:\MingW32\src\inet\Web\Mega-SDK\include\mega/attrmap.h"
  F:\MingW32\src\inet\Web\Mega-SDK\include\mega/utils.h"
   f:\mingw32\src\inet\web\mega-sdk\include\mega\types.h"
    F:\MingW32\src\inet\Web\Mega-SDK\include\mega/win32/megasys.h"
     f:\ProgramFiler-x86\WindowsKits\Include\10.0.15063.0\ucrt\inttypes.h"
      f:\ProgramFiler-x86\WindowsKits\Include\10.0.15063.0\ucrt\corecrt.h"

... lot of system headers here ...

            F:\MingW32\src\inet\Web\Mega-SDK\include\mega\share.h"
             f:\mingw32\src\inet\web\mega-sdk\include\mega\types.h"  << Cachable should be seen here, but isn't
             f:\mingw32\src\inet\web\mega-sdk\include\mega\user.h"
              f:\mingw32\src\inet\web\mega-sdk\include\mega\attrmap.h"
```

Not the indenting. Anybody who can give me a glue?

**Comment by gvanem** [comment]
I noted that the file `mega/mega_http_parser.h` may define basic types like `u_int64_t` Why?
IMHO, all such basic types should go into `mega/types.h`. I guess the above problem is due to some circular-dependency in the `include/*.h` files. I give up on the SDK for now.

**Comment by sergiohs84** [comment]
Visual Studio 2015 is not supported anymore. We are using VS 2019 and currently in the progress to support VS 2022.
Closing this ticket as obsolete. Thanks
