### ISSUE TITLE
[Ubuntu] compilation problem on Ubuntu Server

### ISSUE THREAD

**Issue by Neeqstock** [meganz/sdk#659]
Hi,
I'm trying to compile the SDK for java, on a machine with Ubuntu Server and an Intel Xeon processor.
I've added all the dependencies manually, then i run "autoconf.sh" and

`./configure --enable-java --with-java-include-dir=/usr/lib/jvm/java-8-oracle/include`

and everything goes fine.
The fact is that when i do "make", this is the result:

[Error.txt](https://github.com/meganz/sdk/files/1004462/Error.txt)

Note that I had to manually install SWIG because it wasn't present on my machine.
I've tried to reinstall it with both apt-get and by downloading and compiling the last version (3.0.12), but no way.

How can I solve this?

Or, else, are there precompiled .so for my system, somewhere?

Thank you very much.

**Comment by polmr** [comment]
AFAIK, there's no precompiled .so you can use.
I've seen that errors in swig 2.0. Solved by using 3.0. Are you certain there's no older swig installed in your system? and configure is using 3.0.12? If you can't figure it out, please, send us the output of `./configure` and `config.log` file

**Comment by Neeqstock** [comment]
First of all, thank you for your answer.

SOLVED.
I was quite sure that I've tried with both 2.0 and 3.0, but the problem was that I tried to "make" with the 2.0, then with the 3.0 without doing a "make clean".

As you said, my issue is verified only with the older versions of SWIG.
Thank you for getting me in the right direction!
