### ISSUE TITLE
Megacmd - Raspbian - get command or megacmd-get dont work with filenames with spaces

### ISSUE THREAD

**Issue by Pirolocito** [meganz/sdk#667]
Trying your linux cmd tool, get command cant find the files with spaces, even using autocompletion with \ or the file name in " or '. However mv works and it is possible to change the file name that had spaces, and then download it. 

The software using the same files with spaces work in sync mode.

Version: raspbian armhf, running in multiarch in arm64 Ubuntu Xenial

**Comment by polmr** [comment]
Hi @Pirolocito , sorry for the late reply.
I'm afraid I can't reproduce that. 
getting a file with spaces works fine in both interactive and non-interactive mode.
Escaping the spaces with `\ ` or surrounding by `"`. Example:
`get a\ subfolder/a\ file\ with\ spaces`
or
`get "a subfolder/a file with spaces"`
If you still can't, can you please paste a failing command here, in case we are missing something here
