### ISSUE TITLE
mega-cmd Linux Debian 8 run as service

### ISSUE THREAD

**Issue by djmaximal** [meganz/sdk#670]
Hi!

I installed this package:
https://mega.nz/linux/MEGAsync/Debian_8.0/amd64/megacmd-Debian_8.0_amd64.deb

mega-cmd interactive mode working, but when i try use non-interactive commands, like mega-login, i get error:
Unable to connect to service: error=111
Please ensure mega-cmd is running

Hot to run mega-cmd as service on Debian 8 Linux amd64!

**Comment by polmr** [comment]
with the version released, this could do:
(mega-cmd 2>&1 > megacmd.log &)
