### ISSUE TITLE
Use mega-cmd

### ISSUE THREAD

**Issue by raspifr** [meganz/sdk#672]
Hi,
I installed this package:
https://mega.nz/linux/MEGAsync/Debian_8.0/amd64/megacmd-Debian_8.0_amd64.deb

mega-cmd interactive mode working, but when I try use non-interactive commands, like mega-login, I get error:
**_Unable to connect to service: error=111
Please ensure mega-cmd is running_**

I tried to use "mega-cmd 2>&1 > /tmp/megacmd.log &" and to run "mega-login _email password_" but I get error:
**_Unable to connect to service: error=111
Please ensure mega-cmd is running_**

**_[2]+  Stopped                 mega-cmd 2>&1 > /tmp/megacmd.log_**

When I want to see /tmp/megacmd.log, it's empty.

**Comment by polmr** [comment]
As explained here: Use this with parenthesis:
```(mega-cmd 2>&1 > /tmp/megacmd.log &)```
There's a known bug that stops initialization in the background in the other case. It'll be solved in the next release.
If that's not enough ensure there is no mega-cmd process running (`pgrep mega-cmd`) and star all over, executing
```mega-cmd```
in a terminal, and executing the client commands (`mega-XXX`) in another one.
Thus, you will see if there are any issues in running the "server" (mega-cmd). If you want more verbosity and the output in both the terminal and a file, you can use:

**Comment by raspifr** [comment]
I solved the problem.
I created a service " megacmd " which will thus be launched on boot. What allows me to execute the commands " mega-* " in a bash script.

**Comment by raspifr** [comment]
I meet another problem:

Having to execute the command of synchronization " mega-sync ", having to stop this synchronization (with options " -s " and " -d ") at the end, I have a network access strongly slows down until I restart my internet box !!!

**Comment by polmr** [comment]
Hi @raspifr, if megacmd is taking too much bandwith, you can limit it with the command speedlimit. To see how to use it:
`speedlimit --help`

**Comment by raspifr** [comment]
The slow internet access was of in my switch d-link. I changed it by a switch netgear and I do not have problem anymore of slowness.

Now I have another question : Can I synchronized only in 1 direction (my PC to mega account) and not the 2 directions (my PC to mega account and mega account to my PC? I woulkd just like that mega account are up-to-date towards my PC and not the opposite. Is it possible to do like that ?

**Comment by polmr** [comment]
Short answer: no, we currently don't support "one way sync".
However there's something you could do. You could invoke `mega-put` command periodically (in a loop / crontab/ whatever) with a folder you want to `upsync` . This will only upload the files that have been added or changed. BUT beware, for files updated, the file will be duplicated in your cloud folder!
e.g: 
`mega-find /onewaysync/upsync/`
```
/onewaysync/upsync/afolder/afile2.txt
/onewaysync/upsync/afolder/afile2.txt
```
And if ever you want to download the folder, two files will be downloaded:
```
localonewaysync/upsync/afolder/afile2.txt
localonewaysync/upsync/afolder/afile2 (1).txt
```
