### ISSUE TITLE
PHP script

### ISSUE THREAD

**Issue by dado4497** [meganz/sdk#674]
Hi,
I need to use the application on a PHP server.
I've seen the PHP example, but I need to use it on a web hosting, so I cannot modify variables or install applications, so the script as a lot errors.
Some errors are in megacli.php are
Fatal error: Call to undefined function dl() in mega/bindings/php/megaapi.php on line 5
Warning: include(mega.php): failed to open stream: No such file or directory in mega/bindings/php/megaapi.php on line 7

Warning: include(): Failed opening 'mega.php' for inclusion (include_path='.:/opt/cpanel/ea-php56/root/usr/share/pear:../../bindings/php:.libs') in mega/bindings/php/megaapi.php on line 7

Fatal error: Class 'MegaListener' not found in mega/bindings/php/megaapi.php on line 35

Can you tell me how to fix errors?

**Comment by sergiohs84** [comment]
Apologies for the late response. Please, give a try to the current SDK. If you still observe the issue, feel free to reopen the ticket. Thanks
