### ISSUE TITLE
megasimplesync does not follow symlinks

### ISSUE THREAD

**Issue by dan-cristian** [meganz/sdk#68]
megasimplesync does not follow symlinks and there is no command line parameter available.
worth adding a command line switch to enable symlinks transversal.

**Comment by javiserrano** [comment]
If you add `client->followsymlinks = true;` before `client->login`, that should do the trick.
Please ensure that the sync engine does not see any filesystem item twice!
Otherwise, you will have synchronization problems. That's the main reason because we don't enable this feature by default.
