### ISSUE TITLE
Add swig for c#

### ISSUE THREAD

**Issue by shinchiro** [meganz/sdk#70]
Can your team add the binding for c# please?

**Comment by javiserrano** [comment]
Please take a look at `bindings/wp8`. It contains C++/CLI bindings that we use to create our Windows Phone app (C#).

I hope that they are useful for you.

**Comment by shinchiro** [comment]
Not sure why I missed ur reply..I'm interested using mega sdk in my winform project. But the one inside `bindings/wp8` is windows phone project so I cannot link the project inside my winform project. I appreciate it if you add normal vcxproj that can be use inside c# console/winform/wpf project
