### ISSUE TITLE
Release 3.1.5, configure head 3.1.3

### ISSUE THREAD

**Issue by SergeyDjam** [meganz/sdk#711]
I download 3.1.5 sdk,
1. ./autogen.sh
2. ./configure

configure: Configured to build Mega SDK:

  SDK version:      3.1.3

?

**Comment by polmr** [comment]
fixed: https://github.com/meganz/sdk/commit/54394895a3ec7b5b3963e86837a5c748dbbdb1ed. Thanks for reporting
