### ISSUE TITLE
MEGAcmd 0.9.3.0 does NOT work on Win-XP (the same PC where MEGAsync does)

### ISSUE THREAD

**Issue by VitRom** [meganz/sdk#712]
$subj.

0.9.3.0 downloaded from MEGA "Apps" page a pair of days ago. The same is MEGAsync 0.9.3.0.
Nor extracted nor installed this MEGAcmd doesn't start at all ending with a "not a win-32 app" message.
I.e. it's compiled wrong, for an NT6+ branch only.

**Comment by polmr** [comment]
It should be working now

**Comment by VitRom** [comment]
It works.
Big thanks to the devteam.
