### ISSUE TITLE
mega-login Unable to connect to service: error=111 Please ensure mega-cmd is running

### ISSUE THREAD

**Issue by EnricoSx** [meganz/sdk#728]
sorry for this question :|, i'm a noob.
i installer megacmd deb file con debian 8
i want use non interactive mode
but i have always this error

```
mega-login
Unable to connect to service: error=111
Please ensure mega-cmd is running
```

what is the correct use with bash script?

**Comment by jdknox** [comment]
You need to make sure the `mega-cmd` "server" is running first before using any other commands.  Start up another shell and run `mega-cmd`, then in your first shell try `mega-login`.  You should see logging info pop up in the server/interactive shell.

**Comment by EnricoSx** [comment]
not work, but i read is bug
the correct command for server is
**(**mega-cmd > /dev/null &**)**
not
mega-cmd > /dev/null &
