### ISSUE TITLE
ERROR reading from socket

### ISSUE THREAD

**Issue by DanixPC** [meganz/sdk#747]
I was writing a .bat to authenticate in MEGAcmd using MEGAclient, and suddenly when I run the .bat I get this error:

MEGA CMD> [FATAL: 19:11:23] ERROR reading from socket
[Err: 19:11:23] command not found
[FATAL: 19:11:23] Unable to accept on outsocket 0 error: 10038

Code:
@echo off
"% ~ Dp0MegaClient.exe" login email password

It's strange that I had been testing this for a while and it worked for me, but this error suddenly originates.
It is the bat that comes in the default installation folder. Sorry for my bad English, I'm using a translator.

Thank you so much

**Comment by polmr** [comment]
Hi @DanixPC 
I would recommend you to simply add the folder where MegaClient.exe and the existing `.bat`s are located to your PATH with:
```$env:PATH += ";$env:LOCALAPPDATA\MEGAcmd"
```
as explained here: https://github.com/meganz/sdk/tree/master/examples/megacmd#windows
Thus, you will be able to simple put 
```mega-login email password```
in your custom .bat. 
The error seems to be an issue in the communications layer. Does it still happen if you restart your MEGAcmd server (ensure there is no MEGAcmd.exe process running before restarting)?
In any case, we have been re-implementing the communications to no longer use sockets. We will release a new version soon that's unlikely to present such issue.

**Comment by DanixPC** [comment]
Greetings and thanks for replying quickly.
The .bat is in the installation folder of MEGAcmd when I run it and this in turn is also running, to receive the commands.

The truth is that I am making an interface in visual studio that executes the bats with the information that the user enters, the program writes a .bat with the instructions to later execute it.
For example 2 text boxes with the email and the password, and a login button.

I hope you get the new version soon that does not use network sockets for this problem to be solved.

Thank you very much!

**Comment by polmr** [comment]
new version is out. It no longer uses network sockets.
