### ISSUE TITLE
[FreeBSD] ./include/mega/posix/megafs.h:32:10: fatal error: 'sys/vfs.h' file not found

### ISSUE THREAD

**Issue by albertobsd** [meganz/sdk#761]
./configure --enable-debug --with-cryptopp=/usr/local                                                                                         --with-sqlite=/usr/local --with-curl=/usr/local --with-freeimage=/usr/local --e                                                                                        nable-examples --with-readline=/usr/local --with-c-ares=/usr/local

After configure:

% make
make  all-recursive
Making all in include
  CXX      src/src_libmega_la-megaclient.lo
In file included from src/megaclient.cpp:22:
In file included from ./include/mega.h:77:
./include/mega/posix/megafs.h:32:10: fatal error: 'sys/vfs.h' file not found
#include <sys/vfs.h>
         ^~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/alberto/mega/sdk
*** Error code 1

Stop.
make[1]: stopped in /usr/home/alberto/mega/sdk
*** Error code 1

Stop.
make: stopped in /usr/home/alberto/mega/sdk

**Comment by polmr** [comment]
change that line for #include <sys/mount.h> and configure it with `--disable-megacmd`. It should work. We'll fix it

**Comment by polmr** [comment]
Branch `fixfreebsd` should work for you

**Comment by albertobsd** [comment]
Excelent!! It works well!
