### ISSUE TITLE
[Windows] App crashes after an attempt to login

### ISSUE THREAD

**Issue by JasmineMan** [meganz/sdk#764]
When I am trying to login using an exported folder URL the app (MEGAcmd.exe) just crashes.
Here is a sample on how I am using it:
`login "https://mega.nz/#someRandomStuff!thePartWithEncryptionKey"`
After confirming this command the process just stops working.
The only info I can supply is this:
`Uncaught exception at 0x00FF9463 in module MEGAcmd.exe: 0xC0000005: an attempt to read memory at 0x00000000`

**Comment by Corak667** [comment]
Admitting - same error on WinXPx32
http://f3.s.qip.ru/cMfvXgN2.png

**Comment by polmr** [comment]
Bug confirmed: this commit will fix it: https://github.com/meganz/sdk/commit/6646acc2a72780ef64f540c4c032017e35994515. There will be a new release soon with that fix included

**Comment by polmr** [comment]
new version released with fix
