### ISSUE TITLE
[FreeBSD] --enable-php swig2.0 (Must specify an input file.)

### ISSUE THREAD

**Issue by albertobsd** [meganz/sdk#769]
In configure:

% ./configure --enable-debug --with-cryptopp=/usr/local --with-sqlite=/usr/local --with-curl=/usr/local --with-freeimage=/usr/local --enable-examples --with-readline=/usr/local --with-cares=/usr/local --enable-php --disable-megacmd --with-sodium=/usr/local

....
  OBJCXXLD src/libmega.la
c++: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
c++: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
/usr/local/bin/swig2.0 -c++ -php -I./include -o bindings/php/megaapi_wrap.cpp
Must specify an input file. Use -help for available options.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/alberto/mega/sdk
*** Error code 1

Stop.
make[1]: stopped in /usr/home/alberto/mega/sdk
*** Error code 1

Stop.
make: stopped in /usr/home/alberto/mega/sdk

**Comment by polmr** [comment]
edit bindings/php/include.am and change:
```
bindings/php/megaapi_wrap.cpp: $(top_srcdir)/bindings/megaapi.i
       $(SWIG) $(SWIG_FLAGS_PHP) -I$(top_srcdir)/include -o $@ $<
```
by
```
bindings/php/megaapi_wrap.cpp: $(top_srcdir)/bindings/megaapi.i
        $(SWIG) $(SWIG_FLAGS_PHP) -I$(top_srcdir)/include -o $@ $(top_srcdir)/bindings/megaapi.i
```
and do configure and make again.
For some reason, prerrequisite substitution is not working (`$<` is not substituted)

**Comment by polmr** [comment]
This is already fixed in `master`
