### ISSUE TITLE
Mega Api browse file system

### ISSUE THREAD

**Issue by rsarov** [meganz/sdk#783]
how make `api->fetchNodes()` only for folders top level?
I have 150,000 files this is very long time
If I have 1,000,000 files. How to make quick access to them via MegaApi?

May by loginToFolder(), but if without shared access?
It is expected that the application will work with the end user, and full cache is not a good idea.

**Comment by sergiohs84** [comment]
Hi @rsarov 

The `fetchnodes()` returns the whole tree of the account, there's currently no way to fetch only the folders in the top level. However, a `fetchnodes()` performed for a large account with thousands or even millions of files/folders can take a while, but only the first time to feed the cache. Afterwards, only updates will be retrieved from server, reducing the required time to get the account's state.

Regarding the `loginToFolder()`, that function is intended to be used with public folder links, and it also retrieves the whole tree under the shared folder.

Let us know if we can help you in any way.

**Comment by rsarov** [comment]
Hi @sergiohs84 
I understand. It is necessary to try all options and choose the best.
Forward.Thank you.
