### ISSUE TITLE
cannot pass "make -j"

### ISSUE THREAD

**Issue by nar6du14** [meganz/sdk#79]
Hello,
I'm on ubuntu 14.04. I want to use the mage sdk but the "make -j" doesn't pass it seems like there is an infinite loop somewhere 

root@wambe:/home/nardu14/Bureau/PERSONAL PROJECT/sdk-master# make -j
make  all-recursive
make[1]: entrant dans le répertoire « /home/nardu14/Bureau/PERSONAL PROJECT/sdk-master »
Making all in include
make[2]: entrant dans le répertoire « /home/nardu14/Bureau/PERSONAL PROJECT/sdk-master/include »
make[2]: Rien à faire pour « all ».
make[2]: quittant le répertoire « /home/nardu14/Bureau/PERSONAL PROJECT/sdk-master/include »
make[2]: entrant dans le répertoire « /home/nardu14/Bureau/PERSONAL PROJECT/sdk-master »
  CXX      src/src_libmega_la-megaclient.lo
  CXX      src/src_libmega_la-attrmap.lo
  CXX      src/src_libmega_la-backofftimer.lo
  CXX      src/src_libmega_la-base64.lo
  CXX      src/src_libmega_la-command.lo
  CXX      src/src_libmega_la-commands.lo
  CXX      src/src_libmega_la-db.lo
  CXX      src/src_libmega_la-fileattributefetch.lo
  CXX      src/src_libmega_la-file.lo
  CXX      src/src_libmega_la-filefingerprint.lo
  CXX      src/src_libmega_la-gfx.lo
  CXX      src/src_libmega_la-http.lo
  CXX      src/src_libmega_la-json.lo
  CXX      src/src_libmega_la-filesystem.lo
  CXX      src/src_libmega_la-node.lo
  CXX      src/src_libmega_la-pubkeyaction.lo
  CXX      src/src_libmega_la-request.lo
  CXX      src/src_libmega_la-serialize64.lo
  CXX      src/src_libmega_la-share.lo
  CXX      src/src_libmega_la-sharenodekeys.lo
  CXX      src/src_libmega_la-sync.lo
  CXX      src/src_libmega_la-transfer.lo
  CXX      src/src_libmega_la-transferslot.lo
  CXX      src/src_libmega_la-treeproc.lo
  CXX      src/src_libmega_la-user.lo
  CXX      src/src_libmega_la-utils.lo
  CXX      src/src_libmega_la-logging.lo
  CXX      src/src_libmega_la-waiterbase.lo
  CXX      src/src_libmega_la-proxy.lo
  CXX      src/crypto/src_libmega_la-cryptopp.lo
  CXX      src/db/src_libmega_la-sqlite.lo
  CXX      src/gfx/src_libmega_la-external.lo
  CXX      src/src_libmega_la-megaapi_impl.lo
  CXX      src/src_libmega_la-megaapi.lo
  CXX      src/gfx/src_libmega_la-freeimage.lo
  CXX      src/posix/src_libmega_la-fs.lo
  CXX      src/posix/src_libmega_la-console.lo
  CXX      src/posix/src_libmega_la-net.lo
  CXX      src/posix/src_libmega_la-waiter.lo
  CXX      src/posix/src_libmega_la-consolewaiter.lo
  CXX      bindings/python/bindings_python__mega_la-megaapi_wrap.lo
  CXX      src/thread/src_libmega_la-posixthread.lo
  CXX      examples/examples_megacli-megacli.o
  CXX      examples/examples_megasimplesync-megasimplesync.o
src/megaapi_impl.cpp:42:0: warning: "_LARGEFILE64_SOURCE" redefined [enabled by default]
 #define _LARGEFILE64_SOURCE
 ^
In file included from /usr/include/inttypes.h:25:0,
                 from ./include/megaapi_impl.h:25,
                 from src/megaapi_impl.cpp:32:
/usr/include/features.h:166:0: note: this is the location of the previous definition
 # define _LARGEFILE64_SOURCE 1
 ^
^C^C^Z
^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^Z^Z^Z^C^C^C[1]+  Stopped                make -j

**Comment by wizzard** [comment]
Hello,
could you please try to use ```make -j1``` or just without -j flag: ```make``` ?

Please let me know how it works for you!

**Comment by pohutukawa** [comment]
Maybe we should change that in our documentation to use `make` without the `-j` flag in general. Those who know will always go and add the `-jN` to it anyway, I suppose.

**Comment by wizzard** [comment]
Thank you! I've just fixed README file, now we suggest to use ```make``` without any arguments.

**Comment by nar6du14** [comment]
with "make" and "make -j1" I get the following

it seems that  "sdk-master/src/libmega.la" is not found  



root@wambe:/home/nardu14/Bureau/PERSONAL PROJECT/sdk-master# make
make  all-recursive
make[1]: entrant dans le répertoire « /home/nardu14/Bureau/PERSONAL PROJECT/sdk-master »
Making all in include
make[2]: entrant dans le répertoire « /home/nardu14/Bureau/PERSONAL PROJECT/sdk-master/include »
make[2]: Rien à faire pour « all ».
make[2]: quittant le répertoire « /home/nardu14/Bureau/PERSONAL PROJECT/sdk-master/include »
make[2]: entrant dans le répertoire « /home/nardu14/Bureau/PERSONAL PROJECT/sdk-master »
  CXX      src/src_libmega_la-megaclient.lo
  CXX      src/src_libmega_la-attrmap.lo
  CXX      src/src_libmega_la-backofftimer.lo
  CXX      src/src_libmega_la-base64.lo
  CXX      src/src_libmega_la-command.lo
  CXX      src/src_libmega_la-commands.lo
  CXX      src/src_libmega_la-db.lo
  CXX      src/src_libmega_la-fileattributefetch.lo
  CXX      src/src_libmega_la-file.lo
  CXX      src/src_libmega_la-filefingerprint.lo
  CXX      src/src_libmega_la-filesystem.lo
  CXX      src/src_libmega_la-gfx.lo
  CXX      src/src_libmega_la-http.lo
  CXX      src/src_libmega_la-json.lo
  CXX      src/src_libmega_la-node.lo
  CXX      src/src_libmega_la-pubkeyaction.lo
  CXX      src/src_libmega_la-request.lo
  CXX      src/src_libmega_la-serialize64.lo
  CXX      src/src_libmega_la-share.lo
  CXX      src/src_libmega_la-sharenodekeys.lo
  CXX      src/src_libmega_la-sync.lo
  CXX      src/src_libmega_la-transfer.lo
  CXX      src/src_libmega_la-transferslot.lo
  CXX      src/src_libmega_la-treeproc.lo
  CXX      src/src_libmega_la-user.lo
  CXX      src/src_libmega_la-utils.lo
  CXX      src/src_libmega_la-logging.lo
  CXX      src/src_libmega_la-waiterbase.lo
  CXX      src/src_libmega_la-proxy.lo
  CXX      src/crypto/src_libmega_la-cryptopp.lo
  CXX      src/db/src_libmega_la-sqlite.lo
  CXX      src/src_libmega_la-mega_utf8proc.lo
  CXX      src/gfx/src_libmega_la-external.lo
  CXX      src/src_libmega_la-megaapi_impl.lo
src/megaapi_impl.cpp:42:0: warning: "_LARGEFILE64_SOURCE" redefined [enabled by default]
 #define _LARGEFILE64_SOURCE
 ^
In file included from /usr/include/inttypes.h:25:0,
                 from ./include/megaapi_impl.h:25,
                 from src/megaapi_impl.cpp:32:
/usr/include/features.h:166:0: note: this is the location of the previous definition
 # define _LARGEFILE64_SOURCE 1
 ^
  CXX      src/src_libmega_la-megaapi.lo
  CXX      src/gfx/src_libmega_la-freeimage.lo
  CXX      src/posix/src_libmega_la-fs.lo
  CXX      src/posix/src_libmega_la-console.lo
  CXX      src/posix/src_libmega_la-net.lo
  CXX      src/posix/src_libmega_la-waiter.lo
src/posix/waiter.cpp: In member function 'void mega::PosixWaiter::notify()':
src/posix/waiter.cpp:143:29: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
     write(m_pipe[1], "0", 1);
                             ^
  CXX      src/posix/src_libmega_la-consolewaiter.lo
  CXX      src/thread/src_libmega_la-posixthread.lo
  CXXLD    src/libmega.la
/usr/bin/swig -c++ -noruntime -threads -python -I./include -o bindings/python/megaapi_wrap.cpp bindings/megaapi.i
SWIG:1: Warning 120: -runtime, -noruntime command line options are deprecated.
  CXX      bindings/python/bindings_python__mega_la-megaapi_wrap.lo
  CXXLD    bindings/python/_mega.la
/bin/sed: can't read PROJECT/sdk-master/src/libmega.la: No such file or directory
libtool: link: `PROJECT/sdk-master/src/libmega.la' is not a valid libtool archive
make[2]: *** [bindings/python/_mega.la] Erreur 1
make[2]: quittant le répertoire « /home/nardu14/Bureau/PERSONAL PROJECT/sdk-master »
make[1]: *** [all-recursive] Erreur 1
make[1]: quittant le répertoire « /home/nardu14/Bureau/PERSONAL PROJECT/sdk-master »
make: *** [all] Erreur 2

**Comment by pohutukawa** [comment]
Could it be caused by the fact that you've got a space in the path name" (`PERSONAL PROJECT`)?

**Comment by wizzard** [comment]
the issue is the space in your folder name:
```
/bin/sed: can't read PROJECT/sdk-master/src/libmega.la: No such file or directory
libtool: link: `PROJECT/sdk-master/src/libmega.la' is not a valid libtool archive
```

try to build SDK project in your ```/tmp``` folder and see how it works for you.
