### ISSUE TITLE
megacmd: bulk rename or move

### ISSUE THREAD

**Issue by amper5and** [meganz/sdk#793]
Is there a way to move a bunch of files in one directory into another in the cmd line client? I'm aware of the `mv` method for renaming individual files/folders, but this doesn't accept wildcards AFAIK. Thanks!

**Comment by polmr** [comment]
We've just implemented that behaviour for `mv`. We will be releasing a new version in a few days. 
In the meantime, you can use this command using the non-interactive mode: 
```(IFS=$'\n\t'; for i in `mega-ls source`; do echo mega-mv "\"source/$i\"" destiny/; done)

**Comment by amper5and** [comment]
Thanks for your reply! I'm on Windows, so I'll need to script something different with batch files. Is the next release still a server-client type of concept? I read somewhere that you guys will be moving away from that. Thanks!

**Comment by polmr** [comment]
Yes, it will keep the server-client concept. However, we will separate the interactive shell and the server. It's explained in the updated Readme: https://github.com/meganz/sdk/tree/develop/examples/megacmd. 
May I ask: where did you read that we are moving away from that?

**Comment by amper5and** [comment]
@polmr, I can't remember, I think there some issue I was researching and someone replied to the OP that whatever change they had proposed might not work in the future because of a change in the megacmd server or something like that. Thinking back on it now, I probably misinterpreted the statement. 

I was hopeful, because I really need a way to use multiple accounts simultaneously through scripting. Will the next update permit multiple simultaneous account logins?

**Comment by polmr** [comment]
megacmd is not intended to work with multiple accounts simultaneously. Besides, that will violate our terms of Service for free accounts: You must not use multiple free accounts (see https://mega.nz/general)

**Comment by polmr** [comment]
The new version has been released. You should be able to use "mv" to copy several files/folders into a remote folder now.

**Comment by amper5and** [comment]
@polmr Got it. I have several PRO accounts. Thanks for your help!

**Comment by amper5and** [comment]
@polmr I just tried `mv * newfolder` where `newfolder` doesn't exist. I expected the command to create a new folder like it does with specific files/folders, but it doesn't work with error message `newfolder must be a valid folder`

Is this intended behavior?

**Comment by polmr** [comment]
Yes, that is intended. It is indeed the same behaviour as systems' `mv`, you need to `mkdir` it

**Comment by amper5and** [comment]
ok thanks
