### ISSUE TITLE
megamcd mega-import doesn't return anything on successful file import

### ISSUE THREAD

**Issue by amper5and** [meganz/sdk#796]
On Windows, I'm using the batch files to interact w/ the megacmd server through VBA in excel. 

When I use `mega-import` on a file, not folder, link, there is no output on `stdout`. If there is an error, there is an output on `stdout ` (not `stderr`, but I can work with that). 

With a folder link, a successful import gives a message on `stdout`.  An error also gives msg on `stdout.`

This discrepancy and the lack of success msg on file import is screwing up my import code for a specific application that reads `stdout`. 

Is it a known issue? Can it be fixed? Can I work around it?

**Comment by polmr** [comment]
All client scripts return an exit code != 0 in case of failure. You can use that to check if everything went fine. Plus, you can add "-v" to your command to increase verbosity (that is explained in `help`). Thus, you will get something printed on `stdout`

**Comment by amper5and** [comment]
Thanks for your help!
