### ISSUE TITLE
[Windows] New version 0.9.4 is unusable. Not responding to commands.

### ISSUE THREAD

**Issue by JasmineMan** [meganz/sdk#811]
![image](https://user-images.githubusercontent.com/19231456/30388037-1e937bee-98b7-11e7-9610-31f97335ee2e.png)
This image should tell all the story.
Whatever I type, after pressing Enter nothing happens. Literally.
I got this version from: https://mega.nz/cmd

**Comment by polmr** [comment]
That's odd. Is that happening right after installing the new version, or did it ever work fine with 0.9.4?

Let's try to see what is happening... 
Please, close all instances of MEGAcmd, and kill all MEGAcmd processes.
Then execute two instances of PowerShell and in the first one do:
$env:PATH += ";$env:LOCALAPPDATA\MEGAcmd"
MEGAcmd.exe --debug-full

In the second one:
$env:PATH += ";$env:LOCALAPPDATA\MEGAcmd"
MEGAcmdShell.exe

Then try to type your commands and show us what you get. The logs might contain some sensitive data. If you do not want to post it here, send it to support@mega.nz and refer this issue in your email.

**Comment by JasmineMan** [comment]
That is odd for sure.
It is happening right after the installation of 0.9.4. I was on 0.9.3 before.
Tried your guide several times. This is what I get:
![image](https://user-images.githubusercontent.com/19231456/30390130-c028bcfc-98bd-11e7-9505-fca0de802eed.png)
![image](https://user-images.githubusercontent.com/19231456/30390150-c7388ba8-98bd-11e7-863e-e453e7f930e8.png)
I decided to not create a text file with logs because there are no logs. When I am typing commands nothing happens in both windows.

**Comment by JasmineMan** [comment]
There is also a kind of strange behavior -- when I am launching the MEGAcmdShell I got three empty command lines and the first one has removed characters.

**Comment by polmr** [comment]
Interesting .... it looks like the server is trapped when trying to output the last character in the welcome message: `´` . There should be some extra output there before much other computation is done.
What is your code page? (execute the following in powershell):
```
chcp
```
Try with CP 850 (kill all megacmd.exe): 
```
chcp 850
MEGAcmd.exe
```

**Comment by JasmineMan** [comment]
Changing the code page is not helping. Originally it was 866, but nothing changed after setting it to 850.

**Comment by polmr** [comment]
mmm I guess we need further digging. Please, can you tell us what is your OS and system language?

**Comment by JasmineMan** [comment]
I am running Windows 10 x64 with russian language.

**Comment by Corak667** [comment]
Same there. No answers even with chcp 850 or 866
Both on Windows XPx32 and 7x64. Language - Russian
Also MegaShell works EXTREMELY slow - nearly 30 sec. per symbol.

**Comment by JasmineMan** [comment]
I must say that I am not experiencing these delays while trying to type something.

**Comment by polmr** [comment]
Hi @JasmineMan , I've been able to reproduce it by configuring my system to Russian. I believe this installer will fix it. Could you try it: https://mega.nz/#!4EhAWKoL!F3QKbKtzbvV25BQxIGsGOX1k7Xau8JsvDzLJFwbkhVU .

**Comment by JasmineMan** [comment]
Yes, it is working now, but I am still able to see empty command lines:
![image](https://user-images.githubusercontent.com/19231456/30443616-d3ea52fc-9988-11e7-8fcc-399519bb26cc.png)

**Comment by polmr** [comment]
Awesome. That's due to some minor timing issues. We'll work on that in the future. Thanks for reporting

**Comment by polmr** [comment]
New package available at https://mega.nz/cmd fixes this issue
