### ISSUE TITLE
Errors when selecting download directory "Unmatched owner", "Unexpected failure to access server: 122" and "Failed to access server: 231"

### ISSUE THREAD

**Issue by Corak667** [meganz/sdk#812]
Getting errors after starting server:
```
MEGAcmd.exe
Unmatched owner - current userАдминистраторы - Corak
ERROR: Pipe owner does not match current user!

MEGAclient.exe lcd "downloads"
Unexpected failure to access server: 122

MEGAclient.exe lpwd
Failed to access server: 231

```
http://f4.s.qip.ru/cMfvXjmf.png
http://f2.s.qip.ru/cMfvXjm9.png

**Comment by polmr** [comment]
I believe it to be related to this issue: https://github.com/meganz/MEGAsync/issues/76. This installer will probably solve that:  https://mega.nz/#!ddg02BRK!NlFotxrdymb1Uy-0_qz34rAtpvsIb_cYHRVVCMMarQ0 . We will officially release a fixed version in asap.

**Comment by polmr** [comment]
New package available at https://mega.nz/cmd should fix this issue

**Comment by Corak667** [comment]
Yes, now fixed, thanks!
http://f1.s.qip.ru/cMfvXjzt.png

**Comment by polmr** [comment]
awesome!
by the way, for your convenience, there are scripts to simply use commands like `mega-lpwd` or `mega-ls`. You only need to add the correct PATH to your environment, as explained here: https://github.com/meganz/sdk/tree/master/examples/megacmd#windows
