### ISSUE TITLE
Java SDK Compiling

### ISSUE THREAD

**Issue by fire855** [meganz/sdk#82]
Hello guys,

I'm trying to compile the new java sdk but I get this error:
configure: error: could not find jni.h, please specify JAVA include directory using --with-java-include-dir option.
And when I will add this option:
Command: ./configure --enable-java --with-java-include-dir /usr/lib/jvm/java-7-openjdk-amd64/
Error: checking build system type... Invalid configuration `/usr/lib/jvm/java-7-openjdk-amd64/': machine `/usr/lib/jvm/java-7-openjdk' not recognized
configure: error: /bin/bash ./config.sub /usr/lib/jvm/java-7-openjdk-amd64/ failed
How can I fix my problem?

Regards
Daniel

**Comment by wizzard** [comment]
Hello,

this is a know issue, I'm currently working on it.

Could you please provide me with the information which Linux distro are you using ?

**Comment by fire855** [comment]
I'm using Linux Mint 17.1 Cinnamon 64-bit.

**Comment by wizzard** [comment]
I'll update this issue, when we have a reliable fix to that issue.
No, we do not distribute prebuilt files.

**Comment by wizzard** [comment]
please try to run ```configure``` script as:
```
./configure --enable-java --with-java-include-dir=/usr/lib/jvm/java-7-openjdk-amd64/
```

Looks like you missed ```=``` equal symbol.

**Comment by fire855** [comment]
Ah, yeah. I also missed the include/
This command works:
./configure --enable-java --with-java-include-dir=/usr/lib/jvm/java-7-openjdk-amd64/include/
