### ISSUE TITLE
Sync Only Special Folders

### ISSUE THREAD

**Issue by ashutoshpw** [meganz/sdk#822]
I have two servers which is listed on meganz servers as 
/server1 & /server2

I need that on my server 1 only /server1 will be synced and on Server 2 only /server2 files should be synced.

Is it possible?

**Comment by polmr** [comment]
You can configure exclusions by name in MEGAsync. Go to Settings -> Advanced -> Exclude file and folder names -> Add. Then restart MEGAsync and add your synchronization.
If you are using `MEGAcmd`, we currently don't support such behaviour, but we will ;-)

**Comment by majuss** [comment]
Any news on the exclusion of files with MEGAcmd? My drive is getting flooded with temp files...

**Comment by ashutoshpw** [comment]
Since most of the servers are Linux servers with command line access.  Adding that functionality to MEGAcmd will be a better option.

**Comment by polmr** [comment]
"exclude" command has been added to MEGAcmd 0.9.6. See `exclude --help` for further info

**Comment by majuss** [comment]
When will the .db be available for Raspbian 9 32 bit?
