### ISSUE TITLE
No longer support Mac?

### ISSUE THREAD

**Issue by jimmyzzzzzzz** [meganz/sdk#824]
Followed steps in doc/OSX.txt and tried to build with xcode8 and xcode9 but it didn't work. error occurred during make
`/usr/local/opt/freeimage/include/FreeImage.h:153:17: error: typedef redefinition with different types ('int32_t' (aka 'int') vs 'signed char')
typedef int32_t BOOL;
                ^
/Applications/Xcode8.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/objc/objc.h:67:21: note: previous definition is
      here
typedef signed char BOOL; 
                    ^
1 error generated.`
If I delete --with-freeimage=/usr/local/opt/freeimage then ./configure would fail.

**Comment by polmr** [comment]
There's an issue with FreeImage. You can fix it by editing `/usr/local/opt/freeimage/include/FreeImage.h`
and surrounding 
```
typedef int32_t BOOL;
```
with
```
#ifndef __MACTYPES__
typedef int32_t BOOL;
#endif
```

**Comment by jimmyzzzzzzz** [comment]
Thanks. It worked
