### ISSUE TITLE
prebuilt static library for Mac

### ISSUE THREAD

**Issue by jimmyzzzzzzz** [meganz/sdk#838]
I'm using the sdk with cocoa applications, everything is working during runtime but I get 200+ warnings when building the app. These warnings are all similar to one below
`ld: warning: URGENT: building for OSX, but linking in object file (libcryptopp.a(hmac.o)) built for iOS. Note: This will be an error in the future.` Does there exist the build script or a link to prebuilt static libraries for Mac? Or I can share it once I'm finished building them myself.

**Comment by sergiohs84** [comment]
This issue is obsolete. If you still observe the issue, please, create a new issue. Thanks
