### ISSUE TITLE
Invite command does not recognise email address

### ISSUE THREAD

**Issue by steve4444** [meganz/sdk#851]
With MagaCmd, I get 

    No valid email provided

using the `invite` command, when the email address contains a dot before the @ symbol.
The same address works with the `share` command or through web app invitation.

**Comment by polmr** [comment]
There's a bug in the email validation used by "invite". Thanks for reporting. This loose validation fixes it: https://github.com/meganz/MEGAcmd/commit/5979358b9d30f480361f99061d050d0f7df9464c (MEGAcmd is being moved to an isolated repo) . It'll be included in the next release. Btw, "share" implies "invite". Hence it might be enough for you.

**Comment by steve4444** [comment]
Thanks for the fix. 
> Btw, "share" implies "invite". 

yes, but there is no possibility of setting a custom message. 
Among the other things, the custom message helps in fighting spam.
It would be a nice idea to allow a custom message with the "share" command too.
