### ISSUE TITLE
mega-cmd is causing 100% fseventsd usage on OS X

### ISSUE THREAD

**Issue by hyperknot** [meganz/sdk#877]
When using non-interactive mode:

1. I start a transfer with mega-put
2. The transfer completes
3. mega-cmd is making a continuous disk usage, causing fseventsd to have 100% CPU usage. 

This also makes apps like Dropbox have 100% CPU usage, so now 2 cores are 100% loaded.

The fix is to run mega-quit. That stops fseventsd usage. 

OS X 10.12.16

**Comment by polmr** [comment]
To be sincere... that does not ring any bell to us.
We subscribe to fsevents to get notifications of changes in files within a synchronized folder. `mega-put` should not trigger anything related to fsevents at all. Do you have synchronizations? Did you provide admin credentials the first time you opened MEGAcmd? (a popup is shown requiring you to do it).

**Comment by hyperknot** [comment]
I think fseventsd gets high usage if something else is modifying or updating some file metadata, maybe mega-cmd was doing it. Running mega-quit immediately stopped the problem.
I don't remember if I've given admin credentials or if it asked me.

**Comment by polmr** [comment]
repo moved to https://github.com/meganz/MEGAcmd and new versions have been released
