### ISSUE TITLE
README.md: apt command to install packages to speed up installation

### ISSUE THREAD

**Issue by GeneThomas** [meganz/sdk#891]
Please add  this to your README.md (for ubuntu/debian users):

sudo apt install libcurl4-openssl-dev libc-ares-dev libssl-dev libcrypto++-dev zlib1g-dev libsqlite3-dev libfreeimage-dev libsodium-dev libreadline-dev

will speed things up.

for red hat users (from memory):

yum install libcurl-devel c-ares-devel openssl-devel libcryptopp-devel zlib-devel sqlite-devel freeimage-devel libsodium-devel readline-devel

**Comment by sergiohs84** [comment]
Please, feel free to create a PR with your suggestions ;)
