### ISSUE TITLE
Cannot compile MEGASync using newest Crypto++ version

### ISSUE THREAD

**Issue by matejm** [meganz/sdk#935]
I was not exactly sure where should I write this issue, as I was compiling [MEGASync cilent](https://github.com/meganz/MEGAsync/tree/master/src/MEGASync), but this is clearly a sdk problem.

Running `make` command produces following error (platform: Arch Linux):
```
In file included from mega/include/mega/types.h:55:0,
                 from mega/include/mega/utils.h:25,
                 from mega/include/mega/attrmap.h:25,
                 from mega/src/attrmap.cpp:22:
mega/include/mega/crypto/cryptopp.h:61:26: error: ‘byte’ has not been declared
     static void genblock(byte* buf, int len);
                          ^~~~
mega/include/mega/crypto/cryptopp.h:94:12: error: ‘byte’ does not name a type
     static byte zeroiv[CryptoPP::AES::BLOCKSIZE];
            ^~~~
mega/include/mega/crypto/cryptopp.h:99:5: error: ‘byte’ does not name a type
     byte key[KEYLENGTH];
     ^~~~
mega/include/mega/crypto/cryptopp.h:103:23: error: ‘byte’ does not name a type
     void setkey(const byte*, int = 1);
                       ^~~~
mega/include/mega/crypto/cryptopp.h:115:22: error: ‘byte’ has not been declared
     void ecb_encrypt(byte*, byte* = NULL, unsigned = BLOCKSIZE);
                      ^~~~
mega/include/mega/crypto/cryptopp.h:115:29: error: ‘byte’ has not been declared
     void ecb_encrypt(byte*, byte* = NULL, unsigned = BLOCKSIZE);
.....
(actual error is much longer, but you probably get the idea)
```

The problem is that [latest Crypto++ release](https://github.com/weidai11/cryptopp/releases/tag/CRYPTOPP_6_0_0) - version `6_0_0` (released only 10 days ago) moved definition of `byte`  to their namespace, `CryptoPP::byte`. For more in-depth explanation and possible solution see this [link](https://www.cryptopp.com/wiki/Std::byte#The_Problem) from Crypto++ wiki.

**Comment by polmr** [comment]
It's fine here. We'll fix that asap @matejm . Thank's for the heads-up !

**Comment by polmr** [comment]
This commit: https://github.com/meganz/sdk/commit/222594ea17e6fe4fca9b42b28e3cce335c2ca60e on branch `cryptopp600support` should fix it

**Comment by matejm** [comment]
Thanks! Works for me.

**Comment by Archcar** [comment]
I'm a beginner using Manjaro. Since a week ago I cannot use Megasync. Could you, please, explain to me (step by step) how to fix it?
Many thanks.

**Comment by polmr** [comment]
The easiest way: use the official MEGAsync client provided for Arch Linux: https://mega.nz/sync . Download it and install it with `pacman -U megasync-x86_64.pkg.tar.xz`
