### ISSUE TITLE
How to use with python 3 on windows 10

### ISSUE THREAD

**Issue by Joseram0n** [meganz/sdk#959]
Binding guide says "The instructions given here are strictly only valid for Linux".
As title says I want to compile it and use on windows 10 with python.
I have tried to build it with msys and mingw32, but i get a lot of errors like "winhttp.h is missing...".

**Comment by WitalijBukatkin** [comment]
Hello, I have this problem. Did you decide?

**Comment by Joseram0n** [comment]
Hello Witalij Bukatkin,

I haven't solved the problem yet, I'm looking at other options.

2018-07-23 12:19 GMT+02:00 Witalij Bukatkin <notifications@github.com>:

**Comment by WitalijBukatkin** [comment]
I did so,
--with-winhttp=/usr/include/w32api

**Comment by sergiohs84** [comment]
WinHTTP is not supported any more since v7.1.0. All the platforms are based on libcurl nowadays.
Closing the ticket as obsolete. Thanks
