### ISSUE TITLE
Rust binding?

### ISSUE THREAD

**Issue by shinchiro** [meganz/sdk#98]
Is it possible to has rust binding for this library?

**Comment by pohutukawa** [comment]
We're using SWIG for creation of the different language bindings. As far as I know, SWIG does not provide bindings to Rust (probably as it's too new?). Therefore it's unlikely that we're going to provide Rust bindings ourselves. However, we're quite open to contributions ... ;-)

**Comment by shinchiro** [comment]
I see :)
